/*
###############################################################
#  Generated by:      Cadence Encounter 14.28-s033_1
#  OS:                Linux x86_64(Host ID onyx.clear.rice.edu)
#  Generated on:      Thu Mar  2 16:43:24 2023
#  Design:            top_module
#  Command:           saveNetlist final.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : N-2017.09-SP2
// Date      : Thu Mar  2 16:37:01 2023
/////////////////////////////////////////////////////////////
module top_module (
	in_clka, 
	in_clkb, 
	in_restart, 
	in_inserted_5, 
	in_inserted_1, 
	in_inserted_05, 
	in_inserted_025, 
	in_sel_a, 
	in_sel_b, 
	in_sel_c, 
	in_sel_d, 
	in_next, 
	in_finish, 
	out_change, 
	out_stock_a, 
	out_stock_b, 
	out_stock_c, 
	out_stock_d, 
	out_csel_a, 
	out_csel_b, 
	out_csel_c, 
	out_csel_d, 
	out_change_1, 
	out_change_05, 
	out_change_025, 
	out_spit_a, 
	out_spit_b, 
	out_spit_c, 
	out_spit_d, 
	out_state);
   input in_clka;
   input in_clkb;
   input in_restart;
   input [7:0] in_inserted_5;
   input [7:0] in_inserted_1;
   input [7:0] in_inserted_05;
   input [7:0] in_inserted_025;
   input in_sel_a;
   input in_sel_b;
   input in_sel_c;
   input in_sel_d;
   input in_next;
   input in_finish;
   output [15:0] out_change;
   output out_stock_a;
   output out_stock_b;
   output out_stock_c;
   output out_stock_d;
   output out_csel_a;
   output out_csel_b;
   output out_csel_c;
   output out_csel_d;
   output [7:0] out_change_1;
   output out_change_05;
   output out_change_025;
   output out_spit_a;
   output out_spit_b;
   output out_spit_c;
   output out_spit_d;
   output [1:0] out_state;

   // Internal wires
   wire \main_FSM_dut/n5 ;
   wire \main_FSM_dut/n4 ;
   wire \main_FSM_dut/n3 ;
   wire \main_FSM_dut/N38 ;
   wire \main_FSM_dut/N28 ;
   wire \main_FSM_dut/N27 ;
   wire \main_FSM_dut/next_out_state[1] ;
   wire \dp_dut/n291 ;
   wire \dp_dut/n290 ;
   wire \dp_dut/n289 ;
   wire \dp_dut/n288 ;
   wire \dp_dut/n287 ;
   wire \dp_dut/n286 ;
   wire \dp_dut/n285 ;
   wire \dp_dut/n284 ;
   wire \dp_dut/n283 ;
   wire \dp_dut/n282 ;
   wire \dp_dut/n281 ;
   wire \dp_dut/n280 ;
   wire \dp_dut/n279 ;
   wire \dp_dut/n278 ;
   wire \dp_dut/n277 ;
   wire \dp_dut/n276 ;
   wire \dp_dut/n275 ;
   wire \dp_dut/n274 ;
   wire \dp_dut/n273 ;
   wire \dp_dut/n272 ;
   wire \dp_dut/n271 ;
   wire \dp_dut/n270 ;
   wire \dp_dut/n269 ;
   wire \dp_dut/n268 ;
   wire \dp_dut/n267 ;
   wire \dp_dut/n266 ;
   wire \dp_dut/n265 ;
   wire \dp_dut/n264 ;
   wire \dp_dut/n263 ;
   wire \dp_dut/n262 ;
   wire \dp_dut/n261 ;
   wire \dp_dut/n260 ;
   wire \dp_dut/n259 ;
   wire \dp_dut/n258 ;
   wire \dp_dut/n257 ;
   wire \dp_dut/n256 ;
   wire \dp_dut/n255 ;
   wire \dp_dut/n254 ;
   wire \dp_dut/n253 ;
   wire \dp_dut/n252 ;
   wire \dp_dut/n251 ;
   wire \dp_dut/n250 ;
   wire \dp_dut/n249 ;
   wire \dp_dut/n248 ;
   wire \dp_dut/n247 ;
   wire \dp_dut/n246 ;
   wire \dp_dut/n245 ;
   wire \dp_dut/n244 ;
   wire \dp_dut/n243 ;
   wire \dp_dut/n242 ;
   wire \dp_dut/n241 ;
   wire \dp_dut/n240 ;
   wire \dp_dut/n239 ;
   wire \dp_dut/n238 ;
   wire \dp_dut/n237 ;
   wire \dp_dut/n236 ;
   wire \dp_dut/n235 ;
   wire \dp_dut/n234 ;
   wire \dp_dut/n233 ;
   wire \dp_dut/n232 ;
   wire \dp_dut/n231 ;
   wire \dp_dut/n230 ;
   wire \dp_dut/n229 ;
   wire \dp_dut/n228 ;
   wire \dp_dut/n227 ;
   wire \dp_dut/n226 ;
   wire \dp_dut/n225 ;
   wire \dp_dut/n224 ;
   wire \dp_dut/n223 ;
   wire \dp_dut/n222 ;
   wire \dp_dut/n221 ;
   wire \dp_dut/n220 ;
   wire \dp_dut/n219 ;
   wire \dp_dut/n218 ;
   wire \dp_dut/n217 ;
   wire \dp_dut/n216 ;
   wire \dp_dut/n215 ;
   wire \dp_dut/n214 ;
   wire \dp_dut/n213 ;
   wire \dp_dut/n212 ;
   wire \dp_dut/n211 ;
   wire \dp_dut/n210 ;
   wire \dp_dut/n209 ;
   wire \dp_dut/n208 ;
   wire \dp_dut/n207 ;
   wire \dp_dut/n206 ;
   wire \dp_dut/n205 ;
   wire \dp_dut/n204 ;
   wire \dp_dut/n203 ;
   wire \dp_dut/n202 ;
   wire \dp_dut/n201 ;
   wire \dp_dut/n200 ;
   wire \dp_dut/n199 ;
   wire \dp_dut/n198 ;
   wire \dp_dut/n197 ;
   wire \dp_dut/n196 ;
   wire \dp_dut/n195 ;
   wire \dp_dut/n194 ;
   wire \dp_dut/n193 ;
   wire \dp_dut/n192 ;
   wire \dp_dut/n191 ;
   wire \dp_dut/n190 ;
   wire \dp_dut/n189 ;
   wire \dp_dut/n188 ;
   wire \dp_dut/n187 ;
   wire \dp_dut/n186 ;
   wire \dp_dut/n185 ;
   wire \dp_dut/n184 ;
   wire \dp_dut/n183 ;
   wire \dp_dut/n182 ;
   wire \dp_dut/n181 ;
   wire \dp_dut/n180 ;
   wire \dp_dut/n179 ;
   wire \dp_dut/n178 ;
   wire \dp_dut/n177 ;
   wire \dp_dut/n176 ;
   wire \dp_dut/n175 ;
   wire \dp_dut/n174 ;
   wire \dp_dut/n173 ;
   wire \dp_dut/n172 ;
   wire \dp_dut/n171 ;
   wire \dp_dut/n170 ;
   wire \dp_dut/n169 ;
   wire \dp_dut/n168 ;
   wire \dp_dut/n167 ;
   wire \dp_dut/n166 ;
   wire \dp_dut/n165 ;
   wire \dp_dut/n164 ;
   wire \dp_dut/n163 ;
   wire \dp_dut/n162 ;
   wire \dp_dut/n161 ;
   wire \dp_dut/n160 ;
   wire \dp_dut/n159 ;
   wire \dp_dut/n158 ;
   wire \dp_dut/n156 ;
   wire \dp_dut/n155 ;
   wire \dp_dut/n154 ;
   wire \dp_dut/n153 ;
   wire \dp_dut/n152 ;
   wire \dp_dut/n151 ;
   wire \dp_dut/n150 ;
   wire \dp_dut/n149 ;
   wire \dp_dut/n148 ;
   wire \dp_dut/n147 ;
   wire \dp_dut/n146 ;
   wire \dp_dut/n145 ;
   wire \dp_dut/n144 ;
   wire \dp_dut/n143 ;
   wire \dp_dut/n142 ;
   wire \dp_dut/n141 ;
   wire \dp_dut/n140 ;
   wire \dp_dut/n139 ;
   wire \dp_dut/n138 ;
   wire \dp_dut/n137 ;
   wire \dp_dut/n136 ;
   wire \dp_dut/n135 ;
   wire \dp_dut/n134 ;
   wire \dp_dut/n133 ;
   wire \dp_dut/n132 ;
   wire \dp_dut/n131 ;
   wire \dp_dut/n128 ;
   wire \dp_dut/n126 ;
   wire \dp_dut/n125 ;
   wire \dp_dut/n124 ;
   wire \dp_dut/n123 ;
   wire \dp_dut/n122 ;
   wire \dp_dut/n121 ;
   wire \dp_dut/n120 ;
   wire \dp_dut/n119 ;
   wire \dp_dut/n118 ;
   wire \dp_dut/n117 ;
   wire \dp_dut/n116 ;
   wire \dp_dut/n115 ;
   wire \dp_dut/n114 ;
   wire \dp_dut/n113 ;
   wire \dp_dut/dp_cluster_1/N22 ;
   wire \dp_dut/dp_cluster_1/N23 ;
   wire \dp_dut/dp_cluster_1/N24 ;
   wire \dp_dut/dp_cluster_1/N28 ;
   wire \dp_dut/dp_cluster_0/N100 ;
   wire \dp_dut/dp_cluster_0/N101 ;
   wire \dp_dut/dp_cluster_0/N102 ;
   wire \dp_dut/dp_cluster_0/N103 ;
   wire \dp_dut/dp_cluster_0/N104 ;
   wire \dp_dut/dp_cluster_0/N105 ;
   wire \dp_dut/dp_cluster_0/N111 ;
   wire \dp_dut/dp_cluster_0/N112 ;
   wire \dp_dut/dp_cluster_0/N113 ;
   wire \dp_dut/dp_cluster_0/N114 ;
   wire \dp_dut/dp_cluster_0/N115 ;
   wire \dp_dut/dp_cluster_0/N116 ;
   wire \dp_dut/dp_cluster_0/N117 ;
   wire \dp_dut/dp_cluster_0/N118 ;
   wire \dp_dut/dp_cluster_0/N128 ;
   wire \dp_dut/dp_cluster_0/N129 ;
   wire \dp_dut/dp_cluster_0/N130 ;
   wire \dp_dut/dp_cluster_0/N131 ;
   wire \dp_dut/dp_cluster_0/N132 ;
   wire \dp_dut/dp_cluster_0/N133 ;
   wire \dp_dut/dp_cluster_0/N134 ;
   wire \dp_dut/dp_cluster_0/N135 ;
   wire \dp_dut/dp_cluster_0/N136 ;
   wire \dp_dut/dp_cluster_0/N137 ;
   wire \dp_dut/dp_cluster_0/N138 ;
   wire \dp_dut/dp_cluster_0/N139 ;
   wire \dp_dut/dp_cluster_0/N140 ;
   wire \dp_dut/dp_cluster_0/N80 ;
   wire \dp_dut/dp_cluster_0/N81 ;
   wire \dp_dut/dp_cluster_0/N82 ;
   wire \dp_dut/dp_cluster_0/N83 ;
   wire \dp_dut/dp_cluster_0/N84 ;
   wire \dp_dut/dp_cluster_0/N85 ;
   wire \dp_dut/dp_cluster_0/N86 ;
   wire \dp_dut/dp_cluster_0/N87 ;
   wire \dp_dut/dp_cluster_0/N88 ;
   wire \dp_dut/dp_cluster_0/N89 ;
   wire \dp_dut/dp_cluster_0/N90 ;
   wire \dp_dut/dp_cluster_0/N91 ;
   wire \dp_dut/dp_cluster_0/N92 ;
   wire \dp_dut/dp_cluster_0/N98 ;
   wire \dp_dut/dp_cluster_0/N99 ;
   wire \dp_dut/N206 ;
   wire \dp_dut/N205 ;
   wire \dp_dut/N204 ;
   wire \dp_dut/N203 ;
   wire \dp_dut/N202 ;
   wire \dp_dut/N201 ;
   wire \dp_dut/N200 ;
   wire \dp_dut/N199 ;
   wire \dp_dut/N198 ;
   wire \dp_dut/N197 ;
   wire \dp_dut/N196 ;
   wire \dp_dut/N195 ;
   wire \dp_dut/N194 ;
   wire \dp_dut/N193 ;
   wire \dp_dut/N192 ;
   wire \dp_dut/N191 ;
   wire \dp_dut/N190 ;
   wire \dp_dut/N189 ;
   wire \dp_dut/N188 ;
   wire \dp_dut/N187 ;
   wire \dp_dut/N186 ;
   wire \dp_dut/N185 ;
   wire \dp_dut/N184 ;
   wire \dp_dut/N183 ;
   wire \dp_dut/N182 ;
   wire \dp_dut/N181 ;
   wire \dp_dut/N180 ;
   wire \dp_dut/N179 ;
   wire \dp_dut/N178 ;
   wire \dp_dut/N177 ;
   wire \dp_dut/N176 ;
   wire \dp_dut/N175 ;
   wire \dp_dut/N158 ;
   wire \dp_dut/N156 ;
   wire \dp_dut/N155 ;
   wire \dp_dut/N154 ;
   wire \dp_dut/N153 ;
   wire \dp_dut/N152 ;
   wire \dp_dut/N151 ;
   wire \dp_dut/N150 ;
   wire \dp_dut/N149 ;
   wire \dp_dut/N148 ;
   wire \dp_dut/N147 ;
   wire \dp_dut/N146 ;
   wire \dp_dut/N145 ;
   wire \dp_dut/N144 ;
   wire \dp_dut/N143 ;
   wire \dp_dut/N142 ;
   wire \dp_dut/N141 ;
   wire \dp_dut/N53 ;
   wire \dp_dut/N52 ;
   wire \dp_dut/N51 ;
   wire \dp_dut/N50 ;
   wire \dp_dut/N49 ;
   wire \dp_dut/N48 ;
   wire \dp_dut/N47 ;
   wire \dp_dut/N46 ;
   wire \dp_dut/N45 ;
   wire \dp_dut/N44 ;
   wire \dp_dut/N43 ;
   wire \dp_dut/N42 ;
   wire \dp_dut/N41 ;
   wire \dp_dut/N40 ;
   wire \dp_dut/N39 ;
   wire \dp_dut/N36 ;
   wire \dp_dut/N35 ;
   wire \dp_dut/N34 ;
   wire \dp_dut/N33 ;
   wire \dp_dut/N32 ;
   wire \dp_dut/dp_cluster_1/add_0_root_add_65_3/carry[4] ;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire [1:0] cmd;
   wire [15:0] \dp_dut/inserted_money ;
   wire [6:0] \dp_dut/total_price ;
   wire [7:0] \dp_dut/item_d_num ;
   wire [7:0] \dp_dut/item_c_num ;
   wire [7:0] \dp_dut/item_b_num ;
   wire [7:0] \dp_dut/item_a_num ;
   wire [16:0] \dp_dut/r374/carry ;
   wire [8:0] \dp_dut/sub_125/carry ;
   wire [8:0] \dp_dut/sub_126/carry ;
   wire [8:0] \dp_dut/sub_127/carry ;
   wire [8:0] \dp_dut/sub_128/carry ;
   wire [15:1] \dp_dut/dp_cluster_0/add_3_root_add_103_5/carry ;
   wire [15:1] \dp_dut/dp_cluster_0/add_4_root_add_103_5/carry ;
   wire [15:1] \dp_dut/dp_cluster_0/add_1_root_add_103_5/carry ;
   wire [15:1] \dp_dut/dp_cluster_0/add_2_root_add_103_5/carry ;
   wire [15:1] \dp_dut/dp_cluster_0/add_0_root_add_103_5/carry ;

   NOR2X1 \main_FSM_dut/U9  (.Y(\main_FSM_dut/n5 ),
	.B(n84),
	.A(out_state[1]));
   AOI21X1 \main_FSM_dut/U8  (.Y(\main_FSM_dut/N27 ),
	.C(in_restart),
	.B(in_next),
	.A(\main_FSM_dut/n5 ));
   OR2X1 \main_FSM_dut/U7  (.Y(\main_FSM_dut/n3 ),
	.B(out_state[1]),
	.A(in_restart));
   OAI21X1 \main_FSM_dut/U6  (.Y(\main_FSM_dut/n4 ),
	.C(out_state[0]),
	.B(in_finish),
	.A(in_next));
   NOR2X1 \main_FSM_dut/U5  (.Y(\main_FSM_dut/N28 ),
	.B(\main_FSM_dut/n4 ),
	.A(\main_FSM_dut/n3 ));
   DFFNEGX1 \main_FSM_dut/out_cmd_reg[0]  (.Q(cmd[0]),
	.D(\main_FSM_dut/N38 ),
	.CLK(in_clkb));
   DFFNEGX1 \main_FSM_dut/out_cmd_reg[1]  (.Q(cmd[1]),
	.D(n83),
	.CLK(in_clkb));
   DFFNEGX1 \main_FSM_dut/next_out_state_reg[0]  (.Q(\main_FSM_dut/N38 ),
	.D(\main_FSM_dut/N27 ),
	.CLK(n57));
   DFFNEGX1 \main_FSM_dut/out_state_reg[1]  (.Q(out_state[1]),
	.D(\main_FSM_dut/next_out_state[1] ),
	.CLK(in_clkb));
   DFFNEGX1 \main_FSM_dut/next_out_state_reg[1]  (.Q(\main_FSM_dut/next_out_state[1] ),
	.D(\main_FSM_dut/N28 ),
	.CLK(n57));
   DFFNEGX1 \main_FSM_dut/out_state_reg[0]  (.Q(out_state[0]),
	.D(\main_FSM_dut/N38 ),
	.CLK(in_clkb));
   NAND2X1 \dp_dut/U278  (.Y(\dp_dut/n151 ),
	.B(cmd[1]),
	.A(cmd[0]));
   NAND2X1 \dp_dut/U277  (.Y(\dp_dut/n113 ),
	.B(n81),
	.A(cmd[1]));
   NAND3X1 \dp_dut/U276  (.Y(\dp_dut/n204 ),
	.C(n44),
	.B(n60),
	.A(n81));
   NOR2X1 \dp_dut/U275  (.Y(\dp_dut/n162 ),
	.B(in_restart),
	.A(n42));
   AOI21X1 \dp_dut/U274  (.Y(\dp_dut/n205 ),
	.C(\dp_dut/n162 ),
	.B(\dp_dut/N158 ),
	.A(n59));
   NOR2X1 \dp_dut/U272  (.Y(\dp_dut/n126 ),
	.B(n38),
	.A(n48));
   AOI21X1 \dp_dut/U271  (.Y(\dp_dut/n219 ),
	.C(n37),
	.B(n61),
	.A(n82));
   NOR2X1 \dp_dut/U270  (.Y(\dp_dut/n225 ),
	.B(\dp_dut/item_a_num [6]),
	.A(\dp_dut/item_a_num [7]));
   NAND3X1 \dp_dut/U269  (.Y(\dp_dut/n222 ),
	.C(\dp_dut/n225 ),
	.B(n113),
	.A(n114));
   NOR2X1 \dp_dut/U268  (.Y(\dp_dut/n224 ),
	.B(\dp_dut/item_a_num [2]),
	.A(\dp_dut/item_a_num [3]));
   NAND3X1 \dp_dut/U267  (.Y(\dp_dut/n223 ),
	.C(\dp_dut/n224 ),
	.B(n117),
	.A(n118));
   OR2X1 \dp_dut/U266  (.Y(out_stock_a),
	.B(\dp_dut/n223 ),
	.A(\dp_dut/n222 ));
   NOR2X1 \dp_dut/U265  (.Y(\dp_dut/n221 ),
	.B(n61),
	.A(\dp_dut/n151 ));
   NAND3X1 \dp_dut/U264  (.Y(\dp_dut/n220 ),
	.C(\dp_dut/n221 ),
	.B(out_stock_a),
	.A(n58));
   OAI21X1 \dp_dut/U263  (.Y(\dp_dut/n291 ),
	.C(\dp_dut/n220 ),
	.B(n137),
	.A(\dp_dut/n219 ));
   NAND3X1 \dp_dut/U262  (.Y(\dp_dut/n207 ),
	.C(cmd[0]),
	.B(n60),
	.A(\dp_dut/n151 ));
   NAND2X1 \dp_dut/U261  (.Y(\dp_dut/n122 ),
	.B(n43),
	.A(\dp_dut/N39 ));
   NOR2X1 \dp_dut/U260  (.Y(\dp_dut/n209 ),
	.B(n36),
	.A(n38));
   NAND2X1 \dp_dut/U259  (.Y(\dp_dut/n218 ),
	.B(\dp_dut/n209 ),
	.A(out_change_025));
   OAI21X1 \dp_dut/U258  (.Y(\dp_dut/n290 ),
	.C(\dp_dut/n218 ),
	.B(\dp_dut/n122 ),
	.A(\dp_dut/n207 ));
   NAND2X1 \dp_dut/U257  (.Y(\dp_dut/n121 ),
	.B(n46),
	.A(\dp_dut/N40 ));
   NAND2X1 \dp_dut/U256  (.Y(\dp_dut/n217 ),
	.B(\dp_dut/n209 ),
	.A(out_change_05));
   OAI21X1 \dp_dut/U255  (.Y(\dp_dut/n289 ),
	.C(\dp_dut/n217 ),
	.B(\dp_dut/n121 ),
	.A(\dp_dut/n207 ));
   NAND2X1 \dp_dut/U254  (.Y(\dp_dut/n120 ),
	.B(n41),
	.A(\dp_dut/N41 ));
   NAND2X1 \dp_dut/U253  (.Y(\dp_dut/n216 ),
	.B(\dp_dut/n209 ),
	.A(out_change_1[0]));
   OAI21X1 \dp_dut/U252  (.Y(\dp_dut/n288 ),
	.C(\dp_dut/n216 ),
	.B(\dp_dut/n120 ),
	.A(\dp_dut/n207 ));
   NAND2X1 \dp_dut/U251  (.Y(\dp_dut/n119 ),
	.B(n42),
	.A(\dp_dut/N42 ));
   NAND2X1 \dp_dut/U250  (.Y(\dp_dut/n215 ),
	.B(\dp_dut/n209 ),
	.A(out_change_1[1]));
   OAI21X1 \dp_dut/U249  (.Y(\dp_dut/n287 ),
	.C(\dp_dut/n215 ),
	.B(\dp_dut/n119 ),
	.A(\dp_dut/n207 ));
   NAND2X1 \dp_dut/U248  (.Y(\dp_dut/n118 ),
	.B(n46),
	.A(\dp_dut/N43 ));
   NAND2X1 \dp_dut/U247  (.Y(\dp_dut/n214 ),
	.B(\dp_dut/n209 ),
	.A(out_change_1[2]));
   OAI21X1 \dp_dut/U246  (.Y(\dp_dut/n286 ),
	.C(\dp_dut/n214 ),
	.B(\dp_dut/n118 ),
	.A(\dp_dut/n207 ));
   NAND2X1 \dp_dut/U245  (.Y(\dp_dut/n117 ),
	.B(n42),
	.A(\dp_dut/N44 ));
   NAND2X1 \dp_dut/U244  (.Y(\dp_dut/n213 ),
	.B(\dp_dut/n209 ),
	.A(out_change_1[3]));
   OAI21X1 \dp_dut/U243  (.Y(\dp_dut/n285 ),
	.C(\dp_dut/n213 ),
	.B(\dp_dut/n117 ),
	.A(\dp_dut/n207 ));
   NAND2X1 \dp_dut/U242  (.Y(\dp_dut/n116 ),
	.B(n44),
	.A(\dp_dut/N45 ));
   NAND2X1 \dp_dut/U241  (.Y(\dp_dut/n212 ),
	.B(\dp_dut/n209 ),
	.A(out_change_1[4]));
   OAI21X1 \dp_dut/U240  (.Y(\dp_dut/n284 ),
	.C(\dp_dut/n212 ),
	.B(\dp_dut/n116 ),
	.A(\dp_dut/n207 ));
   NAND2X1 \dp_dut/U239  (.Y(\dp_dut/n115 ),
	.B(n43),
	.A(\dp_dut/N46 ));
   NAND2X1 \dp_dut/U238  (.Y(\dp_dut/n211 ),
	.B(\dp_dut/n209 ),
	.A(out_change_1[5]));
   OAI21X1 \dp_dut/U237  (.Y(\dp_dut/n283 ),
	.C(\dp_dut/n211 ),
	.B(\dp_dut/n115 ),
	.A(\dp_dut/n207 ));
   NAND2X1 \dp_dut/U236  (.Y(\dp_dut/n114 ),
	.B(n44),
	.A(\dp_dut/N47 ));
   NAND2X1 \dp_dut/U235  (.Y(\dp_dut/n210 ),
	.B(\dp_dut/n209 ),
	.A(out_change_1[6]));
   OAI21X1 \dp_dut/U234  (.Y(\dp_dut/n282 ),
	.C(\dp_dut/n210 ),
	.B(\dp_dut/n114 ),
	.A(\dp_dut/n207 ));
   NAND2X1 \dp_dut/U233  (.Y(\dp_dut/n123 ),
	.B(n45),
	.A(\dp_dut/N48 ));
   NAND2X1 \dp_dut/U232  (.Y(\dp_dut/n208 ),
	.B(\dp_dut/n209 ),
	.A(out_change_1[7]));
   OAI21X1 \dp_dut/U231  (.Y(\dp_dut/n281 ),
	.C(\dp_dut/n208 ),
	.B(\dp_dut/n123 ),
	.A(\dp_dut/n207 ));
   AOI22X1 \dp_dut/U229  (.Y(\dp_dut/n206 ),
	.D(n38),
	.C(\dp_dut/N156 ),
	.B(\dp_dut/N53 ),
	.A(n1));
   OAI21X1 \dp_dut/U228  (.Y(\dp_dut/n280 ),
	.C(\dp_dut/n206 ),
	.B(n136),
	.A(n35));
   NAND2X1 \dp_dut/U226  (.Y(\dp_dut/n203 ),
	.B(n49),
	.A(\dp_dut/N182 ));
   OAI21X1 \dp_dut/U225  (.Y(\dp_dut/n279 ),
	.C(\dp_dut/n203 ),
	.B(n112),
	.A(n48));
   AOI21X1 \dp_dut/U224  (.Y(\dp_dut/n202 ),
	.C(\dp_dut/n162 ),
	.B(n49),
	.A(\dp_dut/N175 ));
   OAI21X1 \dp_dut/U223  (.Y(\dp_dut/n278 ),
	.C(\dp_dut/n202 ),
	.B(n118),
	.A(n47));
   NAND2X1 \dp_dut/U222  (.Y(\dp_dut/n201 ),
	.B(n49),
	.A(\dp_dut/N176 ));
   OAI21X1 \dp_dut/U221  (.Y(\dp_dut/n277 ),
	.C(\dp_dut/n201 ),
	.B(n117),
	.A(n48));
   NAND2X1 \dp_dut/U220  (.Y(\dp_dut/n200 ),
	.B(n49),
	.A(\dp_dut/N177 ));
   OAI21X1 \dp_dut/U219  (.Y(\dp_dut/n276 ),
	.C(\dp_dut/n200 ),
	.B(n116),
	.A(n47));
   NAND2X1 \dp_dut/U218  (.Y(\dp_dut/n199 ),
	.B(n49),
	.A(\dp_dut/N178 ));
   OAI21X1 \dp_dut/U217  (.Y(\dp_dut/n275 ),
	.C(\dp_dut/n199 ),
	.B(n115),
	.A(n48));
   NAND2X1 \dp_dut/U216  (.Y(\dp_dut/n198 ),
	.B(n49),
	.A(\dp_dut/N179 ));
   OAI21X1 \dp_dut/U215  (.Y(\dp_dut/n274 ),
	.C(\dp_dut/n198 ),
	.B(n114),
	.A(n47));
   NAND2X1 \dp_dut/U214  (.Y(\dp_dut/n197 ),
	.B(n49),
	.A(\dp_dut/N180 ));
   OAI21X1 \dp_dut/U213  (.Y(\dp_dut/n273 ),
	.C(\dp_dut/n197 ),
	.B(n113),
	.A(n48));
   NAND2X1 \dp_dut/U212  (.Y(\dp_dut/n196 ),
	.B(n49),
	.A(\dp_dut/N181 ));
   OAI21X1 \dp_dut/U211  (.Y(\dp_dut/n272 ),
	.C(\dp_dut/n196 ),
	.B(n119),
	.A(n48));
   NAND2X1 \dp_dut/U210  (.Y(\dp_dut/n195 ),
	.B(n49),
	.A(\dp_dut/N190 ));
   OAI21X1 \dp_dut/U209  (.Y(\dp_dut/n271 ),
	.C(\dp_dut/n195 ),
	.B(n103),
	.A(n48));
   NAND2X1 \dp_dut/U208  (.Y(\dp_dut/n194 ),
	.B(n49),
	.A(\dp_dut/N183 ));
   OAI21X1 \dp_dut/U207  (.Y(\dp_dut/n270 ),
	.C(\dp_dut/n194 ),
	.B(n109),
	.A(n48));
   NAND2X1 \dp_dut/U206  (.Y(\dp_dut/n193 ),
	.B(n49),
	.A(\dp_dut/N184 ));
   OAI21X1 \dp_dut/U205  (.Y(\dp_dut/n269 ),
	.C(\dp_dut/n193 ),
	.B(n108),
	.A(n48));
   AOI21X1 \dp_dut/U204  (.Y(\dp_dut/n192 ),
	.C(\dp_dut/n162 ),
	.B(n49),
	.A(\dp_dut/N185 ));
   OAI21X1 \dp_dut/U203  (.Y(\dp_dut/n268 ),
	.C(\dp_dut/n192 ),
	.B(n107),
	.A(n48));
   NAND2X1 \dp_dut/U202  (.Y(\dp_dut/n191 ),
	.B(n49),
	.A(\dp_dut/N186 ));
   OAI21X1 \dp_dut/U201  (.Y(\dp_dut/n267 ),
	.C(\dp_dut/n191 ),
	.B(n106),
	.A(n48));
   NAND2X1 \dp_dut/U200  (.Y(\dp_dut/n190 ),
	.B(n49),
	.A(\dp_dut/N187 ));
   OAI21X1 \dp_dut/U199  (.Y(\dp_dut/n266 ),
	.C(\dp_dut/n190 ),
	.B(n105),
	.A(n48));
   NAND2X1 \dp_dut/U198  (.Y(\dp_dut/n189 ),
	.B(n49),
	.A(\dp_dut/N188 ));
   OAI21X1 \dp_dut/U197  (.Y(\dp_dut/n265 ),
	.C(\dp_dut/n189 ),
	.B(n104),
	.A(n48));
   NAND2X1 \dp_dut/U196  (.Y(\dp_dut/n188 ),
	.B(n49),
	.A(\dp_dut/N189 ));
   OAI21X1 \dp_dut/U195  (.Y(\dp_dut/n264 ),
	.C(\dp_dut/n188 ),
	.B(n111),
	.A(n48));
   AOI21X1 \dp_dut/U194  (.Y(\dp_dut/n181 ),
	.C(n37),
	.B(n62),
	.A(n82));
   NOR2X1 \dp_dut/U193  (.Y(\dp_dut/n187 ),
	.B(\dp_dut/item_b_num [6]),
	.A(\dp_dut/item_b_num [7]));
   NAND3X1 \dp_dut/U192  (.Y(\dp_dut/n184 ),
	.C(\dp_dut/n187 ),
	.B(n104),
	.A(n105));
   NOR2X1 \dp_dut/U191  (.Y(\dp_dut/n186 ),
	.B(\dp_dut/item_b_num [2]),
	.A(\dp_dut/item_b_num [3]));
   NAND3X1 \dp_dut/U190  (.Y(\dp_dut/n185 ),
	.C(\dp_dut/n186 ),
	.B(n108),
	.A(n109));
   OR2X1 \dp_dut/U189  (.Y(out_stock_b),
	.B(\dp_dut/n185 ),
	.A(\dp_dut/n184 ));
   NOR2X1 \dp_dut/U188  (.Y(\dp_dut/n183 ),
	.B(n62),
	.A(\dp_dut/n151 ));
   NAND3X1 \dp_dut/U187  (.Y(\dp_dut/n182 ),
	.C(\dp_dut/n183 ),
	.B(out_stock_b),
	.A(n58));
   OAI21X1 \dp_dut/U186  (.Y(\dp_dut/n263 ),
	.C(\dp_dut/n182 ),
	.B(n110),
	.A(\dp_dut/n181 ));
   NAND2X1 \dp_dut/U185  (.Y(\dp_dut/n180 ),
	.B(n49),
	.A(\dp_dut/N198 ));
   OAI21X1 \dp_dut/U184  (.Y(\dp_dut/n262 ),
	.C(\dp_dut/n180 ),
	.B(n94),
	.A(n48));
   NAND2X1 \dp_dut/U183  (.Y(\dp_dut/n179 ),
	.B(n49),
	.A(\dp_dut/N191 ));
   OAI21X1 \dp_dut/U182  (.Y(\dp_dut/n261 ),
	.C(\dp_dut/n179 ),
	.B(n100),
	.A(n48));
   NAND2X1 \dp_dut/U181  (.Y(\dp_dut/n178 ),
	.B(n49),
	.A(\dp_dut/N192 ));
   OAI21X1 \dp_dut/U180  (.Y(\dp_dut/n260 ),
	.C(\dp_dut/n178 ),
	.B(n99),
	.A(n48));
   AOI21X1 \dp_dut/U179  (.Y(\dp_dut/n177 ),
	.C(\dp_dut/n162 ),
	.B(n49),
	.A(\dp_dut/N193 ));
   OAI21X1 \dp_dut/U178  (.Y(\dp_dut/n259 ),
	.C(\dp_dut/n177 ),
	.B(n98),
	.A(n47));
   NAND2X1 \dp_dut/U177  (.Y(\dp_dut/n176 ),
	.B(n49),
	.A(\dp_dut/N194 ));
   OAI21X1 \dp_dut/U176  (.Y(\dp_dut/n258 ),
	.C(\dp_dut/n176 ),
	.B(n97),
	.A(n47));
   NAND2X1 \dp_dut/U175  (.Y(\dp_dut/n175 ),
	.B(n49),
	.A(\dp_dut/N195 ));
   OAI21X1 \dp_dut/U174  (.Y(\dp_dut/n257 ),
	.C(\dp_dut/n175 ),
	.B(n96),
	.A(n47));
   NAND2X1 \dp_dut/U173  (.Y(\dp_dut/n174 ),
	.B(n49),
	.A(\dp_dut/N196 ));
   OAI21X1 \dp_dut/U172  (.Y(\dp_dut/n256 ),
	.C(\dp_dut/n174 ),
	.B(n95),
	.A(n47));
   NAND2X1 \dp_dut/U171  (.Y(\dp_dut/n173 ),
	.B(n49),
	.A(\dp_dut/N197 ));
   OAI21X1 \dp_dut/U170  (.Y(\dp_dut/n255 ),
	.C(\dp_dut/n173 ),
	.B(n102),
	.A(n47));
   AOI21X1 \dp_dut/U169  (.Y(\dp_dut/n166 ),
	.C(n37),
	.B(n63),
	.A(n82));
   NOR2X1 \dp_dut/U168  (.Y(\dp_dut/n172 ),
	.B(\dp_dut/item_c_num [6]),
	.A(\dp_dut/item_c_num [7]));
   NAND3X1 \dp_dut/U167  (.Y(\dp_dut/n169 ),
	.C(\dp_dut/n172 ),
	.B(n95),
	.A(n96));
   NOR2X1 \dp_dut/U166  (.Y(\dp_dut/n171 ),
	.B(\dp_dut/item_c_num [2]),
	.A(\dp_dut/item_c_num [3]));
   NAND3X1 \dp_dut/U165  (.Y(\dp_dut/n170 ),
	.C(\dp_dut/n171 ),
	.B(n99),
	.A(n100));
   OR2X1 \dp_dut/U164  (.Y(out_stock_c),
	.B(\dp_dut/n170 ),
	.A(\dp_dut/n169 ));
   NOR2X1 \dp_dut/U163  (.Y(\dp_dut/n168 ),
	.B(n63),
	.A(\dp_dut/n151 ));
   NAND3X1 \dp_dut/U162  (.Y(\dp_dut/n167 ),
	.C(\dp_dut/n168 ),
	.B(out_stock_c),
	.A(n58));
   OAI21X1 \dp_dut/U161  (.Y(\dp_dut/n254 ),
	.C(\dp_dut/n167 ),
	.B(n101),
	.A(\dp_dut/n166 ));
   NAND2X1 \dp_dut/U160  (.Y(\dp_dut/n165 ),
	.B(n49),
	.A(\dp_dut/N206 ));
   OAI21X1 \dp_dut/U159  (.Y(\dp_dut/n253 ),
	.C(\dp_dut/n165 ),
	.B(n85),
	.A(n47));
   NAND2X1 \dp_dut/U158  (.Y(\dp_dut/n164 ),
	.B(n49),
	.A(\dp_dut/N199 ));
   OAI21X1 \dp_dut/U157  (.Y(\dp_dut/n252 ),
	.C(\dp_dut/n164 ),
	.B(n91),
	.A(n47));
   NAND2X1 \dp_dut/U156  (.Y(\dp_dut/n163 ),
	.B(n49),
	.A(\dp_dut/N200 ));
   OAI21X1 \dp_dut/U155  (.Y(\dp_dut/n251 ),
	.C(\dp_dut/n163 ),
	.B(n90),
	.A(n47));
   AOI21X1 \dp_dut/U154  (.Y(\dp_dut/n161 ),
	.C(\dp_dut/n162 ),
	.B(n49),
	.A(\dp_dut/N201 ));
   OAI21X1 \dp_dut/U153  (.Y(\dp_dut/n250 ),
	.C(\dp_dut/n161 ),
	.B(n89),
	.A(n47));
   NAND2X1 \dp_dut/U152  (.Y(\dp_dut/n160 ),
	.B(n49),
	.A(\dp_dut/N202 ));
   OAI21X1 \dp_dut/U151  (.Y(\dp_dut/n249 ),
	.C(\dp_dut/n160 ),
	.B(n88),
	.A(n47));
   NAND2X1 \dp_dut/U150  (.Y(\dp_dut/n159 ),
	.B(n49),
	.A(\dp_dut/N203 ));
   OAI21X1 \dp_dut/U149  (.Y(\dp_dut/n248 ),
	.C(\dp_dut/n159 ),
	.B(n87),
	.A(n47));
   NAND2X1 \dp_dut/U148  (.Y(\dp_dut/n158 ),
	.B(n49),
	.A(\dp_dut/N204 ));
   OAI21X1 \dp_dut/U147  (.Y(\dp_dut/n247 ),
	.C(\dp_dut/n158 ),
	.B(n86),
	.A(n47));
   NAND2X1 \dp_dut/U146  (.Y(\dp_dut/n156 ),
	.B(n49),
	.A(\dp_dut/N205 ));
   OAI21X1 \dp_dut/U145  (.Y(\dp_dut/n246 ),
	.C(\dp_dut/n156 ),
	.B(n93),
	.A(n47));
   AOI21X1 \dp_dut/U144  (.Y(\dp_dut/n148 ),
	.C(n37),
	.B(n64),
	.A(n82));
   NOR2X1 \dp_dut/U143  (.Y(\dp_dut/n155 ),
	.B(\dp_dut/item_d_num [6]),
	.A(\dp_dut/item_d_num [7]));
   NAND3X1 \dp_dut/U142  (.Y(\dp_dut/n152 ),
	.C(\dp_dut/n155 ),
	.B(n86),
	.A(n87));
   NOR2X1 \dp_dut/U141  (.Y(\dp_dut/n154 ),
	.B(\dp_dut/item_d_num [2]),
	.A(\dp_dut/item_d_num [3]));
   NAND3X1 \dp_dut/U140  (.Y(\dp_dut/n153 ),
	.C(\dp_dut/n154 ),
	.B(n90),
	.A(n91));
   OR2X1 \dp_dut/U139  (.Y(out_stock_d),
	.B(\dp_dut/n153 ),
	.A(\dp_dut/n152 ));
   NOR2X1 \dp_dut/U138  (.Y(\dp_dut/n150 ),
	.B(n64),
	.A(\dp_dut/n151 ));
   NAND3X1 \dp_dut/U137  (.Y(\dp_dut/n149 ),
	.C(\dp_dut/n150 ),
	.B(out_stock_d),
	.A(n58));
   OAI21X1 \dp_dut/U136  (.Y(\dp_dut/n245 ),
	.C(\dp_dut/n149 ),
	.B(n92),
	.A(\dp_dut/n148 ));
   NAND2X1 \dp_dut/U135  (.Y(\dp_dut/n124 ),
	.B(n58),
	.A(n59));
   NAND2X1 \dp_dut/U134  (.Y(\dp_dut/n147 ),
	.B(n37),
	.A(out_spit_a));
   OAI21X1 \dp_dut/U133  (.Y(\dp_dut/n244 ),
	.C(\dp_dut/n147 ),
	.B(n137),
	.A(\dp_dut/n124 ));
   NAND2X1 \dp_dut/U132  (.Y(\dp_dut/n146 ),
	.B(n37),
	.A(out_spit_b));
   OAI21X1 \dp_dut/U131  (.Y(\dp_dut/n243 ),
	.C(\dp_dut/n146 ),
	.B(n110),
	.A(\dp_dut/n124 ));
   NAND2X1 \dp_dut/U130  (.Y(\dp_dut/n145 ),
	.B(n37),
	.A(out_spit_c));
   OAI21X1 \dp_dut/U129  (.Y(\dp_dut/n242 ),
	.C(\dp_dut/n145 ),
	.B(n101),
	.A(\dp_dut/n124 ));
   AOI22X1 \dp_dut/U128  (.Y(\dp_dut/n144 ),
	.D(n38),
	.C(\dp_dut/N141 ),
	.B(\dp_dut/N141 ),
	.A(n1));
   OAI21X1 \dp_dut/U127  (.Y(\dp_dut/n241 ),
	.C(\dp_dut/n144 ),
	.B(n120),
	.A(n35));
   AOI22X1 \dp_dut/U126  (.Y(\dp_dut/n143 ),
	.D(n38),
	.C(\dp_dut/N142 ),
	.B(\dp_dut/N39 ),
	.A(n1));
   OAI21X1 \dp_dut/U125  (.Y(\dp_dut/n240 ),
	.C(\dp_dut/n143 ),
	.B(n121),
	.A(n35));
   AOI22X1 \dp_dut/U124  (.Y(\dp_dut/n142 ),
	.D(n38),
	.C(\dp_dut/N143 ),
	.B(\dp_dut/N40 ),
	.A(n1));
   OAI21X1 \dp_dut/U123  (.Y(\dp_dut/n239 ),
	.C(\dp_dut/n142 ),
	.B(n122),
	.A(n35));
   AOI22X1 \dp_dut/U122  (.Y(\dp_dut/n141 ),
	.D(n38),
	.C(\dp_dut/N144 ),
	.B(\dp_dut/N41 ),
	.A(n1));
   OAI21X1 \dp_dut/U121  (.Y(\dp_dut/n238 ),
	.C(\dp_dut/n141 ),
	.B(n123),
	.A(n35));
   AOI22X1 \dp_dut/U120  (.Y(\dp_dut/n140 ),
	.D(n38),
	.C(\dp_dut/N145 ),
	.B(\dp_dut/N42 ),
	.A(n1));
   OAI21X1 \dp_dut/U119  (.Y(\dp_dut/n237 ),
	.C(\dp_dut/n140 ),
	.B(n124),
	.A(n35));
   AOI22X1 \dp_dut/U118  (.Y(\dp_dut/n139 ),
	.D(n38),
	.C(\dp_dut/N146 ),
	.B(\dp_dut/N43 ),
	.A(n1));
   OAI21X1 \dp_dut/U117  (.Y(\dp_dut/n236 ),
	.C(\dp_dut/n139 ),
	.B(n125),
	.A(n35));
   AOI22X1 \dp_dut/U116  (.Y(\dp_dut/n138 ),
	.D(n38),
	.C(\dp_dut/N147 ),
	.B(\dp_dut/N44 ),
	.A(n1));
   OAI21X1 \dp_dut/U115  (.Y(\dp_dut/n235 ),
	.C(\dp_dut/n138 ),
	.B(n127),
	.A(n35));
   AOI22X1 \dp_dut/U114  (.Y(\dp_dut/n137 ),
	.D(n38),
	.C(\dp_dut/N148 ),
	.B(\dp_dut/N45 ),
	.A(n1));
   OAI21X1 \dp_dut/U113  (.Y(\dp_dut/n234 ),
	.C(\dp_dut/n137 ),
	.B(n128),
	.A(n35));
   AOI22X1 \dp_dut/U112  (.Y(\dp_dut/n136 ),
	.D(n38),
	.C(\dp_dut/N149 ),
	.B(\dp_dut/N46 ),
	.A(n1));
   OAI21X1 \dp_dut/U111  (.Y(\dp_dut/n233 ),
	.C(\dp_dut/n136 ),
	.B(n129),
	.A(n35));
   AOI22X1 \dp_dut/U110  (.Y(\dp_dut/n135 ),
	.D(n38),
	.C(\dp_dut/N150 ),
	.B(\dp_dut/N47 ),
	.A(n1));
   OAI21X1 \dp_dut/U109  (.Y(\dp_dut/n232 ),
	.C(\dp_dut/n135 ),
	.B(n130),
	.A(n35));
   AOI22X1 \dp_dut/U108  (.Y(\dp_dut/n134 ),
	.D(n38),
	.C(\dp_dut/N151 ),
	.B(\dp_dut/N48 ),
	.A(n1));
   OAI21X1 \dp_dut/U107  (.Y(\dp_dut/n231 ),
	.C(\dp_dut/n134 ),
	.B(n131),
	.A(n35));
   AOI22X1 \dp_dut/U106  (.Y(\dp_dut/n133 ),
	.D(n38),
	.C(\dp_dut/N152 ),
	.B(\dp_dut/N49 ),
	.A(n1));
   OAI21X1 \dp_dut/U105  (.Y(\dp_dut/n230 ),
	.C(\dp_dut/n133 ),
	.B(n132),
	.A(n35));
   AOI22X1 \dp_dut/U104  (.Y(\dp_dut/n132 ),
	.D(n38),
	.C(\dp_dut/N153 ),
	.B(\dp_dut/N50 ),
	.A(n1));
   OAI21X1 \dp_dut/U103  (.Y(\dp_dut/n229 ),
	.C(\dp_dut/n132 ),
	.B(n133),
	.A(n35));
   AOI22X1 \dp_dut/U102  (.Y(\dp_dut/n131 ),
	.D(n38),
	.C(\dp_dut/N154 ),
	.B(\dp_dut/N51 ),
	.A(n1));
   OAI21X1 \dp_dut/U101  (.Y(\dp_dut/n228 ),
	.C(\dp_dut/n131 ),
	.B(n134),
	.A(n35));
   AOI22X1 \dp_dut/U100  (.Y(\dp_dut/n128 ),
	.D(n38),
	.C(\dp_dut/N155 ),
	.B(\dp_dut/N52 ),
	.A(n1));
   OAI21X1 \dp_dut/U99  (.Y(\dp_dut/n227 ),
	.C(\dp_dut/n128 ),
	.B(n135),
	.A(n35));
   NAND2X1 \dp_dut/U98  (.Y(\dp_dut/n125 ),
	.B(n37),
	.A(out_spit_d));
   OAI21X1 \dp_dut/U97  (.Y(\dp_dut/n226 ),
	.C(\dp_dut/n125 ),
	.B(n92),
	.A(\dp_dut/n124 ));
   AND2X2 \dp_dut/U22  (.Y(out_change[0]),
	.B(\dp_dut/N141 ),
	.A(n41));
   AND2X2 \dp_dut/U14  (.Y(out_change[11]),
	.B(\dp_dut/N49 ),
	.A(n43));
   AND2X2 \dp_dut/U13  (.Y(out_change[12]),
	.B(\dp_dut/N50 ),
	.A(n45));
   AND2X2 \dp_dut/U12  (.Y(out_change[13]),
	.B(\dp_dut/N51 ),
	.A(n46));
   AND2X2 \dp_dut/U11  (.Y(out_change[14]),
	.B(\dp_dut/N52 ),
	.A(n41));
   AND2X2 \dp_dut/U10  (.Y(out_change[15]),
	.B(\dp_dut/N53 ),
	.A(n42));
   AND2X2 \dp_dut/U8  (.Y(\dp_dut/total_price [1]),
	.B(n43),
	.A(\dp_dut/N32 ));
   AND2X2 \dp_dut/U7  (.Y(\dp_dut/total_price [2]),
	.B(n44),
	.A(\dp_dut/N33 ));
   AND2X2 \dp_dut/U5  (.Y(\dp_dut/total_price [4]),
	.B(n45),
	.A(\dp_dut/N35 ));
   AND2X2 \dp_dut/U4  (.Y(\dp_dut/total_price [5]),
	.B(n41),
	.A(\dp_dut/N36 ));
   DFFNEGX1 \dp_dut/out_spit_d_reg  (.Q(out_spit_d),
	.D(\dp_dut/n226 ),
	.CLK(n57));
   DFFNEGX1 \dp_dut/out_spit_a_reg  (.Q(out_spit_a),
	.D(\dp_dut/n244 ),
	.CLK(n56));
   DFFNEGX1 \dp_dut/item_d_num_reg[7]  (.Q(\dp_dut/item_d_num [7]),
	.D(\dp_dut/n253 ),
	.CLK(n56));
   DFFNEGX1 \dp_dut/item_d_num_reg[5]  (.Q(\dp_dut/item_d_num [5]),
	.D(\dp_dut/n247 ),
	.CLK(n56));
   DFFNEGX1 \dp_dut/item_d_num_reg[4]  (.Q(\dp_dut/item_d_num [4]),
	.D(\dp_dut/n248 ),
	.CLK(n56));
   DFFNEGX1 \dp_dut/item_d_num_reg[3]  (.Q(\dp_dut/item_d_num [3]),
	.D(\dp_dut/n249 ),
	.CLK(n56));
   DFFNEGX1 \dp_dut/item_d_num_reg[2]  (.Q(\dp_dut/item_d_num [2]),
	.D(\dp_dut/n250 ),
	.CLK(n56));
   DFFNEGX1 \dp_dut/item_d_num_reg[1]  (.Q(\dp_dut/item_d_num [1]),
	.D(\dp_dut/n251 ),
	.CLK(n56));
   DFFNEGX1 \dp_dut/item_d_num_reg[0]  (.Q(\dp_dut/item_d_num [0]),
	.D(\dp_dut/n252 ),
	.CLK(n56));
   DFFNEGX1 \dp_dut/out_csel_d_reg  (.Q(out_csel_d),
	.D(\dp_dut/n245 ),
	.CLK(n56));
   DFFNEGX1 \dp_dut/item_d_num_reg[6]  (.Q(\dp_dut/item_d_num [6]),
	.D(\dp_dut/n246 ),
	.CLK(n56));
   DFFNEGX1 \dp_dut/out_spit_c_reg  (.Q(out_spit_c),
	.D(\dp_dut/n242 ),
	.CLK(n56));
   DFFNEGX1 \dp_dut/item_c_num_reg[7]  (.Q(\dp_dut/item_c_num [7]),
	.D(\dp_dut/n262 ),
	.CLK(n56));
   DFFNEGX1 \dp_dut/item_c_num_reg[5]  (.Q(\dp_dut/item_c_num [5]),
	.D(\dp_dut/n256 ),
	.CLK(n56));
   DFFNEGX1 \dp_dut/item_c_num_reg[4]  (.Q(\dp_dut/item_c_num [4]),
	.D(\dp_dut/n257 ),
	.CLK(n55));
   DFFNEGX1 \dp_dut/item_c_num_reg[3]  (.Q(\dp_dut/item_c_num [3]),
	.D(\dp_dut/n258 ),
	.CLK(n55));
   DFFNEGX1 \dp_dut/item_c_num_reg[2]  (.Q(\dp_dut/item_c_num [2]),
	.D(\dp_dut/n259 ),
	.CLK(n55));
   DFFNEGX1 \dp_dut/item_c_num_reg[1]  (.Q(\dp_dut/item_c_num [1]),
	.D(\dp_dut/n260 ),
	.CLK(n55));
   DFFNEGX1 \dp_dut/item_c_num_reg[0]  (.Q(\dp_dut/item_c_num [0]),
	.D(\dp_dut/n261 ),
	.CLK(n55));
   DFFNEGX1 \dp_dut/out_csel_c_reg  (.Q(out_csel_c),
	.D(\dp_dut/n254 ),
	.CLK(n55));
   DFFNEGX1 \dp_dut/item_c_num_reg[6]  (.Q(\dp_dut/item_c_num [6]),
	.D(\dp_dut/n255 ),
	.CLK(n55));
   DFFNEGX1 \dp_dut/out_spit_b_reg  (.Q(out_spit_b),
	.D(\dp_dut/n243 ),
	.CLK(n55));
   DFFNEGX1 \dp_dut/item_b_num_reg[7]  (.Q(\dp_dut/item_b_num [7]),
	.D(\dp_dut/n271 ),
	.CLK(n55));
   DFFNEGX1 \dp_dut/item_b_num_reg[5]  (.Q(\dp_dut/item_b_num [5]),
	.D(\dp_dut/n265 ),
	.CLK(n55));
   DFFNEGX1 \dp_dut/item_b_num_reg[4]  (.Q(\dp_dut/item_b_num [4]),
	.D(\dp_dut/n266 ),
	.CLK(n55));
   DFFNEGX1 \dp_dut/item_b_num_reg[3]  (.Q(\dp_dut/item_b_num [3]),
	.D(\dp_dut/n267 ),
	.CLK(n55));
   DFFNEGX1 \dp_dut/item_b_num_reg[2]  (.Q(\dp_dut/item_b_num [2]),
	.D(\dp_dut/n268 ),
	.CLK(n55));
   DFFNEGX1 \dp_dut/item_b_num_reg[1]  (.Q(\dp_dut/item_b_num [1]),
	.D(\dp_dut/n269 ),
	.CLK(n54));
   DFFNEGX1 \dp_dut/item_b_num_reg[0]  (.Q(\dp_dut/item_b_num [0]),
	.D(\dp_dut/n270 ),
	.CLK(n54));
   DFFNEGX1 \dp_dut/out_csel_b_reg  (.Q(out_csel_b),
	.D(\dp_dut/n263 ),
	.CLK(n54));
   DFFNEGX1 \dp_dut/item_b_num_reg[6]  (.Q(\dp_dut/item_b_num [6]),
	.D(\dp_dut/n264 ),
	.CLK(n54));
   DFFNEGX1 \dp_dut/item_a_num_reg[7]  (.Q(\dp_dut/item_a_num [7]),
	.D(\dp_dut/n279 ),
	.CLK(n54));
   DFFNEGX1 \dp_dut/item_a_num_reg[5]  (.Q(\dp_dut/item_a_num [5]),
	.D(\dp_dut/n273 ),
	.CLK(n54));
   DFFNEGX1 \dp_dut/item_a_num_reg[4]  (.Q(\dp_dut/item_a_num [4]),
	.D(\dp_dut/n274 ),
	.CLK(n54));
   DFFNEGX1 \dp_dut/item_a_num_reg[3]  (.Q(\dp_dut/item_a_num [3]),
	.D(\dp_dut/n275 ),
	.CLK(n54));
   DFFNEGX1 \dp_dut/item_a_num_reg[2]  (.Q(\dp_dut/item_a_num [2]),
	.D(\dp_dut/n276 ),
	.CLK(n54));
   DFFNEGX1 \dp_dut/item_a_num_reg[1]  (.Q(\dp_dut/item_a_num [1]),
	.D(\dp_dut/n277 ),
	.CLK(n54));
   DFFNEGX1 \dp_dut/item_a_num_reg[0]  (.Q(\dp_dut/item_a_num [0]),
	.D(\dp_dut/n278 ),
	.CLK(n54));
   DFFNEGX1 \dp_dut/item_a_num_reg[6]  (.Q(\dp_dut/item_a_num [6]),
	.D(\dp_dut/n272 ),
	.CLK(n54));
   DFFNEGX1 \dp_dut/inserted_money_reg[0]  (.Q(\dp_dut/N141 ),
	.D(\dp_dut/n241 ),
	.CLK(n54));
   DFFNEGX1 \dp_dut/inserted_money_reg[1]  (.Q(\dp_dut/inserted_money [1]),
	.D(\dp_dut/n240 ),
	.CLK(n53));
   DFFNEGX1 \dp_dut/inserted_money_reg[2]  (.Q(\dp_dut/inserted_money [2]),
	.D(\dp_dut/n239 ),
	.CLK(n53));
   DFFNEGX1 \dp_dut/inserted_money_reg[3]  (.Q(\dp_dut/inserted_money [3]),
	.D(\dp_dut/n238 ),
	.CLK(n53));
   DFFNEGX1 \dp_dut/inserted_money_reg[4]  (.Q(\dp_dut/inserted_money [4]),
	.D(\dp_dut/n237 ),
	.CLK(n53));
   DFFNEGX1 \dp_dut/inserted_money_reg[5]  (.Q(\dp_dut/inserted_money [5]),
	.D(\dp_dut/n236 ),
	.CLK(n53));
   DFFNEGX1 \dp_dut/inserted_money_reg[6]  (.Q(\dp_dut/inserted_money [6]),
	.D(\dp_dut/n235 ),
	.CLK(n53));
   DFFNEGX1 \dp_dut/inserted_money_reg[7]  (.Q(\dp_dut/inserted_money [7]),
	.D(\dp_dut/n234 ),
	.CLK(n53));
   DFFNEGX1 \dp_dut/inserted_money_reg[8]  (.Q(\dp_dut/inserted_money [8]),
	.D(\dp_dut/n233 ),
	.CLK(n53));
   DFFNEGX1 \dp_dut/inserted_money_reg[9]  (.Q(\dp_dut/inserted_money [9]),
	.D(\dp_dut/n232 ),
	.CLK(n53));
   DFFNEGX1 \dp_dut/inserted_money_reg[10]  (.Q(\dp_dut/inserted_money [10]),
	.D(\dp_dut/n231 ),
	.CLK(n53));
   DFFNEGX1 \dp_dut/inserted_money_reg[11]  (.Q(\dp_dut/inserted_money [11]),
	.D(\dp_dut/n230 ),
	.CLK(n53));
   DFFNEGX1 \dp_dut/inserted_money_reg[12]  (.Q(\dp_dut/inserted_money [12]),
	.D(\dp_dut/n229 ),
	.CLK(n53));
   DFFNEGX1 \dp_dut/inserted_money_reg[13]  (.Q(\dp_dut/inserted_money [13]),
	.D(\dp_dut/n228 ),
	.CLK(n53));
   DFFNEGX1 \dp_dut/inserted_money_reg[14]  (.Q(\dp_dut/inserted_money [14]),
	.D(\dp_dut/n227 ),
	.CLK(n52));
   DFFNEGX1 \dp_dut/inserted_money_reg[15]  (.Q(\dp_dut/inserted_money [15]),
	.D(\dp_dut/n280 ),
	.CLK(n52));
   DFFNEGX1 \dp_dut/out_change_1_reg[7]  (.Q(out_change_1[7]),
	.D(\dp_dut/n281 ),
	.CLK(n52));
   DFFNEGX1 \dp_dut/out_change_1_reg[6]  (.Q(out_change_1[6]),
	.D(\dp_dut/n282 ),
	.CLK(n52));
   DFFNEGX1 \dp_dut/out_change_1_reg[5]  (.Q(out_change_1[5]),
	.D(\dp_dut/n283 ),
	.CLK(n52));
   DFFNEGX1 \dp_dut/out_change_1_reg[4]  (.Q(out_change_1[4]),
	.D(\dp_dut/n284 ),
	.CLK(n52));
   DFFNEGX1 \dp_dut/out_change_1_reg[3]  (.Q(out_change_1[3]),
	.D(\dp_dut/n285 ),
	.CLK(n52));
   DFFNEGX1 \dp_dut/out_change_1_reg[2]  (.Q(out_change_1[2]),
	.D(\dp_dut/n286 ),
	.CLK(n52));
   DFFNEGX1 \dp_dut/out_change_1_reg[1]  (.Q(out_change_1[1]),
	.D(\dp_dut/n287 ),
	.CLK(n52));
   DFFNEGX1 \dp_dut/out_change_1_reg[0]  (.Q(out_change_1[0]),
	.D(\dp_dut/n288 ),
	.CLK(n52));
   DFFNEGX1 \dp_dut/out_change_05_reg  (.Q(out_change_05),
	.D(\dp_dut/n289 ),
	.CLK(n52));
   DFFNEGX1 \dp_dut/out_change_025_reg  (.Q(out_change_025),
	.D(\dp_dut/n290 ),
	.CLK(n52));
   DFFNEGX1 \dp_dut/out_csel_a_reg  (.Q(out_csel_a),
	.D(\dp_dut/n291 ),
	.CLK(n52));
   FAX1 \dp_dut/r374/U2_2  (.YS(\dp_dut/N40 ),
	.YC(\dp_dut/r374/carry [3]),
	.C(\dp_dut/r374/carry [2]),
	.B(n77),
	.A(\dp_dut/inserted_money [2]));
   FAX1 \dp_dut/r374/U2_3  (.YS(\dp_dut/N41 ),
	.YC(\dp_dut/r374/carry [4]),
	.C(\dp_dut/r374/carry [3]),
	.B(n4),
	.A(\dp_dut/inserted_money [3]));
   FAX1 \dp_dut/r374/U2_4  (.YS(\dp_dut/N42 ),
	.YC(\dp_dut/r374/carry [5]),
	.C(\dp_dut/r374/carry [4]),
	.B(n79),
	.A(\dp_dut/inserted_money [4]));
   FAX1 \dp_dut/r374/U2_5  (.YS(\dp_dut/N43 ),
	.YC(\dp_dut/r374/carry [6]),
	.C(\dp_dut/r374/carry [5]),
	.B(n80),
	.A(\dp_dut/inserted_money [5]));
   FAX1 \dp_dut/dp_cluster_0/add_3_root_add_103_5/U1_6  (.YS(\dp_dut/dp_cluster_0/N99 ),
	.YC(\dp_dut/dp_cluster_0/add_3_root_add_103_5/carry [7]),
	.C(n13),
	.B(in_inserted_1[3]),
	.A(n28));
   FAX1 \dp_dut/dp_cluster_0/add_3_root_add_103_5/U1_7  (.YS(\dp_dut/dp_cluster_0/N100 ),
	.YC(\dp_dut/dp_cluster_0/add_3_root_add_103_5/carry [8]),
	.C(\dp_dut/dp_cluster_0/add_3_root_add_103_5/carry [7]),
	.B(in_inserted_1[4]),
	.A(n29));
   FAX1 \dp_dut/dp_cluster_0/add_3_root_add_103_5/U1_8  (.YS(\dp_dut/dp_cluster_0/N101 ),
	.YC(\dp_dut/dp_cluster_0/add_3_root_add_103_5/carry [9]),
	.C(\dp_dut/dp_cluster_0/add_3_root_add_103_5/carry [8]),
	.B(in_inserted_1[5]),
	.A(n30));
   FAX1 \dp_dut/dp_cluster_0/add_3_root_add_103_5/U1_9  (.YS(\dp_dut/dp_cluster_0/N102 ),
	.YC(\dp_dut/dp_cluster_0/add_3_root_add_103_5/carry [10]),
	.C(\dp_dut/dp_cluster_0/add_3_root_add_103_5/carry [9]),
	.B(in_inserted_1[6]),
	.A(n31));
   FAX1 \dp_dut/dp_cluster_0/add_3_root_add_103_5/U1_10  (.YS(\dp_dut/dp_cluster_0/N103 ),
	.YC(\dp_dut/dp_cluster_0/add_3_root_add_103_5/carry [11]),
	.C(\dp_dut/dp_cluster_0/add_3_root_add_103_5/carry [10]),
	.B(in_inserted_1[7]),
	.A(n32));
   FAX1 \dp_dut/dp_cluster_0/add_4_root_add_103_5/U1_4  (.YS(\dp_dut/dp_cluster_0/N81 ),
	.YC(\dp_dut/dp_cluster_0/add_4_root_add_103_5/carry [5]),
	.C(n8),
	.B(n28),
	.A(\dp_dut/inserted_money [4]));
   FAX1 \dp_dut/dp_cluster_0/add_4_root_add_103_5/U1_5  (.YS(\dp_dut/dp_cluster_0/N82 ),
	.YC(\dp_dut/dp_cluster_0/add_4_root_add_103_5/carry [6]),
	.C(\dp_dut/dp_cluster_0/add_4_root_add_103_5/carry [5]),
	.B(n29),
	.A(\dp_dut/inserted_money [5]));
   FAX1 \dp_dut/dp_cluster_0/add_4_root_add_103_5/U1_6  (.YS(\dp_dut/dp_cluster_0/N83 ),
	.YC(\dp_dut/dp_cluster_0/add_4_root_add_103_5/carry [7]),
	.C(\dp_dut/dp_cluster_0/add_4_root_add_103_5/carry [6]),
	.B(n30),
	.A(\dp_dut/inserted_money [6]));
   FAX1 \dp_dut/dp_cluster_0/add_4_root_add_103_5/U1_7  (.YS(\dp_dut/dp_cluster_0/N84 ),
	.YC(\dp_dut/dp_cluster_0/add_4_root_add_103_5/carry [8]),
	.C(\dp_dut/dp_cluster_0/add_4_root_add_103_5/carry [7]),
	.B(n31),
	.A(\dp_dut/inserted_money [7]));
   FAX1 \dp_dut/dp_cluster_0/add_4_root_add_103_5/U1_8  (.YS(\dp_dut/dp_cluster_0/N85 ),
	.YC(\dp_dut/dp_cluster_0/add_4_root_add_103_5/carry [9]),
	.C(\dp_dut/dp_cluster_0/add_4_root_add_103_5/carry [8]),
	.B(n32),
	.A(\dp_dut/inserted_money [8]));
   FAX1 \dp_dut/dp_cluster_0/add_4_root_add_103_5/U1_9  (.YS(\dp_dut/dp_cluster_0/N86 ),
	.YC(\dp_dut/dp_cluster_0/add_4_root_add_103_5/carry [10]),
	.C(\dp_dut/dp_cluster_0/add_4_root_add_103_5/carry [9]),
	.B(n33),
	.A(\dp_dut/inserted_money [9]));
   FAX1 \dp_dut/dp_cluster_0/add_4_root_add_103_5/U1_10  (.YS(\dp_dut/dp_cluster_0/N87 ),
	.YC(\dp_dut/dp_cluster_0/add_4_root_add_103_5/carry [11]),
	.C(\dp_dut/dp_cluster_0/add_4_root_add_103_5/carry [10]),
	.B(n34),
	.A(\dp_dut/inserted_money [10]));
   FAX1 \dp_dut/dp_cluster_0/add_1_root_add_103_5/U1_4  (.YS(\dp_dut/dp_cluster_0/N129 ),
	.YC(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [5]),
	.C(n12),
	.B(in_inserted_1[1]),
	.A(\dp_dut/dp_cluster_0/N81 ));
   FAX1 \dp_dut/dp_cluster_0/add_1_root_add_103_5/U1_5  (.YS(\dp_dut/dp_cluster_0/N130 ),
	.YC(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [6]),
	.C(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [5]),
	.B(\dp_dut/dp_cluster_0/N98 ),
	.A(\dp_dut/dp_cluster_0/N82 ));
   FAX1 \dp_dut/dp_cluster_0/add_1_root_add_103_5/U1_6  (.YS(\dp_dut/dp_cluster_0/N131 ),
	.YC(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [7]),
	.C(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [6]),
	.B(\dp_dut/dp_cluster_0/N99 ),
	.A(\dp_dut/dp_cluster_0/N83 ));
   FAX1 \dp_dut/dp_cluster_0/add_1_root_add_103_5/U1_7  (.YS(\dp_dut/dp_cluster_0/N132 ),
	.YC(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [8]),
	.C(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [7]),
	.B(\dp_dut/dp_cluster_0/N100 ),
	.A(\dp_dut/dp_cluster_0/N84 ));
   FAX1 \dp_dut/dp_cluster_0/add_1_root_add_103_5/U1_8  (.YS(\dp_dut/dp_cluster_0/N133 ),
	.YC(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [9]),
	.C(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [8]),
	.B(\dp_dut/dp_cluster_0/N101 ),
	.A(\dp_dut/dp_cluster_0/N85 ));
   FAX1 \dp_dut/dp_cluster_0/add_1_root_add_103_5/U1_9  (.YS(\dp_dut/dp_cluster_0/N134 ),
	.YC(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [10]),
	.C(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [9]),
	.B(\dp_dut/dp_cluster_0/N102 ),
	.A(\dp_dut/dp_cluster_0/N86 ));
   FAX1 \dp_dut/dp_cluster_0/add_1_root_add_103_5/U1_10  (.YS(\dp_dut/dp_cluster_0/N135 ),
	.YC(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [11]),
	.C(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [10]),
	.B(\dp_dut/dp_cluster_0/N103 ),
	.A(\dp_dut/dp_cluster_0/N87 ));
   FAX1 \dp_dut/dp_cluster_0/add_1_root_add_103_5/U1_11  (.YS(\dp_dut/dp_cluster_0/N136 ),
	.YC(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [12]),
	.C(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [11]),
	.B(\dp_dut/dp_cluster_0/N104 ),
	.A(\dp_dut/dp_cluster_0/N88 ));
   FAX1 \dp_dut/dp_cluster_0/add_1_root_add_103_5/U1_12  (.YS(\dp_dut/dp_cluster_0/N137 ),
	.YC(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [13]),
	.C(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [12]),
	.B(\dp_dut/dp_cluster_0/N105 ),
	.A(\dp_dut/dp_cluster_0/N89 ));
   FAX1 \dp_dut/dp_cluster_0/add_1_root_add_103_5/U1_13  (.YS(\dp_dut/dp_cluster_0/N138 ),
	.YC(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [14]),
	.C(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [13]),
	.B(n2),
	.A(\dp_dut/dp_cluster_0/N90 ));
   FAX1 \dp_dut/dp_cluster_0/add_2_root_add_103_5/U1_3  (.YS(\dp_dut/dp_cluster_0/N112 ),
	.YC(\dp_dut/dp_cluster_0/add_2_root_add_103_5/carry [4]),
	.C(n11),
	.B(in_inserted_025[2]),
	.A(in_inserted_05[1]));
   FAX1 \dp_dut/dp_cluster_0/add_2_root_add_103_5/U1_4  (.YS(\dp_dut/dp_cluster_0/N113 ),
	.YC(\dp_dut/dp_cluster_0/add_2_root_add_103_5/carry [5]),
	.C(\dp_dut/dp_cluster_0/add_2_root_add_103_5/carry [4]),
	.B(in_inserted_025[3]),
	.A(in_inserted_05[2]));
   FAX1 \dp_dut/dp_cluster_0/add_2_root_add_103_5/U1_5  (.YS(\dp_dut/dp_cluster_0/N114 ),
	.YC(\dp_dut/dp_cluster_0/add_2_root_add_103_5/carry [6]),
	.C(\dp_dut/dp_cluster_0/add_2_root_add_103_5/carry [5]),
	.B(in_inserted_025[4]),
	.A(in_inserted_05[3]));
   FAX1 \dp_dut/dp_cluster_0/add_2_root_add_103_5/U1_6  (.YS(\dp_dut/dp_cluster_0/N115 ),
	.YC(\dp_dut/dp_cluster_0/add_2_root_add_103_5/carry [7]),
	.C(\dp_dut/dp_cluster_0/add_2_root_add_103_5/carry [6]),
	.B(in_inserted_025[5]),
	.A(in_inserted_05[4]));
   FAX1 \dp_dut/dp_cluster_0/add_2_root_add_103_5/U1_7  (.YS(\dp_dut/dp_cluster_0/N116 ),
	.YC(\dp_dut/dp_cluster_0/add_2_root_add_103_5/carry [8]),
	.C(\dp_dut/dp_cluster_0/add_2_root_add_103_5/carry [7]),
	.B(in_inserted_025[6]),
	.A(in_inserted_05[5]));
   FAX1 \dp_dut/dp_cluster_0/add_2_root_add_103_5/U1_8  (.YS(\dp_dut/dp_cluster_0/N117 ),
	.YC(\dp_dut/dp_cluster_0/add_2_root_add_103_5/carry [9]),
	.C(\dp_dut/dp_cluster_0/add_2_root_add_103_5/carry [8]),
	.B(in_inserted_025[7]),
	.A(in_inserted_05[6]));
   FAX1 \dp_dut/dp_cluster_0/add_0_root_add_103_5/U1_2  (.YS(\dp_dut/N143 ),
	.YC(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [3]),
	.C(n9),
	.B(\dp_dut/inserted_money [2]),
	.A(\dp_dut/dp_cluster_0/N111 ));
   FAX1 \dp_dut/dp_cluster_0/add_0_root_add_103_5/U1_3  (.YS(\dp_dut/N144 ),
	.YC(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [4]),
	.C(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [3]),
	.B(\dp_dut/dp_cluster_0/N128 ),
	.A(\dp_dut/dp_cluster_0/N112 ));
   FAX1 \dp_dut/dp_cluster_0/add_0_root_add_103_5/U1_4  (.YS(\dp_dut/N145 ),
	.YC(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [5]),
	.C(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [4]),
	.B(\dp_dut/dp_cluster_0/N129 ),
	.A(\dp_dut/dp_cluster_0/N113 ));
   FAX1 \dp_dut/dp_cluster_0/add_0_root_add_103_5/U1_5  (.YS(\dp_dut/N146 ),
	.YC(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [6]),
	.C(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [5]),
	.B(\dp_dut/dp_cluster_0/N130 ),
	.A(\dp_dut/dp_cluster_0/N114 ));
   FAX1 \dp_dut/dp_cluster_0/add_0_root_add_103_5/U1_6  (.YS(\dp_dut/N147 ),
	.YC(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [7]),
	.C(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [6]),
	.B(\dp_dut/dp_cluster_0/N131 ),
	.A(\dp_dut/dp_cluster_0/N115 ));
   FAX1 \dp_dut/dp_cluster_0/add_0_root_add_103_5/U1_7  (.YS(\dp_dut/N148 ),
	.YC(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [8]),
	.C(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [7]),
	.B(\dp_dut/dp_cluster_0/N132 ),
	.A(\dp_dut/dp_cluster_0/N116 ));
   FAX1 \dp_dut/dp_cluster_0/add_0_root_add_103_5/U1_8  (.YS(\dp_dut/N149 ),
	.YC(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [9]),
	.C(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [8]),
	.B(\dp_dut/dp_cluster_0/N133 ),
	.A(\dp_dut/dp_cluster_0/N117 ));
   FAX1 \dp_dut/dp_cluster_0/add_0_root_add_103_5/U1_9  (.YS(\dp_dut/N150 ),
	.YC(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [10]),
	.C(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [9]),
	.B(\dp_dut/dp_cluster_0/N134 ),
	.A(\dp_dut/dp_cluster_0/N118 ));
   FAX1 \dp_dut/dp_cluster_0/add_0_root_add_103_5/U1_10  (.YS(\dp_dut/N151 ),
	.YC(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [11]),
	.C(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [10]),
	.B(\dp_dut/dp_cluster_0/N135 ),
	.A(n5));
   FAX1 \dp_dut/dp_cluster_1/add_2_root_add_65_3/U1_3  (.YS(\dp_dut/dp_cluster_1/N23 ),
	.YC(\dp_dut/dp_cluster_1/N24 ),
	.C(n7),
	.B(out_csel_b),
	.A(out_csel_a));
   FAX1 \dp_dut/dp_cluster_1/add_0_root_add_65_3/U1_3  (.YS(\dp_dut/N34 ),
	.YC(\dp_dut/dp_cluster_1/add_0_root_add_65_3/carry[4] ),
	.C(n14),
	.B(\dp_dut/dp_cluster_1/N28 ),
	.A(\dp_dut/dp_cluster_1/N23 ));
   FAX1 \dp_dut/dp_cluster_1/add_0_root_add_65_3/U1_4  (.YS(\dp_dut/N35 ),
	.YC(\dp_dut/N36 ),
	.C(\dp_dut/dp_cluster_1/add_0_root_add_65_3/carry[4] ),
	.B(n6),
	.A(\dp_dut/dp_cluster_1/N24 ));
   AND2X2 U1 (.Y(n1),
	.B(n35),
	.A(n59));
   AND2X2 U2 (.Y(n2),
	.B(n34),
	.A(n18));
   AND2X2 U3 (.Y(n3),
	.B(\dp_dut/inserted_money [13]),
	.A(n16));
   NAND2X1 U4 (.Y(n4),
	.B(n45),
	.A(\dp_dut/N34 ));
   AND2X2 U5 (.Y(n5),
	.B(in_inserted_05[7]),
	.A(\dp_dut/dp_cluster_0/add_2_root_add_103_5/carry [9]));
   AND2X2 U6 (.Y(n6),
	.B(out_csel_c),
	.A(out_csel_d));
   AND2X2 U7 (.Y(n7),
	.B(out_csel_a),
	.A(out_csel_b));
   AND2X2 U8 (.Y(n8),
	.B(\dp_dut/inserted_money [3]),
	.A(n27));
   AND2X2 U9 (.Y(n9),
	.B(in_inserted_025[0]),
	.A(\dp_dut/inserted_money [1]));
   AND2X2 U10 (.Y(n10),
	.B(out_csel_a),
	.A(out_csel_c));
   AND2X2 U11 (.Y(n11),
	.B(in_inserted_05[0]),
	.A(in_inserted_025[1]));
   AND2X2 U12 (.Y(n12),
	.B(\dp_dut/dp_cluster_0/N80 ),
	.A(in_inserted_1[0]));
   AND2X2 U13 (.Y(n13),
	.B(n27),
	.A(in_inserted_1[2]));
   AND2X2 U14 (.Y(n14),
	.B(\dp_dut/dp_cluster_1/N22 ),
	.A(n10));
   AND2X2 U15 (.Y(n15),
	.B(\dp_dut/inserted_money [11]),
	.A(\dp_dut/dp_cluster_0/add_4_root_add_103_5/carry [11]));
   AND2X2 U16 (.Y(n16),
	.B(\dp_dut/inserted_money [12]),
	.A(n15));
   AND2X2 U17 (.Y(n17),
	.B(\dp_dut/dp_cluster_0/N136 ),
	.A(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [11]));
   AND2X2 U18 (.Y(n18),
	.B(n33),
	.A(\dp_dut/dp_cluster_0/add_3_root_add_103_5/carry [11]));
   AND2X2 U19 (.Y(n19),
	.B(\dp_dut/dp_cluster_0/N137 ),
	.A(n17));
   AND2X2 U20 (.Y(n20),
	.B(\dp_dut/dp_cluster_0/N138 ),
	.A(n19));
   AND2X2 U21 (.Y(n21),
	.B(\dp_dut/inserted_money [14]),
	.A(n3));
   AND2X2 U22 (.Y(n22),
	.B(\dp_dut/dp_cluster_0/N91 ),
	.A(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [14]));
   AND2X2 U23 (.Y(n23),
	.B(\dp_dut/dp_cluster_0/N139 ),
	.A(n20));
   BUFX2 U24 (.Y(n37),
	.A(\dp_dut/n126 ));
   INVX2 U25 (.Y(n49),
	.A(n24));
   INVX2 U26 (.Y(n48),
	.A(\dp_dut/n205 ));
   INVX2 U27 (.Y(n47),
	.A(\dp_dut/n205 ));
   INVX2 U28 (.Y(n35),
	.A(n25));
   BUFX2 U29 (.Y(n52),
	.A(n50));
   BUFX2 U30 (.Y(n53),
	.A(n50));
   BUFX2 U31 (.Y(n54),
	.A(n50));
   BUFX2 U32 (.Y(n55),
	.A(n51));
   BUFX2 U33 (.Y(n56),
	.A(n51));
   OR2X1 U34 (.Y(n24),
	.B(\dp_dut/n205 ),
	.A(\dp_dut/n204 ));
   AND2X2 U35 (.Y(n25),
	.B(\dp_dut/n207 ),
	.A(n37));
   BUFX2 U36 (.Y(n57),
	.A(n51));
   INVX2 U37 (.Y(n38),
	.A(n26));
   OR2X1 U38 (.Y(n26),
	.B(in_restart),
	.A(\dp_dut/n151 ));
   BUFX2 U39 (.Y(n28),
	.A(in_inserted_5[1]));
   BUFX2 U40 (.Y(n29),
	.A(in_inserted_5[2]));
   BUFX2 U41 (.Y(n30),
	.A(in_inserted_5[3]));
   BUFX2 U42 (.Y(n31),
	.A(in_inserted_5[4]));
   BUFX2 U43 (.Y(n32),
	.A(in_inserted_5[5]));
   INVX2 U44 (.Y(n36),
	.A(\dp_dut/n207 ));
   BUFX2 U45 (.Y(n33),
	.A(in_inserted_5[6]));
   BUFX2 U46 (.Y(n34),
	.A(in_inserted_5[7]));
   BUFX2 U47 (.Y(n27),
	.A(in_inserted_5[0]));
   BUFX2 U48 (.Y(n50),
	.A(in_clka));
   BUFX2 U49 (.Y(n51),
	.A(in_clka));
   OR2X1 U50 (.Y(\dp_dut/r374/carry [11]),
	.B(\dp_dut/r374/carry [10]),
	.A(\dp_dut/inserted_money [10]));
   XNOR2X1 U51 (.Y(\dp_dut/N48 ),
	.B(\dp_dut/inserted_money [10]),
	.A(\dp_dut/r374/carry [10]));
   OR2X1 U52 (.Y(\dp_dut/r374/carry [12]),
	.B(\dp_dut/r374/carry [11]),
	.A(\dp_dut/inserted_money [11]));
   XNOR2X1 U53 (.Y(\dp_dut/N49 ),
	.B(\dp_dut/inserted_money [11]),
	.A(\dp_dut/r374/carry [11]));
   OR2X1 U54 (.Y(\dp_dut/r374/carry [13]),
	.B(\dp_dut/r374/carry [12]),
	.A(\dp_dut/inserted_money [12]));
   XNOR2X1 U55 (.Y(\dp_dut/N50 ),
	.B(\dp_dut/inserted_money [12]),
	.A(\dp_dut/r374/carry [12]));
   OR2X1 U56 (.Y(\dp_dut/r374/carry [14]),
	.B(\dp_dut/r374/carry [13]),
	.A(\dp_dut/inserted_money [13]));
   XNOR2X1 U57 (.Y(\dp_dut/N51 ),
	.B(\dp_dut/inserted_money [13]),
	.A(\dp_dut/r374/carry [13]));
   OR2X1 U58 (.Y(\dp_dut/r374/carry [15]),
	.B(\dp_dut/r374/carry [14]),
	.A(\dp_dut/inserted_money [14]));
   XNOR2X1 U59 (.Y(\dp_dut/N52 ),
	.B(\dp_dut/inserted_money [14]),
	.A(\dp_dut/r374/carry [14]));
   XNOR2X1 U60 (.Y(\dp_dut/N53 ),
	.B(\dp_dut/r374/carry [15]),
	.A(\dp_dut/inserted_money [15]));
   OR2X1 U61 (.Y(\dp_dut/r374/carry [8]),
	.B(\dp_dut/r374/carry [7]),
	.A(\dp_dut/inserted_money [7]));
   XNOR2X1 U62 (.Y(\dp_dut/N45 ),
	.B(\dp_dut/inserted_money [7]),
	.A(\dp_dut/r374/carry [7]));
   OR2X1 U63 (.Y(\dp_dut/r374/carry [9]),
	.B(\dp_dut/r374/carry [8]),
	.A(\dp_dut/inserted_money [8]));
   XNOR2X1 U64 (.Y(\dp_dut/N46 ),
	.B(\dp_dut/inserted_money [8]),
	.A(\dp_dut/r374/carry [8]));
   OR2X1 U65 (.Y(\dp_dut/r374/carry [10]),
	.B(\dp_dut/r374/carry [9]),
	.A(\dp_dut/inserted_money [9]));
   XNOR2X1 U66 (.Y(\dp_dut/N47 ),
	.B(\dp_dut/inserted_money [9]),
	.A(\dp_dut/r374/carry [9]));
   OR2X1 U67 (.Y(\dp_dut/sub_125/carry [2]),
	.B(\dp_dut/sub_125/carry [1]),
	.A(\dp_dut/item_a_num [1]));
   XNOR2X1 U68 (.Y(\dp_dut/N176 ),
	.B(\dp_dut/item_a_num [1]),
	.A(\dp_dut/sub_125/carry [1]));
   OR2X1 U69 (.Y(\dp_dut/sub_125/carry [3]),
	.B(\dp_dut/sub_125/carry [2]),
	.A(\dp_dut/item_a_num [2]));
   XNOR2X1 U70 (.Y(\dp_dut/N177 ),
	.B(\dp_dut/item_a_num [2]),
	.A(\dp_dut/sub_125/carry [2]));
   OR2X1 U71 (.Y(\dp_dut/sub_125/carry [4]),
	.B(\dp_dut/sub_125/carry [3]),
	.A(\dp_dut/item_a_num [3]));
   XNOR2X1 U72 (.Y(\dp_dut/N178 ),
	.B(\dp_dut/item_a_num [3]),
	.A(\dp_dut/sub_125/carry [3]));
   OR2X1 U73 (.Y(\dp_dut/sub_125/carry [5]),
	.B(\dp_dut/sub_125/carry [4]),
	.A(\dp_dut/item_a_num [4]));
   XNOR2X1 U74 (.Y(\dp_dut/N179 ),
	.B(\dp_dut/item_a_num [4]),
	.A(\dp_dut/sub_125/carry [4]));
   OR2X1 U75 (.Y(\dp_dut/sub_125/carry [6]),
	.B(\dp_dut/sub_125/carry [5]),
	.A(\dp_dut/item_a_num [5]));
   XNOR2X1 U76 (.Y(\dp_dut/N180 ),
	.B(\dp_dut/item_a_num [5]),
	.A(\dp_dut/sub_125/carry [5]));
   OR2X1 U77 (.Y(\dp_dut/sub_125/carry [7]),
	.B(\dp_dut/sub_125/carry [6]),
	.A(\dp_dut/item_a_num [6]));
   XNOR2X1 U78 (.Y(\dp_dut/N181 ),
	.B(\dp_dut/item_a_num [6]),
	.A(\dp_dut/sub_125/carry [6]));
   XNOR2X1 U79 (.Y(\dp_dut/N182 ),
	.B(\dp_dut/sub_125/carry [7]),
	.A(\dp_dut/item_a_num [7]));
   OR2X1 U80 (.Y(\dp_dut/sub_125/carry [1]),
	.B(n137),
	.A(\dp_dut/item_a_num [0]));
   XNOR2X1 U81 (.Y(\dp_dut/N175 ),
	.B(\dp_dut/item_a_num [0]),
	.A(n137));
   OR2X1 U82 (.Y(\dp_dut/sub_126/carry [2]),
	.B(\dp_dut/sub_126/carry [1]),
	.A(\dp_dut/item_b_num [1]));
   XNOR2X1 U83 (.Y(\dp_dut/N184 ),
	.B(\dp_dut/item_b_num [1]),
	.A(\dp_dut/sub_126/carry [1]));
   OR2X1 U84 (.Y(\dp_dut/sub_126/carry [3]),
	.B(\dp_dut/sub_126/carry [2]),
	.A(\dp_dut/item_b_num [2]));
   XNOR2X1 U85 (.Y(\dp_dut/N185 ),
	.B(\dp_dut/item_b_num [2]),
	.A(\dp_dut/sub_126/carry [2]));
   OR2X1 U86 (.Y(\dp_dut/sub_126/carry [4]),
	.B(\dp_dut/sub_126/carry [3]),
	.A(\dp_dut/item_b_num [3]));
   XNOR2X1 U87 (.Y(\dp_dut/N186 ),
	.B(\dp_dut/item_b_num [3]),
	.A(\dp_dut/sub_126/carry [3]));
   OR2X1 U88 (.Y(\dp_dut/sub_126/carry [5]),
	.B(\dp_dut/sub_126/carry [4]),
	.A(\dp_dut/item_b_num [4]));
   XNOR2X1 U89 (.Y(\dp_dut/N187 ),
	.B(\dp_dut/item_b_num [4]),
	.A(\dp_dut/sub_126/carry [4]));
   OR2X1 U90 (.Y(\dp_dut/sub_126/carry [6]),
	.B(\dp_dut/sub_126/carry [5]),
	.A(\dp_dut/item_b_num [5]));
   XNOR2X1 U91 (.Y(\dp_dut/N188 ),
	.B(\dp_dut/item_b_num [5]),
	.A(\dp_dut/sub_126/carry [5]));
   OR2X1 U92 (.Y(\dp_dut/sub_126/carry [7]),
	.B(\dp_dut/sub_126/carry [6]),
	.A(\dp_dut/item_b_num [6]));
   XNOR2X1 U93 (.Y(\dp_dut/N189 ),
	.B(\dp_dut/item_b_num [6]),
	.A(\dp_dut/sub_126/carry [6]));
   XNOR2X1 U94 (.Y(\dp_dut/N190 ),
	.B(\dp_dut/sub_126/carry [7]),
	.A(\dp_dut/item_b_num [7]));
   OR2X1 U95 (.Y(\dp_dut/sub_126/carry [1]),
	.B(n110),
	.A(\dp_dut/item_b_num [0]));
   XNOR2X1 U96 (.Y(\dp_dut/N183 ),
	.B(\dp_dut/item_b_num [0]),
	.A(n110));
   OR2X1 U97 (.Y(\dp_dut/sub_127/carry [2]),
	.B(\dp_dut/sub_127/carry [1]),
	.A(\dp_dut/item_c_num [1]));
   XNOR2X1 U98 (.Y(\dp_dut/N192 ),
	.B(\dp_dut/item_c_num [1]),
	.A(\dp_dut/sub_127/carry [1]));
   OR2X1 U99 (.Y(\dp_dut/sub_127/carry [3]),
	.B(\dp_dut/sub_127/carry [2]),
	.A(\dp_dut/item_c_num [2]));
   XNOR2X1 U100 (.Y(\dp_dut/N193 ),
	.B(\dp_dut/item_c_num [2]),
	.A(\dp_dut/sub_127/carry [2]));
   OR2X1 U101 (.Y(\dp_dut/sub_127/carry [4]),
	.B(\dp_dut/sub_127/carry [3]),
	.A(\dp_dut/item_c_num [3]));
   XNOR2X1 U102 (.Y(\dp_dut/N194 ),
	.B(\dp_dut/item_c_num [3]),
	.A(\dp_dut/sub_127/carry [3]));
   OR2X1 U103 (.Y(\dp_dut/sub_127/carry [5]),
	.B(\dp_dut/sub_127/carry [4]),
	.A(\dp_dut/item_c_num [4]));
   XNOR2X1 U104 (.Y(\dp_dut/N195 ),
	.B(\dp_dut/item_c_num [4]),
	.A(\dp_dut/sub_127/carry [4]));
   OR2X1 U105 (.Y(\dp_dut/sub_127/carry [6]),
	.B(\dp_dut/sub_127/carry [5]),
	.A(\dp_dut/item_c_num [5]));
   XNOR2X1 U106 (.Y(\dp_dut/N196 ),
	.B(\dp_dut/item_c_num [5]),
	.A(\dp_dut/sub_127/carry [5]));
   OR2X1 U107 (.Y(\dp_dut/sub_127/carry [7]),
	.B(\dp_dut/sub_127/carry [6]),
	.A(\dp_dut/item_c_num [6]));
   XNOR2X1 U108 (.Y(\dp_dut/N197 ),
	.B(\dp_dut/item_c_num [6]),
	.A(\dp_dut/sub_127/carry [6]));
   XNOR2X1 U109 (.Y(\dp_dut/N198 ),
	.B(\dp_dut/sub_127/carry [7]),
	.A(\dp_dut/item_c_num [7]));
   OR2X1 U110 (.Y(\dp_dut/sub_127/carry [1]),
	.B(n101),
	.A(\dp_dut/item_c_num [0]));
   XNOR2X1 U111 (.Y(\dp_dut/N191 ),
	.B(\dp_dut/item_c_num [0]),
	.A(n101));
   OR2X1 U112 (.Y(\dp_dut/sub_128/carry [2]),
	.B(\dp_dut/sub_128/carry [1]),
	.A(\dp_dut/item_d_num [1]));
   XNOR2X1 U113 (.Y(\dp_dut/N200 ),
	.B(\dp_dut/item_d_num [1]),
	.A(\dp_dut/sub_128/carry [1]));
   OR2X1 U114 (.Y(\dp_dut/sub_128/carry [3]),
	.B(\dp_dut/sub_128/carry [2]),
	.A(\dp_dut/item_d_num [2]));
   XNOR2X1 U115 (.Y(\dp_dut/N201 ),
	.B(\dp_dut/item_d_num [2]),
	.A(\dp_dut/sub_128/carry [2]));
   OR2X1 U116 (.Y(\dp_dut/sub_128/carry [4]),
	.B(\dp_dut/sub_128/carry [3]),
	.A(\dp_dut/item_d_num [3]));
   XNOR2X1 U117 (.Y(\dp_dut/N202 ),
	.B(\dp_dut/item_d_num [3]),
	.A(\dp_dut/sub_128/carry [3]));
   OR2X1 U118 (.Y(\dp_dut/sub_128/carry [5]),
	.B(\dp_dut/sub_128/carry [4]),
	.A(\dp_dut/item_d_num [4]));
   XNOR2X1 U119 (.Y(\dp_dut/N203 ),
	.B(\dp_dut/item_d_num [4]),
	.A(\dp_dut/sub_128/carry [4]));
   OR2X1 U120 (.Y(\dp_dut/sub_128/carry [6]),
	.B(\dp_dut/sub_128/carry [5]),
	.A(\dp_dut/item_d_num [5]));
   XNOR2X1 U121 (.Y(\dp_dut/N204 ),
	.B(\dp_dut/item_d_num [5]),
	.A(\dp_dut/sub_128/carry [5]));
   OR2X1 U122 (.Y(\dp_dut/sub_128/carry [7]),
	.B(\dp_dut/sub_128/carry [6]),
	.A(\dp_dut/item_d_num [6]));
   XNOR2X1 U123 (.Y(\dp_dut/N205 ),
	.B(\dp_dut/item_d_num [6]),
	.A(\dp_dut/sub_128/carry [6]));
   XNOR2X1 U124 (.Y(\dp_dut/N206 ),
	.B(\dp_dut/sub_128/carry [7]),
	.A(\dp_dut/item_d_num [7]));
   OR2X1 U125 (.Y(\dp_dut/sub_128/carry [1]),
	.B(n92),
	.A(\dp_dut/item_d_num [0]));
   XNOR2X1 U126 (.Y(\dp_dut/N199 ),
	.B(\dp_dut/item_d_num [0]),
	.A(n92));
   OR2X1 U127 (.Y(\dp_dut/r374/carry [7]),
	.B(\dp_dut/r374/carry [6]),
	.A(\dp_dut/inserted_money [6]));
   XNOR2X1 U128 (.Y(\dp_dut/N44 ),
	.B(\dp_dut/inserted_money [6]),
	.A(\dp_dut/r374/carry [6]));
   OR2X1 U129 (.Y(\dp_dut/r374/carry [2]),
	.B(n76),
	.A(\dp_dut/inserted_money [1]));
   XNOR2X1 U130 (.Y(\dp_dut/N39 ),
	.B(\dp_dut/inserted_money [1]),
	.A(n76));
   XOR2X1 U131 (.Y(\dp_dut/dp_cluster_0/N104 ),
	.B(n33),
	.A(\dp_dut/dp_cluster_0/add_3_root_add_103_5/carry [11]));
   XOR2X1 U132 (.Y(\dp_dut/dp_cluster_0/N105 ),
	.B(n34),
	.A(n18));
   XOR2X1 U133 (.Y(\dp_dut/dp_cluster_0/N88 ),
	.B(\dp_dut/inserted_money [11]),
	.A(\dp_dut/dp_cluster_0/add_4_root_add_103_5/carry [11]));
   XOR2X1 U134 (.Y(\dp_dut/dp_cluster_0/N89 ),
	.B(\dp_dut/inserted_money [12]),
	.A(n15));
   XOR2X1 U135 (.Y(\dp_dut/dp_cluster_0/N90 ),
	.B(\dp_dut/inserted_money [13]),
	.A(n16));
   XOR2X1 U136 (.Y(\dp_dut/dp_cluster_0/N91 ),
	.B(\dp_dut/inserted_money [14]),
	.A(n3));
   XOR2X1 U137 (.Y(\dp_dut/dp_cluster_0/N92 ),
	.B(n21),
	.A(\dp_dut/inserted_money [15]));
   XOR2X1 U138 (.Y(\dp_dut/dp_cluster_0/N139 ),
	.B(\dp_dut/dp_cluster_0/N91 ),
	.A(\dp_dut/dp_cluster_0/add_1_root_add_103_5/carry [14]));
   XOR2X1 U139 (.Y(\dp_dut/dp_cluster_0/N140 ),
	.B(n22),
	.A(\dp_dut/dp_cluster_0/N92 ));
   XOR2X1 U140 (.Y(\dp_dut/dp_cluster_0/N118 ),
	.B(in_inserted_05[7]),
	.A(\dp_dut/dp_cluster_0/add_2_root_add_103_5/carry [9]));
   XOR2X1 U141 (.Y(\dp_dut/N142 ),
	.B(in_inserted_025[0]),
	.A(\dp_dut/inserted_money [1]));
   XOR2X1 U142 (.Y(\dp_dut/N152 ),
	.B(\dp_dut/dp_cluster_0/N136 ),
	.A(\dp_dut/dp_cluster_0/add_0_root_add_103_5/carry [11]));
   XOR2X1 U143 (.Y(\dp_dut/N153 ),
	.B(\dp_dut/dp_cluster_0/N137 ),
	.A(n17));
   XOR2X1 U144 (.Y(\dp_dut/N154 ),
	.B(\dp_dut/dp_cluster_0/N138 ),
	.A(n19));
   XOR2X1 U145 (.Y(\dp_dut/N155 ),
	.B(\dp_dut/dp_cluster_0/N139 ),
	.A(n20));
   XOR2X1 U146 (.Y(\dp_dut/N156 ),
	.B(n23),
	.A(\dp_dut/dp_cluster_0/N140 ));
   XOR2X1 U147 (.Y(\dp_dut/dp_cluster_1/N28 ),
	.B(out_csel_c),
	.A(out_csel_d));
   XOR2X1 U148 (.Y(\dp_dut/N32 ),
	.B(out_csel_a),
	.A(out_csel_c));
   XOR2X1 U149 (.Y(\dp_dut/dp_cluster_1/N22 ),
	.B(out_csel_a),
	.A(out_csel_b));
   XOR2X1 U150 (.Y(\dp_dut/dp_cluster_0/N80 ),
	.B(\dp_dut/inserted_money [3]),
	.A(n27));
   XOR2X1 U151 (.Y(\dp_dut/dp_cluster_0/N128 ),
	.B(\dp_dut/dp_cluster_0/N80 ),
	.A(in_inserted_1[0]));
   XOR2X1 U152 (.Y(\dp_dut/N33 ),
	.B(\dp_dut/dp_cluster_1/N22 ),
	.A(n10));
   XOR2X1 U153 (.Y(\dp_dut/dp_cluster_0/N111 ),
	.B(in_inserted_05[0]),
	.A(in_inserted_025[1]));
   XOR2X1 U154 (.Y(\dp_dut/dp_cluster_0/N98 ),
	.B(n27),
	.A(in_inserted_1[2]));
   NAND2X1 U155 (.Y(n39),
	.B(n81),
	.A(cmd[1]));
   NAND2X1 U156 (.Y(n40),
	.B(n81),
	.A(cmd[1]));
   BUFX2 U157 (.Y(n41),
	.A(n39));
   BUFX2 U158 (.Y(n42),
	.A(n39));
   BUFX2 U159 (.Y(n43),
	.A(n40));
   BUFX2 U160 (.Y(n44),
	.A(n40));
   BUFX2 U161 (.Y(n45),
	.A(\dp_dut/n113 ));
   BUFX2 U162 (.Y(n46),
	.A(\dp_dut/n113 ));
   AND2X2 U163 (.Y(n156),
	.B(n154),
	.A(n155));
   INVX2 U164 (.Y(n58),
	.A(n37));
   INVX2 U165 (.Y(n59),
	.A(\dp_dut/n204 ));
   INVX2 U166 (.Y(n60),
	.A(in_restart));
   INVX2 U167 (.Y(n61),
	.A(in_sel_a));
   INVX2 U168 (.Y(n62),
	.A(in_sel_b));
   INVX2 U169 (.Y(n63),
	.A(in_sel_c));
   INVX2 U170 (.Y(n64),
	.A(in_sel_d));
   INVX2 U171 (.Y(n65),
	.A(n143));
   INVX2 U172 (.Y(out_change[10]),
	.A(\dp_dut/n123 ));
   INVX2 U173 (.Y(out_change[9]),
	.A(\dp_dut/n114 ));
   INVX2 U174 (.Y(out_change[8]),
	.A(\dp_dut/n115 ));
   INVX2 U175 (.Y(out_change[7]),
	.A(\dp_dut/n116 ));
   INVX2 U176 (.Y(out_change[6]),
	.A(\dp_dut/n117 ));
   INVX2 U177 (.Y(out_change[5]),
	.A(\dp_dut/n118 ));
   INVX2 U178 (.Y(out_change[4]),
	.A(\dp_dut/n119 ));
   INVX2 U179 (.Y(out_change[3]),
	.A(\dp_dut/n120 ));
   INVX2 U180 (.Y(out_change[2]),
	.A(\dp_dut/n121 ));
   INVX2 U181 (.Y(out_change[1]),
	.A(\dp_dut/n122 ));
   INVX2 U182 (.Y(n76),
	.A(\dp_dut/total_price [1]));
   INVX2 U183 (.Y(n77),
	.A(\dp_dut/total_price [2]));
   INVX2 U184 (.Y(n78),
	.A(n139));
   INVX2 U185 (.Y(n79),
	.A(\dp_dut/total_price [4]));
   INVX2 U186 (.Y(n80),
	.A(\dp_dut/total_price [5]));
   INVX2 U187 (.Y(n81),
	.A(cmd[0]));
   INVX2 U188 (.Y(n82),
	.A(\dp_dut/n151 ));
   INVX2 U189 (.Y(n83),
	.A(\main_FSM_dut/next_out_state[1] ));
   INVX2 U190 (.Y(n84),
	.A(out_state[0]));
   INVX2 U191 (.Y(n85),
	.A(\dp_dut/item_d_num [7]));
   INVX2 U192 (.Y(n86),
	.A(\dp_dut/item_d_num [5]));
   INVX2 U193 (.Y(n87),
	.A(\dp_dut/item_d_num [4]));
   INVX2 U194 (.Y(n88),
	.A(\dp_dut/item_d_num [3]));
   INVX2 U195 (.Y(n89),
	.A(\dp_dut/item_d_num [2]));
   INVX2 U196 (.Y(n90),
	.A(\dp_dut/item_d_num [1]));
   INVX2 U197 (.Y(n91),
	.A(\dp_dut/item_d_num [0]));
   INVX2 U198 (.Y(n92),
	.A(out_csel_d));
   INVX2 U199 (.Y(n93),
	.A(\dp_dut/item_d_num [6]));
   INVX2 U200 (.Y(n94),
	.A(\dp_dut/item_c_num [7]));
   INVX2 U201 (.Y(n95),
	.A(\dp_dut/item_c_num [5]));
   INVX2 U202 (.Y(n96),
	.A(\dp_dut/item_c_num [4]));
   INVX2 U203 (.Y(n97),
	.A(\dp_dut/item_c_num [3]));
   INVX2 U204 (.Y(n98),
	.A(\dp_dut/item_c_num [2]));
   INVX2 U205 (.Y(n99),
	.A(\dp_dut/item_c_num [1]));
   INVX2 U206 (.Y(n100),
	.A(\dp_dut/item_c_num [0]));
   INVX2 U207 (.Y(n101),
	.A(out_csel_c));
   INVX2 U208 (.Y(n102),
	.A(\dp_dut/item_c_num [6]));
   INVX2 U209 (.Y(n103),
	.A(\dp_dut/item_b_num [7]));
   INVX2 U210 (.Y(n104),
	.A(\dp_dut/item_b_num [5]));
   INVX2 U211 (.Y(n105),
	.A(\dp_dut/item_b_num [4]));
   INVX2 U212 (.Y(n106),
	.A(\dp_dut/item_b_num [3]));
   INVX2 U213 (.Y(n107),
	.A(\dp_dut/item_b_num [2]));
   INVX2 U214 (.Y(n108),
	.A(\dp_dut/item_b_num [1]));
   INVX2 U215 (.Y(n109),
	.A(\dp_dut/item_b_num [0]));
   INVX2 U216 (.Y(n110),
	.A(out_csel_b));
   INVX2 U217 (.Y(n111),
	.A(\dp_dut/item_b_num [6]));
   INVX2 U218 (.Y(n112),
	.A(\dp_dut/item_a_num [7]));
   INVX2 U219 (.Y(n113),
	.A(\dp_dut/item_a_num [5]));
   INVX2 U220 (.Y(n114),
	.A(\dp_dut/item_a_num [4]));
   INVX2 U221 (.Y(n115),
	.A(\dp_dut/item_a_num [3]));
   INVX2 U222 (.Y(n116),
	.A(\dp_dut/item_a_num [2]));
   INVX2 U223 (.Y(n117),
	.A(\dp_dut/item_a_num [1]));
   INVX2 U224 (.Y(n118),
	.A(\dp_dut/item_a_num [0]));
   INVX2 U225 (.Y(n119),
	.A(\dp_dut/item_a_num [6]));
   INVX2 U226 (.Y(n120),
	.A(\dp_dut/N141 ));
   INVX2 U227 (.Y(n121),
	.A(\dp_dut/inserted_money [1]));
   INVX2 U228 (.Y(n122),
	.A(\dp_dut/inserted_money [2]));
   INVX2 U229 (.Y(n123),
	.A(\dp_dut/inserted_money [3]));
   INVX2 U230 (.Y(n124),
	.A(\dp_dut/inserted_money [4]));
   INVX2 U231 (.Y(n125),
	.A(\dp_dut/inserted_money [5]));
   INVX2 U232 (.Y(n126),
	.A(n146));
   INVX2 U233 (.Y(n127),
	.A(\dp_dut/inserted_money [6]));
   INVX2 U234 (.Y(n128),
	.A(\dp_dut/inserted_money [7]));
   INVX2 U235 (.Y(n129),
	.A(\dp_dut/inserted_money [8]));
   INVX2 U236 (.Y(n130),
	.A(\dp_dut/inserted_money [9]));
   INVX2 U237 (.Y(n131),
	.A(\dp_dut/inserted_money [10]));
   INVX2 U238 (.Y(n132),
	.A(\dp_dut/inserted_money [11]));
   INVX2 U239 (.Y(n133),
	.A(\dp_dut/inserted_money [12]));
   INVX2 U240 (.Y(n134),
	.A(\dp_dut/inserted_money [13]));
   INVX2 U241 (.Y(n135),
	.A(\dp_dut/inserted_money [14]));
   INVX2 U242 (.Y(n136),
	.A(\dp_dut/inserted_money [15]));
   INVX2 U243 (.Y(n137),
	.A(out_csel_a));
   OAI21X1 U244 (.Y(n143),
	.C(n120),
	.B(\dp_dut/total_price [1]),
	.A(n121));
   NAND2X1 U245 (.Y(n148),
	.B(n125),
	.A(\dp_dut/total_price [5]));
   NAND2X1 U246 (.Y(n146),
	.B(n141),
	.A(n127));
   NAND2X1 U247 (.Y(n140),
	.B(n4),
	.A(\dp_dut/inserted_money [3]));
   NAND3X1 U248 (.Y(n138),
	.C(\dp_dut/total_price [2]),
	.B(n122),
	.A(n140));
   OAI21X1 U249 (.Y(n139),
	.C(n138),
	.B(n4),
	.A(\dp_dut/inserted_money [3]));
   OAI21X1 U250 (.Y(n142),
	.C(n140),
	.B(n122),
	.A(\dp_dut/total_price [2]));
   NOR2X1 U251 (.Y(n141),
	.B(\dp_dut/inserted_money [7]),
	.A(\dp_dut/inserted_money [8]));
   AOI21X1 U252 (.Y(n152),
	.C(n146),
	.B(n142),
	.A(n78));
   AOI21X1 U253 (.Y(n145),
	.C(n65),
	.B(n121),
	.A(\dp_dut/total_price [1]));
   OR2X1 U254 (.Y(n147),
	.B(\dp_dut/total_price [5]),
	.A(n125));
   OAI21X1 U255 (.Y(n144),
	.C(n147),
	.B(n124),
	.A(\dp_dut/total_price [4]));
   AOI21X1 U256 (.Y(n151),
	.C(n144),
	.B(n78),
	.A(n145));
   NAND2X1 U257 (.Y(n149),
	.B(n124),
	.A(n147));
   OAI21X1 U258 (.Y(n150),
	.C(n148),
	.B(n149),
	.A(n79));
   AOI22X1 U259 (.Y(n153),
	.D(n150),
	.C(n126),
	.B(n151),
	.A(n152));
   NOR2X1 U260 (.Y(n158),
	.B(n153),
	.A(\dp_dut/inserted_money [10]));
   NOR2X1 U261 (.Y(n157),
	.B(\dp_dut/inserted_money [11]),
	.A(\dp_dut/inserted_money [12]));
   NOR2X1 U262 (.Y(n155),
	.B(\dp_dut/inserted_money [13]),
	.A(\dp_dut/inserted_money [14]));
   NOR2X1 U263 (.Y(n154),
	.B(\dp_dut/inserted_money [15]),
	.A(\dp_dut/inserted_money [9]));
   NAND3X1 U264 (.Y(\dp_dut/N158 ),
	.C(n156),
	.B(n157),
	.A(n158));
endmodule

