/*
###############################################################
#  Generated by:      Cadence Encounter 14.28-s033_1
#  OS:                Linux x86_64(Host ID agate.clear.rice.edu)
#  Generated on:      Sat Apr 29 20:27:37 2023
#  Design:            top_module
#  Command:           saveNetlist final.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : N-2017.09-SP2
// Date      : Sat Apr 29 20:26:36 2023
/////////////////////////////////////////////////////////////
module top_module (
	in_clka, 
	in_clkb, 
	in_restart, 
	in_inserted_5, 
	in_inserted_1, 
	in_inserted_05, 
	in_inserted_025, 
	in_sel_a, 
	in_sel_b, 
	in_sel_c, 
	in_sel_d, 
	in_next, 
	in_finish, 
	out_change, 
	out_stock_a, 
	out_stock_b, 
	out_stock_c, 
	out_stock_d, 
	out_csel_a, 
	out_csel_b, 
	out_csel_c, 
	out_csel_d, 
	out_change_1, 
	out_change_05, 
	out_change_025, 
	out_spit_a, 
	out_spit_b, 
	out_spit_c, 
	out_spit_d, 
	out_state, 
	out_sol_ok);
   input in_clka;
   input in_clkb;
   input in_restart;
   input in_inserted_5;
   input in_inserted_1;
   input in_inserted_05;
   input in_inserted_025;
   input in_sel_a;
   input in_sel_b;
   input in_sel_c;
   input in_sel_d;
   input in_next;
   input in_finish;
   output [15:0] out_change;
   output out_stock_a;
   output out_stock_b;
   output out_stock_c;
   output out_stock_d;
   output out_csel_a;
   output out_csel_b;
   output out_csel_c;
   output out_csel_d;
   output [7:0] out_change_1;
   output out_change_05;
   output out_change_025;
   output out_spit_a;
   output out_spit_b;
   output out_spit_c;
   output out_spit_d;
   output [1:0] out_state;
   output out_sol_ok;

   // Internal wires
   wire \main_FSM_dut/n5 ;
   wire \main_FSM_dut/n4 ;
   wire \main_FSM_dut/n3 ;
   wire \main_FSM_dut/N38 ;
   wire \main_FSM_dut/N28 ;
   wire \main_FSM_dut/N27 ;
   wire \main_FSM_dut/next_out_state[1] ;
   wire \dp_dut/n479 ;
   wire \dp_dut/n478 ;
   wire \dp_dut/n477 ;
   wire \dp_dut/n476 ;
   wire \dp_dut/n475 ;
   wire \dp_dut/n474 ;
   wire \dp_dut/n473 ;
   wire \dp_dut/n472 ;
   wire \dp_dut/n471 ;
   wire \dp_dut/n470 ;
   wire \dp_dut/n469 ;
   wire \dp_dut/n468 ;
   wire \dp_dut/n467 ;
   wire \dp_dut/n466 ;
   wire \dp_dut/n465 ;
   wire \dp_dut/n464 ;
   wire \dp_dut/n463 ;
   wire \dp_dut/n462 ;
   wire \dp_dut/n461 ;
   wire \dp_dut/n460 ;
   wire \dp_dut/n459 ;
   wire \dp_dut/n458 ;
   wire \dp_dut/n457 ;
   wire \dp_dut/n456 ;
   wire \dp_dut/n455 ;
   wire \dp_dut/n454 ;
   wire \dp_dut/n453 ;
   wire \dp_dut/n452 ;
   wire \dp_dut/n451 ;
   wire \dp_dut/n450 ;
   wire \dp_dut/n449 ;
   wire \dp_dut/n448 ;
   wire \dp_dut/n447 ;
   wire \dp_dut/n446 ;
   wire \dp_dut/n445 ;
   wire \dp_dut/n444 ;
   wire \dp_dut/n443 ;
   wire \dp_dut/n442 ;
   wire \dp_dut/n441 ;
   wire \dp_dut/n440 ;
   wire \dp_dut/n439 ;
   wire \dp_dut/n438 ;
   wire \dp_dut/n437 ;
   wire \dp_dut/n436 ;
   wire \dp_dut/n435 ;
   wire \dp_dut/n434 ;
   wire \dp_dut/n433 ;
   wire \dp_dut/n432 ;
   wire \dp_dut/n431 ;
   wire \dp_dut/n430 ;
   wire \dp_dut/n429 ;
   wire \dp_dut/n428 ;
   wire \dp_dut/n427 ;
   wire \dp_dut/n426 ;
   wire \dp_dut/n425 ;
   wire \dp_dut/n424 ;
   wire \dp_dut/n423 ;
   wire \dp_dut/n422 ;
   wire \dp_dut/n421 ;
   wire \dp_dut/n420 ;
   wire \dp_dut/n419 ;
   wire \dp_dut/n418 ;
   wire \dp_dut/n417 ;
   wire \dp_dut/n416 ;
   wire \dp_dut/n415 ;
   wire \dp_dut/n414 ;
   wire \dp_dut/n413 ;
   wire \dp_dut/n412 ;
   wire \dp_dut/n411 ;
   wire \dp_dut/n410 ;
   wire \dp_dut/n409 ;
   wire \dp_dut/n408 ;
   wire \dp_dut/n407 ;
   wire \dp_dut/n406 ;
   wire \dp_dut/n405 ;
   wire \dp_dut/n404 ;
   wire \dp_dut/n403 ;
   wire \dp_dut/n402 ;
   wire \dp_dut/n401 ;
   wire \dp_dut/n400 ;
   wire \dp_dut/n399 ;
   wire \dp_dut/n398 ;
   wire \dp_dut/n397 ;
   wire \dp_dut/n396 ;
   wire \dp_dut/n395 ;
   wire \dp_dut/n394 ;
   wire \dp_dut/n393 ;
   wire \dp_dut/n392 ;
   wire \dp_dut/n391 ;
   wire \dp_dut/n390 ;
   wire \dp_dut/n389 ;
   wire \dp_dut/n388 ;
   wire \dp_dut/n387 ;
   wire \dp_dut/n386 ;
   wire \dp_dut/n385 ;
   wire \dp_dut/n384 ;
   wire \dp_dut/n383 ;
   wire \dp_dut/n382 ;
   wire \dp_dut/n381 ;
   wire \dp_dut/n380 ;
   wire \dp_dut/n379 ;
   wire \dp_dut/n378 ;
   wire \dp_dut/n377 ;
   wire \dp_dut/n376 ;
   wire \dp_dut/n375 ;
   wire \dp_dut/n374 ;
   wire \dp_dut/n373 ;
   wire \dp_dut/n372 ;
   wire \dp_dut/n371 ;
   wire \dp_dut/n370 ;
   wire \dp_dut/n369 ;
   wire \dp_dut/n368 ;
   wire \dp_dut/n367 ;
   wire \dp_dut/n366 ;
   wire \dp_dut/n365 ;
   wire \dp_dut/n364 ;
   wire \dp_dut/n363 ;
   wire \dp_dut/n362 ;
   wire \dp_dut/n361 ;
   wire \dp_dut/n360 ;
   wire \dp_dut/n359 ;
   wire \dp_dut/n358 ;
   wire \dp_dut/n357 ;
   wire \dp_dut/n356 ;
   wire \dp_dut/n355 ;
   wire \dp_dut/n354 ;
   wire \dp_dut/n353 ;
   wire \dp_dut/n352 ;
   wire \dp_dut/n351 ;
   wire \dp_dut/n350 ;
   wire \dp_dut/n349 ;
   wire \dp_dut/n348 ;
   wire \dp_dut/n346 ;
   wire \dp_dut/n345 ;
   wire \dp_dut/n344 ;
   wire \dp_dut/n343 ;
   wire \dp_dut/n342 ;
   wire \dp_dut/n341 ;
   wire \dp_dut/n340 ;
   wire \dp_dut/n339 ;
   wire \dp_dut/n338 ;
   wire \dp_dut/n337 ;
   wire \dp_dut/n336 ;
   wire \dp_dut/n335 ;
   wire \dp_dut/n334 ;
   wire \dp_dut/n333 ;
   wire \dp_dut/n332 ;
   wire \dp_dut/n331 ;
   wire \dp_dut/n330 ;
   wire \dp_dut/n329 ;
   wire \dp_dut/n328 ;
   wire \dp_dut/n327 ;
   wire \dp_dut/n326 ;
   wire \dp_dut/n325 ;
   wire \dp_dut/n324 ;
   wire \dp_dut/n323 ;
   wire \dp_dut/n322 ;
   wire \dp_dut/n321 ;
   wire \dp_dut/n320 ;
   wire \dp_dut/n319 ;
   wire \dp_dut/n318 ;
   wire \dp_dut/n317 ;
   wire \dp_dut/n316 ;
   wire \dp_dut/n315 ;
   wire \dp_dut/n314 ;
   wire \dp_dut/n313 ;
   wire \dp_dut/n312 ;
   wire \dp_dut/n311 ;
   wire \dp_dut/n310 ;
   wire \dp_dut/n309 ;
   wire \dp_dut/n308 ;
   wire \dp_dut/n307 ;
   wire \dp_dut/n306 ;
   wire \dp_dut/n305 ;
   wire \dp_dut/n304 ;
   wire \dp_dut/n303 ;
   wire \dp_dut/n302 ;
   wire \dp_dut/n301 ;
   wire \dp_dut/n300 ;
   wire \dp_dut/n299 ;
   wire \dp_dut/n298 ;
   wire \dp_dut/n297 ;
   wire \dp_dut/n296 ;
   wire \dp_dut/n294 ;
   wire \dp_dut/n293 ;
   wire \dp_dut/n292 ;
   wire \dp_dut/n291 ;
   wire \dp_dut/n290 ;
   wire \dp_dut/n289 ;
   wire \dp_dut/n288 ;
   wire \dp_dut/n287 ;
   wire \dp_dut/n286 ;
   wire \dp_dut/n285 ;
   wire \dp_dut/n284 ;
   wire \dp_dut/n283 ;
   wire \dp_dut/n282 ;
   wire \dp_dut/n281 ;
   wire \dp_dut/n280 ;
   wire \dp_dut/n279 ;
   wire \dp_dut/n278 ;
   wire \dp_dut/n277 ;
   wire \dp_dut/n276 ;
   wire \dp_dut/n275 ;
   wire \dp_dut/n274 ;
   wire \dp_dut/n273 ;
   wire \dp_dut/n272 ;
   wire \dp_dut/n271 ;
   wire \dp_dut/n270 ;
   wire \dp_dut/n269 ;
   wire \dp_dut/n268 ;
   wire \dp_dut/n267 ;
   wire \dp_dut/n266 ;
   wire \dp_dut/n265 ;
   wire \dp_dut/n264 ;
   wire \dp_dut/n263 ;
   wire \dp_dut/n262 ;
   wire \dp_dut/n261 ;
   wire \dp_dut/n260 ;
   wire \dp_dut/n259 ;
   wire \dp_dut/n258 ;
   wire \dp_dut/n257 ;
   wire \dp_dut/n256 ;
   wire \dp_dut/n255 ;
   wire \dp_dut/n254 ;
   wire \dp_dut/n253 ;
   wire \dp_dut/n252 ;
   wire \dp_dut/n251 ;
   wire \dp_dut/n250 ;
   wire \dp_dut/n249 ;
   wire \dp_dut/n248 ;
   wire \dp_dut/n247 ;
   wire \dp_dut/n246 ;
   wire \dp_dut/n245 ;
   wire \dp_dut/n244 ;
   wire \dp_dut/n243 ;
   wire \dp_dut/n242 ;
   wire \dp_dut/n241 ;
   wire \dp_dut/n240 ;
   wire \dp_dut/n239 ;
   wire \dp_dut/n238 ;
   wire \dp_dut/n237 ;
   wire \dp_dut/n236 ;
   wire \dp_dut/n234 ;
   wire \dp_dut/n233 ;
   wire \dp_dut/n232 ;
   wire \dp_dut/n231 ;
   wire \dp_dut/n230 ;
   wire \dp_dut/n229 ;
   wire \dp_dut/n228 ;
   wire \dp_dut/n227 ;
   wire \dp_dut/n226 ;
   wire \dp_dut/n225 ;
   wire \dp_dut/n224 ;
   wire \dp_dut/n223 ;
   wire \dp_dut/n222 ;
   wire \dp_dut/n221 ;
   wire \dp_dut/n220 ;
   wire \dp_dut/n219 ;
   wire \dp_dut/n218 ;
   wire \dp_dut/n217 ;
   wire \dp_dut/n216 ;
   wire \dp_dut/n215 ;
   wire \dp_dut/n214 ;
   wire \dp_dut/n213 ;
   wire \dp_dut/n212 ;
   wire \dp_dut/n211 ;
   wire \dp_dut/n210 ;
   wire \dp_dut/n209 ;
   wire \dp_dut/n208 ;
   wire \dp_dut/n205 ;
   wire \dp_dut/n204 ;
   wire \dp_dut/n203 ;
   wire \dp_dut/n202 ;
   wire \dp_dut/dp_cluster_1/N28 ;
   wire \dp_dut/dp_cluster_1/N29 ;
   wire \dp_dut/dp_cluster_1/N30 ;
   wire \dp_dut/dp_cluster_1/N34 ;
   wire \dp_dut/dp_cluster_0/N100 ;
   wire \dp_dut/dp_cluster_0/N101 ;
   wire \dp_dut/dp_cluster_0/N102 ;
   wire \dp_dut/dp_cluster_0/N103 ;
   wire \dp_dut/dp_cluster_0/N104 ;
   wire \dp_dut/dp_cluster_0/N105 ;
   wire \dp_dut/dp_cluster_0/N106 ;
   wire \dp_dut/dp_cluster_0/N142 ;
   wire \dp_dut/dp_cluster_0/N143 ;
   wire \dp_dut/dp_cluster_0/N144 ;
   wire \dp_dut/dp_cluster_0/N145 ;
   wire \dp_dut/dp_cluster_0/N146 ;
   wire \dp_dut/dp_cluster_0/N147 ;
   wire \dp_dut/dp_cluster_0/N148 ;
   wire \dp_dut/dp_cluster_0/N149 ;
   wire \dp_dut/dp_cluster_0/N150 ;
   wire \dp_dut/dp_cluster_0/N151 ;
   wire \dp_dut/dp_cluster_0/N152 ;
   wire \dp_dut/dp_cluster_0/N153 ;
   wire \dp_dut/dp_cluster_0/N154 ;
   wire \dp_dut/dp_cluster_0/N94 ;
   wire \dp_dut/dp_cluster_0/N95 ;
   wire \dp_dut/dp_cluster_0/N96 ;
   wire \dp_dut/dp_cluster_0/N97 ;
   wire \dp_dut/dp_cluster_0/N98 ;
   wire \dp_dut/dp_cluster_0/N99 ;
   wire \dp_dut/N356 ;
   wire \dp_dut/N355 ;
   wire \dp_dut/N354 ;
   wire \dp_dut/N353 ;
   wire \dp_dut/N352 ;
   wire \dp_dut/N351 ;
   wire \dp_dut/N350 ;
   wire \dp_dut/N349 ;
   wire \dp_dut/N348 ;
   wire \dp_dut/N347 ;
   wire \dp_dut/N346 ;
   wire \dp_dut/N345 ;
   wire \dp_dut/N344 ;
   wire \dp_dut/N343 ;
   wire \dp_dut/N342 ;
   wire \dp_dut/N341 ;
   wire \dp_dut/N340 ;
   wire \dp_dut/N339 ;
   wire \dp_dut/N338 ;
   wire \dp_dut/N337 ;
   wire \dp_dut/N336 ;
   wire \dp_dut/N335 ;
   wire \dp_dut/N334 ;
   wire \dp_dut/N333 ;
   wire \dp_dut/N329 ;
   wire \dp_dut/N328 ;
   wire \dp_dut/N327 ;
   wire \dp_dut/N326 ;
   wire \dp_dut/N325 ;
   wire \dp_dut/N324 ;
   wire \dp_dut/N323 ;
   wire \dp_dut/N322 ;
   wire \dp_dut/N318 ;
   wire \dp_dut/N317 ;
   wire \dp_dut/N316 ;
   wire \dp_dut/N315 ;
   wire \dp_dut/N314 ;
   wire \dp_dut/N313 ;
   wire \dp_dut/N312 ;
   wire \dp_dut/N311 ;
   wire \dp_dut/N300 ;
   wire \dp_dut/N299 ;
   wire \dp_dut/N298 ;
   wire \dp_dut/N297 ;
   wire \dp_dut/N296 ;
   wire \dp_dut/N295 ;
   wire \dp_dut/N294 ;
   wire \dp_dut/N293 ;
   wire \dp_dut/N245 ;
   wire \dp_dut/N244 ;
   wire \dp_dut/N243 ;
   wire \dp_dut/N242 ;
   wire \dp_dut/N241 ;
   wire \dp_dut/N240 ;
   wire \dp_dut/N239 ;
   wire \dp_dut/N238 ;
   wire \dp_dut/N237 ;
   wire \dp_dut/N236 ;
   wire \dp_dut/N235 ;
   wire \dp_dut/N234 ;
   wire \dp_dut/N233 ;
   wire \dp_dut/N232 ;
   wire \dp_dut/N231 ;
   wire \dp_dut/N230 ;
   wire \dp_dut/N229 ;
   wire \dp_dut/N228 ;
   wire \dp_dut/N227 ;
   wire \dp_dut/N226 ;
   wire \dp_dut/N225 ;
   wire \dp_dut/N224 ;
   wire \dp_dut/N223 ;
   wire \dp_dut/N222 ;
   wire \dp_dut/N221 ;
   wire \dp_dut/N220 ;
   wire \dp_dut/N219 ;
   wire \dp_dut/N218 ;
   wire \dp_dut/N217 ;
   wire \dp_dut/N216 ;
   wire \dp_dut/N215 ;
   wire \dp_dut/N214 ;
   wire \dp_dut/N213 ;
   wire \dp_dut/N212 ;
   wire \dp_dut/N211 ;
   wire \dp_dut/N210 ;
   wire \dp_dut/N209 ;
   wire \dp_dut/N208 ;
   wire \dp_dut/N207 ;
   wire \dp_dut/N206 ;
   wire \dp_dut/N205 ;
   wire \dp_dut/N204 ;
   wire \dp_dut/N203 ;
   wire \dp_dut/N202 ;
   wire \dp_dut/N201 ;
   wire \dp_dut/N200 ;
   wire \dp_dut/N199 ;
   wire \dp_dut/N196 ;
   wire \dp_dut/N194 ;
   wire \dp_dut/N193 ;
   wire \dp_dut/N192 ;
   wire \dp_dut/N191 ;
   wire \dp_dut/N190 ;
   wire \dp_dut/N189 ;
   wire \dp_dut/N188 ;
   wire \dp_dut/N187 ;
   wire \dp_dut/N186 ;
   wire \dp_dut/N185 ;
   wire \dp_dut/N184 ;
   wire \dp_dut/N183 ;
   wire \dp_dut/N182 ;
   wire \dp_dut/N181 ;
   wire \dp_dut/N180 ;
   wire \dp_dut/N179 ;
   wire \dp_dut/N178 ;
   wire \dp_dut/N177 ;
   wire \dp_dut/N176 ;
   wire \dp_dut/N175 ;
   wire \dp_dut/N174 ;
   wire \dp_dut/N173 ;
   wire \dp_dut/N172 ;
   wire \dp_dut/N171 ;
   wire \dp_dut/N170 ;
   wire \dp_dut/N169 ;
   wire \dp_dut/N168 ;
   wire \dp_dut/N167 ;
   wire \dp_dut/N166 ;
   wire \dp_dut/N165 ;
   wire \dp_dut/N164 ;
   wire \dp_dut/N163 ;
   wire \dp_dut/N162 ;
   wire \dp_dut/N161 ;
   wire \dp_dut/N160 ;
   wire \dp_dut/N159 ;
   wire \dp_dut/N158 ;
   wire \dp_dut/N157 ;
   wire \dp_dut/N156 ;
   wire \dp_dut/N155 ;
   wire \dp_dut/N63 ;
   wire \dp_dut/N62 ;
   wire \dp_dut/N61 ;
   wire \dp_dut/out_change_1_sol1[1] ;
   wire \dp_dut/N59 ;
   wire \dp_dut/N58 ;
   wire \dp_dut/N57 ;
   wire \dp_dut/N56 ;
   wire \dp_dut/N55 ;
   wire \dp_dut/N54 ;
   wire \dp_dut/N53 ;
   wire \dp_dut/N52 ;
   wire \dp_dut/N51 ;
   wire \dp_dut/N50 ;
   wire \dp_dut/N49 ;
   wire \dp_dut/N48 ;
   wire \dp_dut/N47 ;
   wire \dp_dut/N46 ;
   wire \dp_dut/N45 ;
   wire \dp_dut/N42 ;
   wire \dp_dut/N41 ;
   wire \dp_dut/N40 ;
   wire \dp_dut/N39 ;
   wire \dp_dut/N38 ;
   wire \dp_dut/dp_cluster_0/add_1_root_add_121_5/carry[6] ;
   wire \dp_dut/dp_cluster_0/add_0_root_add_121_5/carry[3] ;
   wire \dp_dut/dp_cluster_1/add_0_root_add_75_3/carry[4] ;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n173;
   wire n174;
   wire n175;
   wire n176;
   wire n177;
   wire n178;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire n190;
   wire n191;
   wire n192;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n211;
   wire n212;
   wire n213;
   wire n214;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire n225;
   wire n226;
   wire n227;
   wire n228;
   wire n229;
   wire n230;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n237;
   wire n238;
   wire n239;
   wire n240;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n246;
   wire n247;
   wire n248;
   wire n249;
   wire n250;
   wire n251;
   wire n252;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire n259;
   wire n260;
   wire n261;
   wire n262;
   wire n263;
   wire n264;
   wire [1:0] cmd;
   wire [7:0] \dp_dut/dollar_025_num ;
   wire [7:0] \dp_dut/dollar_05_num ;
   wire [7:0] \dp_dut/dollar_1_num ;
   wire [15:0] \dp_dut/inserted_money ;
   wire [6:0] \dp_dut/total_price ;
   wire [7:0] \dp_dut/item_d_num ;
   wire [7:0] \dp_dut/item_c_num ;
   wire [7:0] \dp_dut/item_b_num ;
   wire [7:0] \dp_dut/item_a_num ;
   wire [16:0] \dp_dut/sub_76/carry ;
   wire [8:0] \dp_dut/r474/carry ;
   wire [8:0] \dp_dut/r475/carry ;
   wire [8:0] \dp_dut/r476/carry ;
   wire [8:0] \dp_dut/r477/carry ;
   wire [16:0] \dp_dut/sub_137/carry ;
   wire [8:0] \dp_dut/sub_171/carry ;
   wire [8:0] \dp_dut/sub_172/carry ;
   wire [8:0] \dp_dut/sub_173/carry ;
   wire [8:0] \dp_dut/sub_185/carry ;
   wire [8:0] \dp_dut/sub_186/carry ;
   wire [8:0] \dp_dut/sub_187/carry ;

   NOR2X1 \main_FSM_dut/U9  (.Y(\main_FSM_dut/n5 ),
	.B(n134),
	.A(out_state[1]));
   AOI21X1 \main_FSM_dut/U8  (.Y(\main_FSM_dut/N27 ),
	.C(in_restart),
	.B(in_next),
	.A(\main_FSM_dut/n5 ));
   OR2X1 \main_FSM_dut/U7  (.Y(\main_FSM_dut/n3 ),
	.B(out_state[1]),
	.A(in_restart));
   OAI21X1 \main_FSM_dut/U6  (.Y(\main_FSM_dut/n4 ),
	.C(out_state[0]),
	.B(in_finish),
	.A(in_next));
   NOR2X1 \main_FSM_dut/U5  (.Y(\main_FSM_dut/N28 ),
	.B(\main_FSM_dut/n4 ),
	.A(\main_FSM_dut/n3 ));
   DFFNEGX1 \main_FSM_dut/out_cmd_reg[0]  (.Q(cmd[0]),
	.D(\main_FSM_dut/N38 ),
	.CLK(in_clkb));
   DFFNEGX1 \main_FSM_dut/out_cmd_reg[1]  (.Q(cmd[1]),
	.D(n133),
	.CLK(in_clkb));
   DFFNEGX1 \main_FSM_dut/next_out_state_reg[0]  (.Q(\main_FSM_dut/N38 ),
	.D(\main_FSM_dut/N27 ),
	.CLK(n90));
   DFFNEGX1 \main_FSM_dut/out_state_reg[1]  (.Q(out_state[1]),
	.D(\main_FSM_dut/next_out_state[1] ),
	.CLK(in_clkb));
   DFFNEGX1 \main_FSM_dut/next_out_state_reg[1]  (.Q(\main_FSM_dut/next_out_state[1] ),
	.D(\main_FSM_dut/N28 ),
	.CLK(n97));
   DFFNEGX1 \main_FSM_dut/out_state_reg[0]  (.Q(out_state[0]),
	.D(\main_FSM_dut/N38 ),
	.CLK(in_clkb));
   NAND3X1 \dp_dut/U434  (.Y(\dp_dut/n389 ),
	.C(\dp_dut/N63 ),
	.B(\dp_dut/N61 ),
	.A(\dp_dut/N62 ));
   NAND2X1 \dp_dut/U433  (.Y(\dp_dut/n342 ),
	.B(out_sol_ok),
	.A(\dp_dut/N196 ));
   NOR2X1 \dp_dut/U432  (.Y(\dp_dut/n388 ),
	.B(cmd[0]),
	.A(cmd[1]));
   NAND2X1 \dp_dut/U431  (.Y(\dp_dut/n343 ),
	.B(n100),
	.A(\dp_dut/n388 ));
   NAND2X1 \dp_dut/U430  (.Y(\dp_dut/n372 ),
	.B(n100),
	.A(\dp_dut/n293 ));
   NAND2X1 \dp_dut/U429  (.Y(\dp_dut/n202 ),
	.B(n131),
	.A(cmd[1]));
   NOR2X1 \dp_dut/U428  (.Y(\dp_dut/n387 ),
	.B(\dp_dut/n293 ),
	.A(in_restart));
   NAND3X1 \dp_dut/U427  (.Y(\dp_dut/n344 ),
	.C(\dp_dut/n387 ),
	.B(n78),
	.A(n132));
   NAND2X1 \dp_dut/U426  (.Y(\dp_dut/n204 ),
	.B(\dp_dut/n344 ),
	.A(\dp_dut/n372 ));
   NOR2X1 \dp_dut/U425  (.Y(\dp_dut/n234 ),
	.B(in_restart),
	.A(n80));
   OAI21X1 \dp_dut/U423  (.Y(\dp_dut/n345 ),
	.C(n74),
	.B(\dp_dut/n343 ),
	.A(\dp_dut/n342 ));
   AOI21X1 \dp_dut/U422  (.Y(\dp_dut/n380 ),
	.C(n72),
	.B(n104),
	.A(\dp_dut/n293 ));
   NOR2X1 \dp_dut/U421  (.Y(\dp_dut/n386 ),
	.B(\dp_dut/item_b_num [6]),
	.A(\dp_dut/item_b_num [7]));
   NAND3X1 \dp_dut/U420  (.Y(\dp_dut/n383 ),
	.C(\dp_dut/n386 ),
	.B(n205),
	.A(n206));
   NOR2X1 \dp_dut/U419  (.Y(\dp_dut/n385 ),
	.B(\dp_dut/item_b_num [2]),
	.A(\dp_dut/item_b_num [3]));
   NAND3X1 \dp_dut/U418  (.Y(\dp_dut/n384 ),
	.C(\dp_dut/n385 ),
	.B(n209),
	.A(n210));
   OR2X1 \dp_dut/U417  (.Y(out_stock_b),
	.B(\dp_dut/n384 ),
	.A(\dp_dut/n383 ));
   NAND2X1 \dp_dut/U416  (.Y(\dp_dut/n288 ),
	.B(n73),
	.A(\dp_dut/n293 ));
   NOR2X1 \dp_dut/U415  (.Y(\dp_dut/n382 ),
	.B(n104),
	.A(\dp_dut/n288 ));
   NAND3X1 \dp_dut/U414  (.Y(\dp_dut/n381 ),
	.C(\dp_dut/n382 ),
	.B(n217),
	.A(out_stock_b));
   OAI21X1 \dp_dut/U413  (.Y(\dp_dut/n479 ),
	.C(\dp_dut/n381 ),
	.B(n217),
	.A(\dp_dut/n380 ));
   AOI22X1 \dp_dut/U411  (.Y(\dp_dut/n379 ),
	.D(n98),
	.C(\dp_dut/N170 ),
	.B(n71),
	.A(\dp_dut/N213 ));
   OAI21X1 \dp_dut/U410  (.Y(\dp_dut/n478 ),
	.C(\dp_dut/n379 ),
	.B(n216),
	.A(n73));
   AOI22X1 \dp_dut/U408  (.Y(\dp_dut/n369 ),
	.D(n74),
	.C(\dp_dut/dollar_025_num [0]),
	.B(n85),
	.A(\dp_dut/N349 ));
   NOR2X1 \dp_dut/U406  (.Y(\dp_dut/n374 ),
	.B(\dp_dut/N322 ),
	.A(\dp_dut/N323 ));
   NOR2X1 \dp_dut/U405  (.Y(\dp_dut/n375 ),
	.B(\dp_dut/N324 ),
	.A(\dp_dut/N325 ));
   NOR2X1 \dp_dut/U404  (.Y(\dp_dut/n377 ),
	.B(\dp_dut/N326 ),
	.A(\dp_dut/N327 ));
   NOR2X1 \dp_dut/U403  (.Y(\dp_dut/n378 ),
	.B(\dp_dut/N328 ),
	.A(\dp_dut/N329 ));
   NAND3X1 \dp_dut/U402  (.Y(\dp_dut/n373 ),
	.C(\dp_dut/n376 ),
	.B(\dp_dut/n375 ),
	.A(\dp_dut/n374 ));
   NAND2X1 \dp_dut/U401  (.Y(\dp_dut/n203 ),
	.B(n82),
	.A(\dp_dut/N59 ));
   NAND2X1 \dp_dut/U400  (.Y(\dp_dut/n210 ),
	.B(\dp_dut/n203 ),
	.A(out_change[1]));
   OAI22X1 \dp_dut/U399  (.Y(\dp_dut/n371 ),
	.D(\dp_dut/n373 ),
	.C(n202),
	.B(\dp_dut/n210 ),
	.A(n107));
   AOI22X1 \dp_dut/U398  (.Y(\dp_dut/n370 ),
	.D(n83),
	.C(\dp_dut/N187 ),
	.B(\dp_dut/n371 ),
	.A(n70));
   NAND2X1 \dp_dut/U397  (.Y(\dp_dut/n477 ),
	.B(\dp_dut/n370 ),
	.A(\dp_dut/n369 ));
   AOI22X1 \dp_dut/U396  (.Y(\dp_dut/n368 ),
	.D(n84),
	.C(\dp_dut/N350 ),
	.B(n83),
	.A(\dp_dut/N188 ));
   OAI21X1 \dp_dut/U395  (.Y(\dp_dut/n476 ),
	.C(\dp_dut/n368 ),
	.B(n149),
	.A(n2));
   AOI22X1 \dp_dut/U394  (.Y(\dp_dut/n367 ),
	.D(n84),
	.C(\dp_dut/N351 ),
	.B(n83),
	.A(\dp_dut/N189 ));
   OAI21X1 \dp_dut/U393  (.Y(\dp_dut/n475 ),
	.C(\dp_dut/n367 ),
	.B(n148),
	.A(n2));
   AOI22X1 \dp_dut/U392  (.Y(\dp_dut/n366 ),
	.D(n84),
	.C(\dp_dut/N352 ),
	.B(n83),
	.A(\dp_dut/N190 ));
   OAI21X1 \dp_dut/U391  (.Y(\dp_dut/n474 ),
	.C(\dp_dut/n366 ),
	.B(n147),
	.A(n2));
   AOI22X1 \dp_dut/U390  (.Y(\dp_dut/n365 ),
	.D(n84),
	.C(\dp_dut/N353 ),
	.B(n83),
	.A(\dp_dut/N191 ));
   OAI21X1 \dp_dut/U389  (.Y(\dp_dut/n473 ),
	.C(\dp_dut/n365 ),
	.B(n146),
	.A(n2));
   AOI22X1 \dp_dut/U388  (.Y(\dp_dut/n364 ),
	.D(n84),
	.C(\dp_dut/N354 ),
	.B(n83),
	.A(\dp_dut/N192 ));
   OAI21X1 \dp_dut/U387  (.Y(\dp_dut/n472 ),
	.C(\dp_dut/n364 ),
	.B(n145),
	.A(n2));
   AOI22X1 \dp_dut/U386  (.Y(\dp_dut/n363 ),
	.D(n84),
	.C(\dp_dut/N355 ),
	.B(n83),
	.A(\dp_dut/N193 ));
   OAI21X1 \dp_dut/U385  (.Y(\dp_dut/n471 ),
	.C(\dp_dut/n363 ),
	.B(n144),
	.A(n2));
   AOI22X1 \dp_dut/U384  (.Y(\dp_dut/n362 ),
	.D(n84),
	.C(\dp_dut/N356 ),
	.B(n83),
	.A(\dp_dut/N194 ));
   OAI21X1 \dp_dut/U383  (.Y(\dp_dut/n470 ),
	.C(\dp_dut/n362 ),
	.B(n150),
	.A(n2));
   AOI22X1 \dp_dut/U382  (.Y(\dp_dut/n361 ),
	.D(n98),
	.C(\dp_dut/N169 ),
	.B(n71),
	.A(\dp_dut/N212 ));
   OAI21X1 \dp_dut/U381  (.Y(\dp_dut/n469 ),
	.C(\dp_dut/n361 ),
	.B(n215),
	.A(\dp_dut/n345 ));
   AOI22X1 \dp_dut/U380  (.Y(\dp_dut/n360 ),
	.D(n98),
	.C(\dp_dut/N168 ),
	.B(n71),
	.A(\dp_dut/N211 ));
   OAI21X1 \dp_dut/U379  (.Y(\dp_dut/n468 ),
	.C(\dp_dut/n360 ),
	.B(n189),
	.A(n73));
   AOI22X1 \dp_dut/U378  (.Y(\dp_dut/n359 ),
	.D(n98),
	.C(\dp_dut/N167 ),
	.B(n71),
	.A(\dp_dut/N210 ));
   OAI21X1 \dp_dut/U377  (.Y(\dp_dut/n467 ),
	.C(\dp_dut/n359 ),
	.B(n190),
	.A(\dp_dut/n345 ));
   AOI22X1 \dp_dut/U376  (.Y(\dp_dut/n358 ),
	.D(n98),
	.C(\dp_dut/N166 ),
	.B(n71),
	.A(\dp_dut/N209 ));
   OAI21X1 \dp_dut/U375  (.Y(\dp_dut/n466 ),
	.C(\dp_dut/n358 ),
	.B(n191),
	.A(n73));
   AOI22X1 \dp_dut/U374  (.Y(\dp_dut/n357 ),
	.D(n98),
	.C(\dp_dut/N165 ),
	.B(n71),
	.A(\dp_dut/N208 ));
   OAI21X1 \dp_dut/U373  (.Y(\dp_dut/n465 ),
	.C(\dp_dut/n357 ),
	.B(n73),
	.A(n192));
   AOI22X1 \dp_dut/U372  (.Y(\dp_dut/n356 ),
	.D(n98),
	.C(\dp_dut/N164 ),
	.B(n71),
	.A(\dp_dut/N207 ));
   OAI21X1 \dp_dut/U371  (.Y(\dp_dut/n464 ),
	.C(\dp_dut/n356 ),
	.B(\dp_dut/n345 ),
	.A(n193));
   AOI22X1 \dp_dut/U370  (.Y(\dp_dut/n355 ),
	.D(n98),
	.C(\dp_dut/N163 ),
	.B(n71),
	.A(\dp_dut/N206 ));
   OAI21X1 \dp_dut/U369  (.Y(\dp_dut/n463 ),
	.C(\dp_dut/n355 ),
	.B(n73),
	.A(n195));
   AOI22X1 \dp_dut/U368  (.Y(\dp_dut/n354 ),
	.D(n98),
	.C(\dp_dut/N162 ),
	.B(n71),
	.A(\dp_dut/N205 ));
   OAI21X1 \dp_dut/U367  (.Y(\dp_dut/n462 ),
	.C(\dp_dut/n354 ),
	.B(\dp_dut/n345 ),
	.A(n196));
   AOI22X1 \dp_dut/U366  (.Y(\dp_dut/n353 ),
	.D(n98),
	.C(\dp_dut/N161 ),
	.B(n71),
	.A(\dp_dut/N204 ));
   OAI21X1 \dp_dut/U365  (.Y(\dp_dut/n461 ),
	.C(\dp_dut/n353 ),
	.B(n73),
	.A(n197));
   AOI22X1 \dp_dut/U364  (.Y(\dp_dut/n352 ),
	.D(n98),
	.C(\dp_dut/N160 ),
	.B(n71),
	.A(\dp_dut/N203 ));
   OAI21X1 \dp_dut/U363  (.Y(\dp_dut/n460 ),
	.C(\dp_dut/n352 ),
	.B(\dp_dut/n345 ),
	.A(n198));
   AOI22X1 \dp_dut/U362  (.Y(\dp_dut/n351 ),
	.D(n98),
	.C(\dp_dut/N159 ),
	.B(n71),
	.A(\dp_dut/N202 ));
   OAI21X1 \dp_dut/U361  (.Y(\dp_dut/n459 ),
	.C(\dp_dut/n351 ),
	.B(n73),
	.A(n199));
   AOI22X1 \dp_dut/U360  (.Y(\dp_dut/n350 ),
	.D(n98),
	.C(\dp_dut/N158 ),
	.B(n71),
	.A(\dp_dut/N201 ));
   OAI21X1 \dp_dut/U359  (.Y(\dp_dut/n458 ),
	.C(\dp_dut/n350 ),
	.B(\dp_dut/n345 ),
	.A(n200));
   AOI22X1 \dp_dut/U358  (.Y(\dp_dut/n349 ),
	.D(n98),
	.C(\dp_dut/N157 ),
	.B(n71),
	.A(\dp_dut/N200 ));
   OAI21X1 \dp_dut/U357  (.Y(\dp_dut/n457 ),
	.C(\dp_dut/n349 ),
	.B(n73),
	.A(n201));
   AOI22X1 \dp_dut/U356  (.Y(\dp_dut/n348 ),
	.D(n98),
	.C(\dp_dut/N156 ),
	.B(n71),
	.A(\dp_dut/N199 ));
   OAI21X1 \dp_dut/U355  (.Y(\dp_dut/n456 ),
	.C(\dp_dut/n348 ),
	.B(\dp_dut/n345 ),
	.A(n202));
   AOI22X1 \dp_dut/U354  (.Y(\dp_dut/n346 ),
	.D(n98),
	.C(\dp_dut/N155 ),
	.B(n71),
	.A(\dp_dut/N155 ));
   OAI21X1 \dp_dut/U353  (.Y(\dp_dut/n455 ),
	.C(\dp_dut/n346 ),
	.B(n203),
	.A(\dp_dut/n345 ));
   NAND2X1 \dp_dut/U352  (.Y(\dp_dut/n341 ),
	.B(\dp_dut/n344 ),
	.A(\dp_dut/n343 ));
   OAI21X1 \dp_dut/U351  (.Y(\dp_dut/n284 ),
	.C(n102),
	.B(\dp_dut/n342 ),
	.A(n99));
   NAND2X1 \dp_dut/U350  (.Y(\dp_dut/n340 ),
	.B(n1),
	.A(\dp_dut/N221 ));
   OAI21X1 \dp_dut/U349  (.Y(\dp_dut/n454 ),
	.C(\dp_dut/n340 ),
	.B(n180),
	.A(\dp_dut/n284 ));
   AOI21X1 \dp_dut/U348  (.Y(\dp_dut/n339 ),
	.C(\dp_dut/n234 ),
	.B(n1),
	.A(\dp_dut/N214 ));
   OAI21X1 \dp_dut/U347  (.Y(\dp_dut/n453 ),
	.C(\dp_dut/n339 ),
	.B(n187),
	.A(\dp_dut/n284 ));
   NAND2X1 \dp_dut/U346  (.Y(\dp_dut/n338 ),
	.B(n1),
	.A(\dp_dut/N215 ));
   OAI21X1 \dp_dut/U345  (.Y(\dp_dut/n452 ),
	.C(\dp_dut/n338 ),
	.B(n186),
	.A(\dp_dut/n284 ));
   NAND2X1 \dp_dut/U344  (.Y(\dp_dut/n337 ),
	.B(n1),
	.A(\dp_dut/N216 ));
   OAI21X1 \dp_dut/U343  (.Y(\dp_dut/n451 ),
	.C(\dp_dut/n337 ),
	.B(n185),
	.A(\dp_dut/n284 ));
   NAND2X1 \dp_dut/U342  (.Y(\dp_dut/n336 ),
	.B(n1),
	.A(\dp_dut/N217 ));
   OAI21X1 \dp_dut/U341  (.Y(\dp_dut/n450 ),
	.C(\dp_dut/n336 ),
	.B(n184),
	.A(\dp_dut/n284 ));
   NAND2X1 \dp_dut/U340  (.Y(\dp_dut/n335 ),
	.B(n1),
	.A(\dp_dut/N218 ));
   OAI21X1 \dp_dut/U339  (.Y(\dp_dut/n449 ),
	.C(\dp_dut/n335 ),
	.B(n183),
	.A(\dp_dut/n284 ));
   NAND2X1 \dp_dut/U338  (.Y(\dp_dut/n334 ),
	.B(n1),
	.A(\dp_dut/N219 ));
   OAI21X1 \dp_dut/U337  (.Y(\dp_dut/n448 ),
	.C(\dp_dut/n334 ),
	.B(n182),
	.A(\dp_dut/n284 ));
   NAND2X1 \dp_dut/U336  (.Y(\dp_dut/n333 ),
	.B(n1),
	.A(\dp_dut/N220 ));
   OAI21X1 \dp_dut/U335  (.Y(\dp_dut/n447 ),
	.C(\dp_dut/n333 ),
	.B(n181),
	.A(\dp_dut/n284 ));
   AOI21X1 \dp_dut/U334  (.Y(\dp_dut/n326 ),
	.C(n72),
	.B(n103),
	.A(\dp_dut/n293 ));
   NOR2X1 \dp_dut/U333  (.Y(\dp_dut/n332 ),
	.B(\dp_dut/item_a_num [6]),
	.A(\dp_dut/item_a_num [7]));
   NAND3X1 \dp_dut/U332  (.Y(\dp_dut/n329 ),
	.C(\dp_dut/n332 ),
	.B(n182),
	.A(n183));
   NOR2X1 \dp_dut/U331  (.Y(\dp_dut/n331 ),
	.B(\dp_dut/item_a_num [2]),
	.A(\dp_dut/item_a_num [3]));
   NAND3X1 \dp_dut/U330  (.Y(\dp_dut/n330 ),
	.C(\dp_dut/n331 ),
	.B(n186),
	.A(n187));
   OR2X1 \dp_dut/U329  (.Y(out_stock_a),
	.B(\dp_dut/n330 ),
	.A(\dp_dut/n329 ));
   NOR2X1 \dp_dut/U328  (.Y(\dp_dut/n328 ),
	.B(n103),
	.A(\dp_dut/n288 ));
   NAND3X1 \dp_dut/U327  (.Y(\dp_dut/n327 ),
	.C(\dp_dut/n328 ),
	.B(n188),
	.A(out_stock_a));
   OAI21X1 \dp_dut/U326  (.Y(\dp_dut/n446 ),
	.C(\dp_dut/n327 ),
	.B(n188),
	.A(\dp_dut/n326 ));
   NAND2X1 \dp_dut/U325  (.Y(\dp_dut/n325 ),
	.B(n1),
	.A(\dp_dut/N229 ));
   OAI21X1 \dp_dut/U324  (.Y(\dp_dut/n445 ),
	.C(\dp_dut/n325 ),
	.B(n211),
	.A(\dp_dut/n284 ));
   NAND2X1 \dp_dut/U323  (.Y(\dp_dut/n324 ),
	.B(n1),
	.A(\dp_dut/N222 ));
   OAI21X1 \dp_dut/U322  (.Y(\dp_dut/n444 ),
	.C(\dp_dut/n324 ),
	.B(n210),
	.A(\dp_dut/n284 ));
   NAND2X1 \dp_dut/U321  (.Y(\dp_dut/n323 ),
	.B(n1),
	.A(\dp_dut/N223 ));
   OAI21X1 \dp_dut/U320  (.Y(\dp_dut/n443 ),
	.C(\dp_dut/n323 ),
	.B(n209),
	.A(n86));
   AOI21X1 \dp_dut/U319  (.Y(\dp_dut/n322 ),
	.C(\dp_dut/n234 ),
	.B(n1),
	.A(\dp_dut/N224 ));
   OAI21X1 \dp_dut/U318  (.Y(\dp_dut/n442 ),
	.C(\dp_dut/n322 ),
	.B(n208),
	.A(n86));
   NAND2X1 \dp_dut/U317  (.Y(\dp_dut/n321 ),
	.B(n1),
	.A(\dp_dut/N225 ));
   OAI21X1 \dp_dut/U316  (.Y(\dp_dut/n441 ),
	.C(\dp_dut/n321 ),
	.B(n207),
	.A(n86));
   NAND2X1 \dp_dut/U315  (.Y(\dp_dut/n320 ),
	.B(n1),
	.A(\dp_dut/N226 ));
   OAI21X1 \dp_dut/U314  (.Y(\dp_dut/n440 ),
	.C(\dp_dut/n320 ),
	.B(n206),
	.A(n86));
   NAND2X1 \dp_dut/U313  (.Y(\dp_dut/n319 ),
	.B(n1),
	.A(\dp_dut/N227 ));
   OAI21X1 \dp_dut/U312  (.Y(\dp_dut/n439 ),
	.C(\dp_dut/n319 ),
	.B(n205),
	.A(n86));
   NAND2X1 \dp_dut/U311  (.Y(\dp_dut/n318 ),
	.B(n1),
	.A(\dp_dut/N228 ));
   OAI21X1 \dp_dut/U310  (.Y(\dp_dut/n438 ),
	.C(\dp_dut/n318 ),
	.B(n204),
	.A(n86));
   NAND2X1 \dp_dut/U309  (.Y(\dp_dut/n317 ),
	.B(n1),
	.A(\dp_dut/N237 ));
   OAI21X1 \dp_dut/U308  (.Y(\dp_dut/n437 ),
	.C(\dp_dut/n317 ),
	.B(n171),
	.A(n86));
   NAND2X1 \dp_dut/U307  (.Y(\dp_dut/n316 ),
	.B(n1),
	.A(\dp_dut/N230 ));
   OAI21X1 \dp_dut/U306  (.Y(\dp_dut/n436 ),
	.C(\dp_dut/n316 ),
	.B(n178),
	.A(n86));
   NAND2X1 \dp_dut/U305  (.Y(\dp_dut/n315 ),
	.B(n1),
	.A(\dp_dut/N231 ));
   OAI21X1 \dp_dut/U304  (.Y(\dp_dut/n435 ),
	.C(\dp_dut/n315 ),
	.B(n177),
	.A(n86));
   AOI21X1 \dp_dut/U303  (.Y(\dp_dut/n314 ),
	.C(\dp_dut/n234 ),
	.B(n1),
	.A(\dp_dut/N232 ));
   OAI21X1 \dp_dut/U302  (.Y(\dp_dut/n434 ),
	.C(\dp_dut/n314 ),
	.B(n176),
	.A(n86));
   NAND2X1 \dp_dut/U301  (.Y(\dp_dut/n313 ),
	.B(n1),
	.A(\dp_dut/N233 ));
   OAI21X1 \dp_dut/U300  (.Y(\dp_dut/n433 ),
	.C(\dp_dut/n313 ),
	.B(n175),
	.A(n86));
   NAND2X1 \dp_dut/U299  (.Y(\dp_dut/n312 ),
	.B(n1),
	.A(\dp_dut/N234 ));
   OAI21X1 \dp_dut/U298  (.Y(\dp_dut/n432 ),
	.C(\dp_dut/n312 ),
	.B(n174),
	.A(n86));
   NAND2X1 \dp_dut/U297  (.Y(\dp_dut/n311 ),
	.B(n1),
	.A(\dp_dut/N235 ));
   OAI21X1 \dp_dut/U296  (.Y(\dp_dut/n431 ),
	.C(\dp_dut/n311 ),
	.B(n173),
	.A(n86));
   NAND2X1 \dp_dut/U295  (.Y(\dp_dut/n310 ),
	.B(n1),
	.A(\dp_dut/N236 ));
   OAI21X1 \dp_dut/U294  (.Y(\dp_dut/n430 ),
	.C(\dp_dut/n310 ),
	.B(n172),
	.A(n86));
   AOI21X1 \dp_dut/U293  (.Y(\dp_dut/n303 ),
	.C(n72),
	.B(n105),
	.A(\dp_dut/n293 ));
   NOR2X1 \dp_dut/U292  (.Y(\dp_dut/n309 ),
	.B(\dp_dut/item_c_num [6]),
	.A(\dp_dut/item_c_num [7]));
   NAND3X1 \dp_dut/U291  (.Y(\dp_dut/n306 ),
	.C(\dp_dut/n309 ),
	.B(n173),
	.A(n174));
   NOR2X1 \dp_dut/U290  (.Y(\dp_dut/n308 ),
	.B(\dp_dut/item_c_num [2]),
	.A(\dp_dut/item_c_num [3]));
   NAND3X1 \dp_dut/U289  (.Y(\dp_dut/n307 ),
	.C(\dp_dut/n308 ),
	.B(n177),
	.A(n178));
   OR2X1 \dp_dut/U288  (.Y(out_stock_c),
	.B(\dp_dut/n307 ),
	.A(\dp_dut/n306 ));
   NOR2X1 \dp_dut/U287  (.Y(\dp_dut/n305 ),
	.B(n105),
	.A(\dp_dut/n288 ));
   NAND3X1 \dp_dut/U286  (.Y(\dp_dut/n304 ),
	.C(\dp_dut/n305 ),
	.B(n179),
	.A(out_stock_c));
   OAI21X1 \dp_dut/U285  (.Y(\dp_dut/n429 ),
	.C(\dp_dut/n304 ),
	.B(n179),
	.A(\dp_dut/n303 ));
   NAND2X1 \dp_dut/U284  (.Y(\dp_dut/n302 ),
	.B(n1),
	.A(\dp_dut/N245 ));
   OAI21X1 \dp_dut/U283  (.Y(\dp_dut/n428 ),
	.C(\dp_dut/n302 ),
	.B(n162),
	.A(n86));
   NAND2X1 \dp_dut/U282  (.Y(\dp_dut/n301 ),
	.B(n1),
	.A(\dp_dut/N238 ));
   OAI21X1 \dp_dut/U281  (.Y(\dp_dut/n427 ),
	.C(\dp_dut/n301 ),
	.B(n169),
	.A(n86));
   NAND2X1 \dp_dut/U280  (.Y(\dp_dut/n300 ),
	.B(n1),
	.A(\dp_dut/N239 ));
   OAI21X1 \dp_dut/U279  (.Y(\dp_dut/n426 ),
	.C(\dp_dut/n300 ),
	.B(n168),
	.A(n86));
   AOI21X1 \dp_dut/U278  (.Y(\dp_dut/n299 ),
	.C(\dp_dut/n234 ),
	.B(n1),
	.A(\dp_dut/N240 ));
   OAI21X1 \dp_dut/U277  (.Y(\dp_dut/n425 ),
	.C(\dp_dut/n299 ),
	.B(n167),
	.A(n86));
   NAND2X1 \dp_dut/U276  (.Y(\dp_dut/n298 ),
	.B(n1),
	.A(\dp_dut/N241 ));
   OAI21X1 \dp_dut/U275  (.Y(\dp_dut/n424 ),
	.C(\dp_dut/n298 ),
	.B(n166),
	.A(n86));
   NAND2X1 \dp_dut/U274  (.Y(\dp_dut/n297 ),
	.B(n1),
	.A(\dp_dut/N242 ));
   OAI21X1 \dp_dut/U273  (.Y(\dp_dut/n423 ),
	.C(\dp_dut/n297 ),
	.B(n165),
	.A(n86));
   NAND2X1 \dp_dut/U272  (.Y(\dp_dut/n296 ),
	.B(n1),
	.A(\dp_dut/N243 ));
   OAI21X1 \dp_dut/U271  (.Y(\dp_dut/n422 ),
	.C(\dp_dut/n296 ),
	.B(n164),
	.A(n86));
   NAND2X1 \dp_dut/U270  (.Y(\dp_dut/n294 ),
	.B(n1),
	.A(\dp_dut/N244 ));
   OAI21X1 \dp_dut/U269  (.Y(\dp_dut/n421 ),
	.C(\dp_dut/n294 ),
	.B(n163),
	.A(n86));
   AOI21X1 \dp_dut/U268  (.Y(\dp_dut/n285 ),
	.C(n72),
	.B(n106),
	.A(\dp_dut/n293 ));
   NOR2X1 \dp_dut/U267  (.Y(\dp_dut/n292 ),
	.B(\dp_dut/item_d_num [6]),
	.A(\dp_dut/item_d_num [7]));
   NAND3X1 \dp_dut/U266  (.Y(\dp_dut/n289 ),
	.C(\dp_dut/n292 ),
	.B(n164),
	.A(n165));
   NOR2X1 \dp_dut/U265  (.Y(\dp_dut/n291 ),
	.B(\dp_dut/item_d_num [2]),
	.A(\dp_dut/item_d_num [3]));
   NAND3X1 \dp_dut/U264  (.Y(\dp_dut/n290 ),
	.C(\dp_dut/n291 ),
	.B(n168),
	.A(n169));
   OR2X1 \dp_dut/U263  (.Y(out_stock_d),
	.B(\dp_dut/n290 ),
	.A(\dp_dut/n289 ));
   NOR2X1 \dp_dut/U262  (.Y(\dp_dut/n287 ),
	.B(n106),
	.A(\dp_dut/n288 ));
   NAND3X1 \dp_dut/U261  (.Y(\dp_dut/n286 ),
	.C(\dp_dut/n287 ),
	.B(n170),
	.A(out_stock_d));
   OAI21X1 \dp_dut/U260  (.Y(\dp_dut/n420 ),
	.C(\dp_dut/n286 ),
	.B(n170),
	.A(\dp_dut/n285 ));
   NOR2X1 \dp_dut/U259  (.Y(\dp_dut/n280 ),
	.B(n83),
	.A(\dp_dut/n284 ));
   OR2X1 \dp_dut/U258  (.Y(\dp_dut/n278 ),
	.B(n99),
	.A(\dp_dut/n280 ));
   NAND2X1 \dp_dut/U257  (.Y(\dp_dut/n283 ),
	.B(\dp_dut/n280 ),
	.A(out_spit_a));
   OAI21X1 \dp_dut/U256  (.Y(\dp_dut/n419 ),
	.C(\dp_dut/n283 ),
	.B(n188),
	.A(\dp_dut/n278 ));
   NAND2X1 \dp_dut/U255  (.Y(\dp_dut/n282 ),
	.B(\dp_dut/n280 ),
	.A(out_spit_b));
   OAI21X1 \dp_dut/U254  (.Y(\dp_dut/n418 ),
	.C(\dp_dut/n282 ),
	.B(n217),
	.A(\dp_dut/n278 ));
   NAND2X1 \dp_dut/U253  (.Y(\dp_dut/n281 ),
	.B(\dp_dut/n280 ),
	.A(out_spit_c));
   OAI21X1 \dp_dut/U252  (.Y(\dp_dut/n417 ),
	.C(\dp_dut/n281 ),
	.B(n179),
	.A(\dp_dut/n278 ));
   NAND2X1 \dp_dut/U251  (.Y(\dp_dut/n279 ),
	.B(\dp_dut/n280 ),
	.A(out_spit_d));
   OAI21X1 \dp_dut/U250  (.Y(\dp_dut/n416 ),
	.C(\dp_dut/n279 ),
	.B(n170),
	.A(\dp_dut/n278 ));
   AOI22X1 \dp_dut/U249  (.Y(\dp_dut/n269 ),
	.D(n74),
	.C(\dp_dut/dollar_1_num [0]),
	.B(n85),
	.A(\dp_dut/N333 ));
   NAND2X1 \dp_dut/U248  (.Y(\dp_dut/n225 ),
	.B(\dp_dut/n203 ),
	.A(out_change[3]));
   NOR2X1 \dp_dut/U247  (.Y(\dp_dut/n273 ),
	.B(\dp_dut/N293 ),
	.A(\dp_dut/N294 ));
   NOR2X1 \dp_dut/U246  (.Y(\dp_dut/n274 ),
	.B(\dp_dut/N295 ),
	.A(\dp_dut/N296 ));
   NOR2X1 \dp_dut/U245  (.Y(\dp_dut/n276 ),
	.B(\dp_dut/N297 ),
	.A(\dp_dut/N298 ));
   NOR2X1 \dp_dut/U244  (.Y(\dp_dut/n277 ),
	.B(\dp_dut/N299 ),
	.A(\dp_dut/N300 ));
   NAND3X1 \dp_dut/U243  (.Y(\dp_dut/n272 ),
	.C(\dp_dut/n275 ),
	.B(\dp_dut/n274 ),
	.A(\dp_dut/n273 ));
   NAND2X1 \dp_dut/U242  (.Y(\dp_dut/n248 ),
	.B(\dp_dut/n272 ),
	.A(n70));
   NAND2X1 \dp_dut/U241  (.Y(\dp_dut/n249 ),
	.B(n70),
	.A(n110));
   OAI22X1 \dp_dut/U240  (.Y(\dp_dut/n271 ),
	.D(\dp_dut/n249 ),
	.C(n200),
	.B(\dp_dut/n248 ),
	.A(\dp_dut/n225 ));
   AOI21X1 \dp_dut/U239  (.Y(\dp_dut/n270 ),
	.C(\dp_dut/n271 ),
	.B(n83),
	.A(\dp_dut/N171 ));
   NAND2X1 \dp_dut/U238  (.Y(\dp_dut/n415 ),
	.B(\dp_dut/n270 ),
	.A(\dp_dut/n269 ));
   AOI22X1 \dp_dut/U237  (.Y(\dp_dut/n265 ),
	.D(n84),
	.C(\dp_dut/N334 ),
	.B(n83),
	.A(\dp_dut/N172 ));
   NAND2X1 \dp_dut/U236  (.Y(\dp_dut/n266 ),
	.B(n74),
	.A(\dp_dut/dollar_1_num [1]));
   OAI21X1 \dp_dut/U235  (.Y(\dp_dut/n268 ),
	.C(n102),
	.B(\dp_dut/n249 ),
	.A(n199));
   AOI21X1 \dp_dut/U234  (.Y(\dp_dut/n267 ),
	.C(\dp_dut/n268 ),
	.B(\dp_dut/out_change_1_sol1[1] ),
	.A(n101));
   NAND3X1 \dp_dut/U233  (.Y(\dp_dut/n414 ),
	.C(\dp_dut/n267 ),
	.B(\dp_dut/n266 ),
	.A(\dp_dut/n265 ));
   AOI22X1 \dp_dut/U232  (.Y(\dp_dut/n262 ),
	.D(n74),
	.C(\dp_dut/dollar_1_num [2]),
	.B(n85),
	.A(\dp_dut/N335 ));
   NAND2X1 \dp_dut/U231  (.Y(\dp_dut/n222 ),
	.B(\dp_dut/n203 ),
	.A(out_change[5]));
   OAI22X1 \dp_dut/U230  (.Y(\dp_dut/n264 ),
	.D(\dp_dut/n249 ),
	.C(n198),
	.B(\dp_dut/n248 ),
	.A(\dp_dut/n222 ));
   AOI21X1 \dp_dut/U229  (.Y(\dp_dut/n263 ),
	.C(\dp_dut/n264 ),
	.B(n83),
	.A(\dp_dut/N173 ));
   NAND2X1 \dp_dut/U228  (.Y(\dp_dut/n413 ),
	.B(\dp_dut/n263 ),
	.A(\dp_dut/n262 ));
   AOI22X1 \dp_dut/U227  (.Y(\dp_dut/n259 ),
	.D(n74),
	.C(\dp_dut/dollar_1_num [3]),
	.B(n84),
	.A(\dp_dut/N336 ));
   NAND2X1 \dp_dut/U226  (.Y(\dp_dut/n220 ),
	.B(\dp_dut/n203 ),
	.A(out_change[6]));
   OAI22X1 \dp_dut/U225  (.Y(\dp_dut/n261 ),
	.D(\dp_dut/n249 ),
	.C(n197),
	.B(\dp_dut/n248 ),
	.A(\dp_dut/n220 ));
   AOI21X1 \dp_dut/U224  (.Y(\dp_dut/n260 ),
	.C(\dp_dut/n261 ),
	.B(n83),
	.A(\dp_dut/N174 ));
   NAND2X1 \dp_dut/U223  (.Y(\dp_dut/n412 ),
	.B(\dp_dut/n260 ),
	.A(\dp_dut/n259 ));
   AOI22X1 \dp_dut/U222  (.Y(\dp_dut/n256 ),
	.D(n74),
	.C(\dp_dut/dollar_1_num [4]),
	.B(n85),
	.A(\dp_dut/N337 ));
   NAND2X1 \dp_dut/U221  (.Y(\dp_dut/n218 ),
	.B(\dp_dut/n203 ),
	.A(out_change[7]));
   OAI22X1 \dp_dut/U220  (.Y(\dp_dut/n258 ),
	.D(\dp_dut/n249 ),
	.C(n196),
	.B(\dp_dut/n248 ),
	.A(\dp_dut/n218 ));
   AOI21X1 \dp_dut/U219  (.Y(\dp_dut/n257 ),
	.C(\dp_dut/n258 ),
	.B(n83),
	.A(\dp_dut/N175 ));
   NAND2X1 \dp_dut/U218  (.Y(\dp_dut/n411 ),
	.B(\dp_dut/n257 ),
	.A(\dp_dut/n256 ));
   AOI22X1 \dp_dut/U217  (.Y(\dp_dut/n253 ),
	.D(n74),
	.C(\dp_dut/dollar_1_num [5]),
	.B(n84),
	.A(\dp_dut/N338 ));
   NAND2X1 \dp_dut/U216  (.Y(\dp_dut/n216 ),
	.B(\dp_dut/n203 ),
	.A(out_change[8]));
   OAI22X1 \dp_dut/U215  (.Y(\dp_dut/n255 ),
	.D(\dp_dut/n249 ),
	.C(n195),
	.B(\dp_dut/n248 ),
	.A(\dp_dut/n216 ));
   AOI21X1 \dp_dut/U214  (.Y(\dp_dut/n254 ),
	.C(\dp_dut/n255 ),
	.B(n83),
	.A(\dp_dut/N176 ));
   NAND2X1 \dp_dut/U213  (.Y(\dp_dut/n410 ),
	.B(\dp_dut/n254 ),
	.A(\dp_dut/n253 ));
   AOI22X1 \dp_dut/U212  (.Y(\dp_dut/n250 ),
	.D(n74),
	.C(\dp_dut/dollar_1_num [6]),
	.B(n85),
	.A(\dp_dut/N339 ));
   NAND2X1 \dp_dut/U211  (.Y(\dp_dut/n214 ),
	.B(\dp_dut/n203 ),
	.A(out_change[9]));
   OAI22X1 \dp_dut/U210  (.Y(\dp_dut/n252 ),
	.D(\dp_dut/n249 ),
	.C(n193),
	.B(\dp_dut/n248 ),
	.A(\dp_dut/n214 ));
   AOI21X1 \dp_dut/U209  (.Y(\dp_dut/n251 ),
	.C(\dp_dut/n252 ),
	.B(n83),
	.A(\dp_dut/N177 ));
   NAND2X1 \dp_dut/U208  (.Y(\dp_dut/n409 ),
	.B(\dp_dut/n251 ),
	.A(\dp_dut/n250 ));
   AOI22X1 \dp_dut/U207  (.Y(\dp_dut/n245 ),
	.D(n74),
	.C(\dp_dut/dollar_1_num [7]),
	.B(n84),
	.A(\dp_dut/N340 ));
   NAND2X1 \dp_dut/U206  (.Y(\dp_dut/n212 ),
	.B(\dp_dut/n203 ),
	.A(out_change[10]));
   OAI22X1 \dp_dut/U205  (.Y(\dp_dut/n247 ),
	.D(\dp_dut/n249 ),
	.C(n192),
	.B(\dp_dut/n248 ),
	.A(\dp_dut/n212 ));
   AOI21X1 \dp_dut/U204  (.Y(\dp_dut/n246 ),
	.C(\dp_dut/n247 ),
	.B(n83),
	.A(\dp_dut/N178 ));
   NAND2X1 \dp_dut/U203  (.Y(\dp_dut/n408 ),
	.B(\dp_dut/n246 ),
	.A(\dp_dut/n245 ));
   AOI22X1 \dp_dut/U202  (.Y(\dp_dut/n236 ),
	.D(n74),
	.C(\dp_dut/dollar_05_num [0]),
	.B(n85),
	.A(\dp_dut/N341 ));
   NOR2X1 \dp_dut/U201  (.Y(\dp_dut/n240 ),
	.B(\dp_dut/N311 ),
	.A(\dp_dut/N312 ));
   NOR2X1 \dp_dut/U200  (.Y(\dp_dut/n241 ),
	.B(\dp_dut/N313 ),
	.A(\dp_dut/N314 ));
   NOR2X1 \dp_dut/U199  (.Y(\dp_dut/n243 ),
	.B(\dp_dut/N315 ),
	.A(\dp_dut/N316 ));
   NOR2X1 \dp_dut/U198  (.Y(\dp_dut/n244 ),
	.B(\dp_dut/N317 ),
	.A(\dp_dut/N318 ));
   NAND3X1 \dp_dut/U197  (.Y(\dp_dut/n239 ),
	.C(\dp_dut/n242 ),
	.B(\dp_dut/n241 ),
	.A(\dp_dut/n240 ));
   NAND2X1 \dp_dut/U196  (.Y(\dp_dut/n208 ),
	.B(\dp_dut/n203 ),
	.A(out_change[2]));
   OAI22X1 \dp_dut/U195  (.Y(\dp_dut/n238 ),
	.D(\dp_dut/n239 ),
	.C(n201),
	.B(\dp_dut/n208 ),
	.A(n108));
   AOI22X1 \dp_dut/U194  (.Y(\dp_dut/n237 ),
	.D(n83),
	.C(\dp_dut/N179 ),
	.B(\dp_dut/n238 ),
	.A(n70));
   NAND2X1 \dp_dut/U193  (.Y(\dp_dut/n407 ),
	.B(\dp_dut/n237 ),
	.A(\dp_dut/n236 ));
   AOI22X1 \dp_dut/U192  (.Y(\dp_dut/n232 ),
	.D(n74),
	.C(\dp_dut/dollar_05_num [1]),
	.B(n84),
	.A(\dp_dut/N342 ));
   AOI21X1 \dp_dut/U191  (.Y(\dp_dut/n233 ),
	.C(\dp_dut/n234 ),
	.B(n83),
	.A(\dp_dut/N180 ));
   NAND2X1 \dp_dut/U190  (.Y(\dp_dut/n406 ),
	.B(\dp_dut/n233 ),
	.A(\dp_dut/n232 ));
   AOI22X1 \dp_dut/U189  (.Y(\dp_dut/n231 ),
	.D(n85),
	.C(\dp_dut/N343 ),
	.B(n83),
	.A(\dp_dut/N181 ));
   OAI21X1 \dp_dut/U188  (.Y(\dp_dut/n405 ),
	.C(\dp_dut/n231 ),
	.B(n141),
	.A(n2));
   AOI22X1 \dp_dut/U187  (.Y(\dp_dut/n230 ),
	.D(n85),
	.C(\dp_dut/N344 ),
	.B(n83),
	.A(\dp_dut/N182 ));
   OAI21X1 \dp_dut/U186  (.Y(\dp_dut/n404 ),
	.C(\dp_dut/n230 ),
	.B(n140),
	.A(n2));
   AOI22X1 \dp_dut/U185  (.Y(\dp_dut/n229 ),
	.D(n85),
	.C(\dp_dut/N345 ),
	.B(n83),
	.A(\dp_dut/N183 ));
   OAI21X1 \dp_dut/U184  (.Y(\dp_dut/n403 ),
	.C(\dp_dut/n229 ),
	.B(n139),
	.A(n2));
   AOI22X1 \dp_dut/U183  (.Y(\dp_dut/n228 ),
	.D(n85),
	.C(\dp_dut/N346 ),
	.B(n83),
	.A(\dp_dut/N184 ));
   OAI21X1 \dp_dut/U182  (.Y(\dp_dut/n402 ),
	.C(\dp_dut/n228 ),
	.B(n138),
	.A(n2));
   AOI22X1 \dp_dut/U181  (.Y(\dp_dut/n227 ),
	.D(n85),
	.C(\dp_dut/N347 ),
	.B(n83),
	.A(\dp_dut/N185 ));
   OAI21X1 \dp_dut/U180  (.Y(\dp_dut/n401 ),
	.C(\dp_dut/n227 ),
	.B(n137),
	.A(n2));
   AOI22X1 \dp_dut/U179  (.Y(\dp_dut/n226 ),
	.D(n85),
	.C(\dp_dut/N348 ),
	.B(n83),
	.A(\dp_dut/N186 ));
   OAI21X1 \dp_dut/U178  (.Y(\dp_dut/n400 ),
	.C(\dp_dut/n226 ),
	.B(n142),
	.A(n2));
   AOI22X1 \dp_dut/U177  (.Y(\dp_dut/n224 ),
	.D(n85),
	.C(\dp_dut/inserted_money [3]),
	.B(n70),
	.A(n114));
   OAI21X1 \dp_dut/U176  (.Y(\dp_dut/n399 ),
	.C(\dp_dut/n224 ),
	.B(n154),
	.A(\dp_dut/n204 ));
   AOI22X1 \dp_dut/U175  (.Y(\dp_dut/n223 ),
	.D(n85),
	.C(\dp_dut/inserted_money [4]),
	.B(n70),
	.A(\dp_dut/out_change_1_sol1[1] ));
   OAI21X1 \dp_dut/U174  (.Y(\dp_dut/n398 ),
	.C(\dp_dut/n223 ),
	.B(n136),
	.A(\dp_dut/n204 ));
   AOI22X1 \dp_dut/U173  (.Y(\dp_dut/n221 ),
	.D(n84),
	.C(\dp_dut/inserted_money [5]),
	.B(n70),
	.A(n116));
   OAI21X1 \dp_dut/U172  (.Y(\dp_dut/n397 ),
	.C(\dp_dut/n221 ),
	.B(n155),
	.A(\dp_dut/n204 ));
   AOI22X1 \dp_dut/U171  (.Y(\dp_dut/n219 ),
	.D(n85),
	.C(\dp_dut/inserted_money [6]),
	.B(n70),
	.A(n117));
   OAI21X1 \dp_dut/U170  (.Y(\dp_dut/n396 ),
	.C(\dp_dut/n219 ),
	.B(n156),
	.A(\dp_dut/n204 ));
   AOI22X1 \dp_dut/U169  (.Y(\dp_dut/n217 ),
	.D(n85),
	.C(\dp_dut/inserted_money [7]),
	.B(n70),
	.A(n119));
   OAI21X1 \dp_dut/U168  (.Y(\dp_dut/n395 ),
	.C(\dp_dut/n217 ),
	.B(n157),
	.A(\dp_dut/n204 ));
   AOI22X1 \dp_dut/U167  (.Y(\dp_dut/n215 ),
	.D(n85),
	.C(\dp_dut/inserted_money [8]),
	.B(n70),
	.A(n120));
   OAI21X1 \dp_dut/U166  (.Y(\dp_dut/n394 ),
	.C(\dp_dut/n215 ),
	.B(n158),
	.A(\dp_dut/n204 ));
   AOI22X1 \dp_dut/U165  (.Y(\dp_dut/n213 ),
	.D(n84),
	.C(\dp_dut/inserted_money [9]),
	.B(n70),
	.A(n122));
   OAI21X1 \dp_dut/U164  (.Y(\dp_dut/n393 ),
	.C(\dp_dut/n213 ),
	.B(n159),
	.A(\dp_dut/n204 ));
   AOI22X1 \dp_dut/U163  (.Y(\dp_dut/n211 ),
	.D(n84),
	.C(\dp_dut/inserted_money [10]),
	.B(n70),
	.A(n123));
   OAI21X1 \dp_dut/U162  (.Y(\dp_dut/n392 ),
	.C(\dp_dut/n211 ),
	.B(n160),
	.A(\dp_dut/n204 ));
   AOI22X1 \dp_dut/U161  (.Y(\dp_dut/n209 ),
	.D(n84),
	.C(\dp_dut/inserted_money [1]),
	.B(n70),
	.A(n112));
   OAI21X1 \dp_dut/U160  (.Y(\dp_dut/n391 ),
	.C(\dp_dut/n209 ),
	.B(n161),
	.A(\dp_dut/n204 ));
   AOI22X1 \dp_dut/U159  (.Y(\dp_dut/n205 ),
	.D(n84),
	.C(\dp_dut/inserted_money [2]),
	.B(n70),
	.A(n124));
   OAI21X1 \dp_dut/U158  (.Y(\dp_dut/n390 ),
	.C(\dp_dut/n205 ),
	.B(n135),
	.A(\dp_dut/n204 ));
   AND2X2 \dp_dut/U53  (.Y(\dp_dut/n293 ),
	.B(cmd[1]),
	.A(cmd[0]));
   AND2X2 \dp_dut/U52  (.Y(\dp_dut/n376 ),
	.B(\dp_dut/n378 ),
	.A(\dp_dut/n377 ));
   AND2X2 \dp_dut/U51  (.Y(out_change[1]),
	.B(n77),
	.A(\dp_dut/N45 ));
   AND2X2 \dp_dut/U49  (.Y(out_change[3]),
	.B(n78),
	.A(\dp_dut/N47 ));
   AND2X2 \dp_dut/U48  (.Y(\dp_dut/n275 ),
	.B(\dp_dut/n277 ),
	.A(\dp_dut/n276 ));
   AND2X2 \dp_dut/U47  (.Y(out_change[4]),
	.B(n79),
	.A(\dp_dut/N48 ));
   AND2X2 \dp_dut/U46  (.Y(\dp_dut/out_change_1_sol1[1] ),
	.B(\dp_dut/n203 ),
	.A(out_change[4]));
   AND2X2 \dp_dut/U45  (.Y(out_change[5]),
	.B(n81),
	.A(\dp_dut/N49 ));
   AND2X2 \dp_dut/U44  (.Y(out_change[6]),
	.B(n77),
	.A(\dp_dut/N50 ));
   AND2X2 \dp_dut/U43  (.Y(out_change[7]),
	.B(n79),
	.A(\dp_dut/N51 ));
   AND2X2 \dp_dut/U42  (.Y(out_change[8]),
	.B(n79),
	.A(\dp_dut/N52 ));
   AND2X2 \dp_dut/U41  (.Y(out_change[9]),
	.B(n80),
	.A(\dp_dut/N53 ));
   AND2X2 \dp_dut/U40  (.Y(out_change[10]),
	.B(n80),
	.A(\dp_dut/N54 ));
   AND2X2 \dp_dut/U39  (.Y(\dp_dut/n242 ),
	.B(\dp_dut/n244 ),
	.A(\dp_dut/n243 ));
   AND2X2 \dp_dut/U15  (.Y(out_change[2]),
	.B(n82),
	.A(\dp_dut/N46 ));
   AND2X2 \dp_dut/U14  (.Y(out_change[0]),
	.B(n78),
	.A(\dp_dut/N155 ));
   AND2X2 \dp_dut/U13  (.Y(out_change[11]),
	.B(n80),
	.A(\dp_dut/N55 ));
   AND2X2 \dp_dut/U12  (.Y(out_change[12]),
	.B(n81),
	.A(\dp_dut/N56 ));
   AND2X2 \dp_dut/U11  (.Y(out_change[13]),
	.B(n82),
	.A(\dp_dut/N57 ));
   AND2X2 \dp_dut/U10  (.Y(out_change[14]),
	.B(n81),
	.A(\dp_dut/N58 ));
   AND2X2 \dp_dut/U8  (.Y(\dp_dut/total_price [1]),
	.B(n77),
	.A(\dp_dut/N38 ));
   AND2X2 \dp_dut/U7  (.Y(\dp_dut/total_price [2]),
	.B(n79),
	.A(\dp_dut/N39 ));
   AND2X2 \dp_dut/U5  (.Y(\dp_dut/total_price [4]),
	.B(n77),
	.A(\dp_dut/N41 ));
   AND2X2 \dp_dut/U4  (.Y(\dp_dut/total_price [5]),
	.B(n78),
	.A(\dp_dut/N42 ));
   DFFNEGX1 \dp_dut/out_change_05_reg  (.Q(out_change_05),
	.D(\dp_dut/n390 ),
	.CLK(n97));
   DFFNEGX1 \dp_dut/out_spit_b_reg  (.Q(out_spit_b),
	.D(\dp_dut/n418 ),
	.CLK(n97));
   DFFNEGX1 \dp_dut/out_change_1_reg[1]  (.Q(out_change_1[1]),
	.D(\dp_dut/n398 ),
	.CLK(n97));
   DFFNEGX1 \dp_dut/dollar_05_num_reg[6]  (.Q(\dp_dut/dollar_05_num [6]),
	.D(\dp_dut/n401 ),
	.CLK(n97));
   DFFNEGX1 \dp_dut/dollar_05_num_reg[5]  (.Q(\dp_dut/dollar_05_num [5]),
	.D(\dp_dut/n402 ),
	.CLK(n97));
   DFFNEGX1 \dp_dut/dollar_05_num_reg[4]  (.Q(\dp_dut/dollar_05_num [4]),
	.D(\dp_dut/n403 ),
	.CLK(n97));
   DFFNEGX1 \dp_dut/dollar_05_num_reg[3]  (.Q(\dp_dut/dollar_05_num [3]),
	.D(\dp_dut/n404 ),
	.CLK(n97));
   DFFNEGX1 \dp_dut/dollar_05_num_reg[2]  (.Q(\dp_dut/dollar_05_num [2]),
	.D(\dp_dut/n405 ),
	.CLK(n97));
   DFFNEGX1 \dp_dut/dollar_05_num_reg[1]  (.Q(\dp_dut/dollar_05_num [1]),
	.D(\dp_dut/n406 ),
	.CLK(n97));
   DFFNEGX1 \dp_dut/dollar_05_num_reg[7]  (.Q(\dp_dut/dollar_05_num [7]),
	.D(\dp_dut/n400 ),
	.CLK(n97));
   DFFNEGX1 \dp_dut/dollar_05_num_reg[0]  (.Q(\dp_dut/dollar_05_num [0]),
	.D(\dp_dut/n407 ),
	.CLK(n97));
   DFFNEGX1 \dp_dut/dollar_025_num_reg[6]  (.Q(\dp_dut/dollar_025_num [6]),
	.D(\dp_dut/n471 ),
	.CLK(n97));
   DFFNEGX1 \dp_dut/dollar_025_num_reg[5]  (.Q(\dp_dut/dollar_025_num [5]),
	.D(\dp_dut/n472 ),
	.CLK(n96));
   DFFNEGX1 \dp_dut/dollar_025_num_reg[4]  (.Q(\dp_dut/dollar_025_num [4]),
	.D(\dp_dut/n473 ),
	.CLK(n96));
   DFFNEGX1 \dp_dut/dollar_025_num_reg[3]  (.Q(\dp_dut/dollar_025_num [3]),
	.D(\dp_dut/n474 ),
	.CLK(n96));
   DFFNEGX1 \dp_dut/dollar_025_num_reg[2]  (.Q(\dp_dut/dollar_025_num [2]),
	.D(\dp_dut/n475 ),
	.CLK(n96));
   DFFNEGX1 \dp_dut/dollar_025_num_reg[1]  (.Q(\dp_dut/dollar_025_num [1]),
	.D(\dp_dut/n476 ),
	.CLK(n96));
   DFFNEGX1 \dp_dut/dollar_025_num_reg[7]  (.Q(\dp_dut/dollar_025_num [7]),
	.D(\dp_dut/n470 ),
	.CLK(n96));
   DFFNEGX1 \dp_dut/dollar_025_num_reg[0]  (.Q(\dp_dut/dollar_025_num [0]),
	.D(\dp_dut/n477 ),
	.CLK(n96));
   DFFNEGX1 \dp_dut/dollar_1_num_reg[2]  (.Q(\dp_dut/dollar_1_num [2]),
	.D(\dp_dut/n413 ),
	.CLK(n96));
   DFFNEGX1 \dp_dut/dollar_1_num_reg[3]  (.Q(\dp_dut/dollar_1_num [3]),
	.D(\dp_dut/n412 ),
	.CLK(n96));
   DFFNEGX1 \dp_dut/dollar_1_num_reg[4]  (.Q(\dp_dut/dollar_1_num [4]),
	.D(\dp_dut/n411 ),
	.CLK(n96));
   DFFNEGX1 \dp_dut/dollar_1_num_reg[5]  (.Q(\dp_dut/dollar_1_num [5]),
	.D(\dp_dut/n410 ),
	.CLK(n96));
   DFFNEGX1 \dp_dut/out_change_1_reg[0]  (.Q(out_change_1[0]),
	.D(\dp_dut/n399 ),
	.CLK(n96));
   DFFNEGX1 \dp_dut/out_change_1_reg[2]  (.Q(out_change_1[2]),
	.D(\dp_dut/n397 ),
	.CLK(n96));
   DFFNEGX1 \dp_dut/out_change_1_reg[3]  (.Q(out_change_1[3]),
	.D(\dp_dut/n396 ),
	.CLK(n95));
   DFFNEGX1 \dp_dut/out_change_1_reg[4]  (.Q(out_change_1[4]),
	.D(\dp_dut/n395 ),
	.CLK(n95));
   DFFNEGX1 \dp_dut/out_change_1_reg[5]  (.Q(out_change_1[5]),
	.D(\dp_dut/n394 ),
	.CLK(n95));
   DFFNEGX1 \dp_dut/out_change_1_reg[6]  (.Q(out_change_1[6]),
	.D(\dp_dut/n393 ),
	.CLK(n95));
   DFFNEGX1 \dp_dut/out_change_1_reg[7]  (.Q(out_change_1[7]),
	.D(\dp_dut/n392 ),
	.CLK(n95));
   DFFNEGX1 \dp_dut/out_change_025_reg  (.Q(out_change_025),
	.D(\dp_dut/n391 ),
	.CLK(n95));
   DFFNEGX1 \dp_dut/out_spit_d_reg  (.Q(out_spit_d),
	.D(\dp_dut/n416 ),
	.CLK(n95));
   DFFNEGX1 \dp_dut/item_d_num_reg[7]  (.Q(\dp_dut/item_d_num [7]),
	.D(\dp_dut/n428 ),
	.CLK(n95));
   DFFNEGX1 \dp_dut/item_d_num_reg[6]  (.Q(\dp_dut/item_d_num [6]),
	.D(\dp_dut/n421 ),
	.CLK(n95));
   DFFNEGX1 \dp_dut/item_d_num_reg[5]  (.Q(\dp_dut/item_d_num [5]),
	.D(\dp_dut/n422 ),
	.CLK(n95));
   DFFNEGX1 \dp_dut/item_d_num_reg[4]  (.Q(\dp_dut/item_d_num [4]),
	.D(\dp_dut/n423 ),
	.CLK(n95));
   DFFNEGX1 \dp_dut/item_d_num_reg[3]  (.Q(\dp_dut/item_d_num [3]),
	.D(\dp_dut/n424 ),
	.CLK(n95));
   DFFNEGX1 \dp_dut/item_d_num_reg[2]  (.Q(\dp_dut/item_d_num [2]),
	.D(\dp_dut/n425 ),
	.CLK(n95));
   DFFNEGX1 \dp_dut/item_d_num_reg[1]  (.Q(\dp_dut/item_d_num [1]),
	.D(\dp_dut/n426 ),
	.CLK(n94));
   DFFNEGX1 \dp_dut/item_d_num_reg[0]  (.Q(\dp_dut/item_d_num [0]),
	.D(\dp_dut/n427 ),
	.CLK(n94));
   DFFNEGX1 \dp_dut/out_csel_d_reg  (.Q(out_csel_d),
	.D(\dp_dut/n420 ),
	.CLK(n94));
   DFFNEGX1 \dp_dut/out_spit_c_reg  (.Q(out_spit_c),
	.D(\dp_dut/n417 ),
	.CLK(n94));
   DFFNEGX1 \dp_dut/item_c_num_reg[7]  (.Q(\dp_dut/item_c_num [7]),
	.D(\dp_dut/n437 ),
	.CLK(n94));
   DFFNEGX1 \dp_dut/item_c_num_reg[6]  (.Q(\dp_dut/item_c_num [6]),
	.D(\dp_dut/n430 ),
	.CLK(n94));
   DFFNEGX1 \dp_dut/item_c_num_reg[5]  (.Q(\dp_dut/item_c_num [5]),
	.D(\dp_dut/n431 ),
	.CLK(n94));
   DFFNEGX1 \dp_dut/item_c_num_reg[4]  (.Q(\dp_dut/item_c_num [4]),
	.D(\dp_dut/n432 ),
	.CLK(n94));
   DFFNEGX1 \dp_dut/item_c_num_reg[3]  (.Q(\dp_dut/item_c_num [3]),
	.D(\dp_dut/n433 ),
	.CLK(n94));
   DFFNEGX1 \dp_dut/item_c_num_reg[2]  (.Q(\dp_dut/item_c_num [2]),
	.D(\dp_dut/n434 ),
	.CLK(n94));
   DFFNEGX1 \dp_dut/item_c_num_reg[1]  (.Q(\dp_dut/item_c_num [1]),
	.D(\dp_dut/n435 ),
	.CLK(n94));
   DFFNEGX1 \dp_dut/item_c_num_reg[0]  (.Q(\dp_dut/item_c_num [0]),
	.D(\dp_dut/n436 ),
	.CLK(n94));
   DFFNEGX1 \dp_dut/out_csel_c_reg  (.Q(out_csel_c),
	.D(\dp_dut/n429 ),
	.CLK(n94));
   DFFNEGX1 \dp_dut/out_spit_a_reg  (.Q(out_spit_a),
	.D(\dp_dut/n419 ),
	.CLK(n93));
   DFFNEGX1 \dp_dut/item_a_num_reg[7]  (.Q(\dp_dut/item_a_num [7]),
	.D(\dp_dut/n454 ),
	.CLK(n93));
   DFFNEGX1 \dp_dut/item_a_num_reg[6]  (.Q(\dp_dut/item_a_num [6]),
	.D(\dp_dut/n447 ),
	.CLK(n93));
   DFFNEGX1 \dp_dut/item_a_num_reg[5]  (.Q(\dp_dut/item_a_num [5]),
	.D(\dp_dut/n448 ),
	.CLK(n93));
   DFFNEGX1 \dp_dut/item_a_num_reg[4]  (.Q(\dp_dut/item_a_num [4]),
	.D(\dp_dut/n449 ),
	.CLK(n93));
   DFFNEGX1 \dp_dut/item_a_num_reg[3]  (.Q(\dp_dut/item_a_num [3]),
	.D(\dp_dut/n450 ),
	.CLK(n93));
   DFFNEGX1 \dp_dut/item_a_num_reg[2]  (.Q(\dp_dut/item_a_num [2]),
	.D(\dp_dut/n451 ),
	.CLK(n93));
   DFFNEGX1 \dp_dut/item_a_num_reg[1]  (.Q(\dp_dut/item_a_num [1]),
	.D(\dp_dut/n452 ),
	.CLK(n93));
   DFFNEGX1 \dp_dut/item_a_num_reg[0]  (.Q(\dp_dut/item_a_num [0]),
	.D(\dp_dut/n453 ),
	.CLK(n93));
   DFFNEGX1 \dp_dut/out_csel_a_reg  (.Q(out_csel_a),
	.D(\dp_dut/n446 ),
	.CLK(n93));
   DFFNEGX1 \dp_dut/inserted_money_reg[13]  (.Q(\dp_dut/inserted_money [13]),
	.D(\dp_dut/n468 ),
	.CLK(n93));
   DFFNEGX1 \dp_dut/inserted_money_reg[12]  (.Q(\dp_dut/inserted_money [12]),
	.D(\dp_dut/n467 ),
	.CLK(n93));
   DFFNEGX1 \dp_dut/inserted_money_reg[11]  (.Q(\dp_dut/inserted_money [11]),
	.D(\dp_dut/n466 ),
	.CLK(n93));
   DFFNEGX1 \dp_dut/inserted_money_reg[10]  (.Q(\dp_dut/inserted_money [10]),
	.D(\dp_dut/n465 ),
	.CLK(n92));
   DFFNEGX1 \dp_dut/inserted_money_reg[9]  (.Q(\dp_dut/inserted_money [9]),
	.D(\dp_dut/n464 ),
	.CLK(n92));
   DFFNEGX1 \dp_dut/inserted_money_reg[8]  (.Q(\dp_dut/inserted_money [8]),
	.D(\dp_dut/n463 ),
	.CLK(n92));
   DFFNEGX1 \dp_dut/inserted_money_reg[7]  (.Q(\dp_dut/inserted_money [7]),
	.D(\dp_dut/n462 ),
	.CLK(n92));
   DFFNEGX1 \dp_dut/inserted_money_reg[6]  (.Q(\dp_dut/inserted_money [6]),
	.D(\dp_dut/n461 ),
	.CLK(n92));
   DFFNEGX1 \dp_dut/inserted_money_reg[5]  (.Q(\dp_dut/inserted_money [5]),
	.D(\dp_dut/n460 ),
	.CLK(n92));
   DFFNEGX1 \dp_dut/inserted_money_reg[4]  (.Q(\dp_dut/inserted_money [4]),
	.D(\dp_dut/n459 ),
	.CLK(n92));
   DFFNEGX1 \dp_dut/inserted_money_reg[3]  (.Q(\dp_dut/inserted_money [3]),
	.D(\dp_dut/n458 ),
	.CLK(n92));
   DFFNEGX1 \dp_dut/inserted_money_reg[2]  (.Q(\dp_dut/inserted_money [2]),
	.D(\dp_dut/n457 ),
	.CLK(n92));
   DFFNEGX1 \dp_dut/inserted_money_reg[1]  (.Q(\dp_dut/inserted_money [1]),
	.D(\dp_dut/n456 ),
	.CLK(n92));
   DFFNEGX1 \dp_dut/inserted_money_reg[0]  (.Q(\dp_dut/N155 ),
	.D(\dp_dut/n455 ),
	.CLK(n92));
   DFFNEGX1 \dp_dut/item_b_num_reg[6]  (.Q(\dp_dut/item_b_num [6]),
	.D(\dp_dut/n438 ),
	.CLK(n92));
   DFFNEGX1 \dp_dut/item_b_num_reg[5]  (.Q(\dp_dut/item_b_num [5]),
	.D(\dp_dut/n439 ),
	.CLK(n92));
   DFFNEGX1 \dp_dut/item_b_num_reg[4]  (.Q(\dp_dut/item_b_num [4]),
	.D(\dp_dut/n440 ),
	.CLK(n91));
   DFFNEGX1 \dp_dut/item_b_num_reg[3]  (.Q(\dp_dut/item_b_num [3]),
	.D(\dp_dut/n441 ),
	.CLK(n91));
   DFFNEGX1 \dp_dut/item_b_num_reg[2]  (.Q(\dp_dut/item_b_num [2]),
	.D(\dp_dut/n442 ),
	.CLK(n91));
   DFFNEGX1 \dp_dut/item_b_num_reg[1]  (.Q(\dp_dut/item_b_num [1]),
	.D(\dp_dut/n443 ),
	.CLK(n91));
   DFFNEGX1 \dp_dut/item_b_num_reg[0]  (.Q(\dp_dut/item_b_num [0]),
	.D(\dp_dut/n444 ),
	.CLK(n91));
   DFFNEGX1 \dp_dut/item_b_num_reg[7]  (.Q(\dp_dut/item_b_num [7]),
	.D(\dp_dut/n445 ),
	.CLK(n91));
   DFFNEGX1 \dp_dut/dollar_1_num_reg[6]  (.Q(\dp_dut/dollar_1_num [6]),
	.D(\dp_dut/n409 ),
	.CLK(n91));
   DFFNEGX1 \dp_dut/dollar_1_num_reg[0]  (.Q(\dp_dut/dollar_1_num [0]),
	.D(\dp_dut/n415 ),
	.CLK(n91));
   DFFNEGX1 \dp_dut/dollar_1_num_reg[7]  (.Q(\dp_dut/dollar_1_num [7]),
	.D(\dp_dut/n408 ),
	.CLK(n91));
   DFFNEGX1 \dp_dut/dollar_1_num_reg[1]  (.Q(\dp_dut/dollar_1_num [1]),
	.D(\dp_dut/n414 ),
	.CLK(n91));
   DFFNEGX1 \dp_dut/inserted_money_reg[14]  (.Q(\dp_dut/inserted_money [14]),
	.D(\dp_dut/n469 ),
	.CLK(n91));
   DFFNEGX1 \dp_dut/inserted_money_reg[15]  (.Q(\dp_dut/inserted_money [15]),
	.D(\dp_dut/n478 ),
	.CLK(n91));
   DFFNEGX1 \dp_dut/out_csel_b_reg  (.Q(out_csel_b),
	.D(\dp_dut/n479 ),
	.CLK(n91));
   FAX1 \dp_dut/sub_76/U2_2  (.YS(\dp_dut/N46 ),
	.YC(\dp_dut/sub_76/carry [3]),
	.C(\dp_dut/sub_76/carry [2]),
	.B(n127),
	.A(\dp_dut/inserted_money [2]));
   FAX1 \dp_dut/sub_76/U2_3  (.YS(\dp_dut/N47 ),
	.YC(\dp_dut/sub_76/carry [4]),
	.C(\dp_dut/sub_76/carry [3]),
	.B(n10),
	.A(\dp_dut/inserted_money [3]));
   FAX1 \dp_dut/sub_76/U2_4  (.YS(\dp_dut/N48 ),
	.YC(\dp_dut/sub_76/carry [5]),
	.C(\dp_dut/sub_76/carry [4]),
	.B(n129),
	.A(\dp_dut/inserted_money [4]));
   FAX1 \dp_dut/sub_76/U2_5  (.YS(\dp_dut/N49 ),
	.YC(\dp_dut/sub_76/carry [6]),
	.C(\dp_dut/sub_76/carry [5]),
	.B(n130),
	.A(\dp_dut/inserted_money [5]));
   FAX1 \dp_dut/sub_137/U2_2  (.YS(\dp_dut/N200 ),
	.YC(\dp_dut/sub_137/carry [3]),
	.C(\dp_dut/sub_137/carry [2]),
	.B(n127),
	.A(\dp_dut/inserted_money [2]));
   FAX1 \dp_dut/sub_137/U2_3  (.YS(\dp_dut/N201 ),
	.YC(\dp_dut/sub_137/carry [4]),
	.C(\dp_dut/sub_137/carry [3]),
	.B(n10),
	.A(\dp_dut/inserted_money [3]));
   FAX1 \dp_dut/sub_137/U2_4  (.YS(\dp_dut/N202 ),
	.YC(\dp_dut/sub_137/carry [5]),
	.C(\dp_dut/sub_137/carry [4]),
	.B(n129),
	.A(\dp_dut/inserted_money [4]));
   FAX1 \dp_dut/sub_137/U2_5  (.YS(\dp_dut/N203 ),
	.YC(\dp_dut/sub_137/carry [6]),
	.C(\dp_dut/sub_137/carry [5]),
	.B(n130),
	.A(\dp_dut/inserted_money [5]));
   FAX1 \dp_dut/sub_185/U2_1  (.YS(\dp_dut/N334 ),
	.YC(\dp_dut/sub_185/carry [2]),
	.C(\dp_dut/sub_185/carry [1]),
	.B(n199),
	.A(\dp_dut/dollar_1_num [1]));
   FAX1 \dp_dut/sub_185/U2_2  (.YS(\dp_dut/N335 ),
	.YC(\dp_dut/sub_185/carry [3]),
	.C(\dp_dut/sub_185/carry [2]),
	.B(n198),
	.A(\dp_dut/dollar_1_num [2]));
   FAX1 \dp_dut/sub_185/U2_3  (.YS(\dp_dut/N336 ),
	.YC(\dp_dut/sub_185/carry [4]),
	.C(\dp_dut/sub_185/carry [3]),
	.B(n197),
	.A(\dp_dut/dollar_1_num [3]));
   FAX1 \dp_dut/sub_185/U2_4  (.YS(\dp_dut/N337 ),
	.YC(\dp_dut/sub_185/carry [5]),
	.C(\dp_dut/sub_185/carry [4]),
	.B(n196),
	.A(\dp_dut/dollar_1_num [4]));
   FAX1 \dp_dut/sub_185/U2_5  (.YS(\dp_dut/N338 ),
	.YC(\dp_dut/sub_185/carry [6]),
	.C(\dp_dut/sub_185/carry [5]),
	.B(n195),
	.A(\dp_dut/dollar_1_num [5]));
   FAX1 \dp_dut/sub_185/U2_6  (.YS(\dp_dut/N339 ),
	.YC(\dp_dut/sub_185/carry [7]),
	.C(\dp_dut/sub_185/carry [6]),
	.B(n193),
	.A(\dp_dut/dollar_1_num [6]));
   FAX1 \dp_dut/sub_185/U2_7  (.YS(\dp_dut/N340 ),
	.YC(),
	.C(\dp_dut/sub_185/carry [7]),
	.B(n192),
	.A(\dp_dut/dollar_1_num [7]));
   FAX1 \dp_dut/dp_cluster_0/add_1_root_add_121_5/U1_5  (.YS(\dp_dut/dp_cluster_0/N144 ),
	.YC(\dp_dut/dp_cluster_0/add_1_root_add_121_5/carry[6] ),
	.C(n39),
	.B(in_inserted_5),
	.A(\dp_dut/dp_cluster_0/N96 ));
   FAX1 \dp_dut/dp_cluster_0/add_0_root_add_121_5/U1_2  (.YS(\dp_dut/N157 ),
	.YC(\dp_dut/dp_cluster_0/add_0_root_add_121_5/carry[3] ),
	.C(n12),
	.B(\dp_dut/inserted_money [2]),
	.A(n69));
   FAX1 \dp_dut/dp_cluster_1/add_2_root_add_75_3/U1_3  (.YS(\dp_dut/dp_cluster_1/N29 ),
	.YC(\dp_dut/dp_cluster_1/N30 ),
	.C(n16),
	.B(out_csel_b),
	.A(out_csel_a));
   FAX1 \dp_dut/dp_cluster_1/add_0_root_add_75_3/U1_3  (.YS(\dp_dut/N40 ),
	.YC(\dp_dut/dp_cluster_1/add_0_root_add_75_3/carry[4] ),
	.C(n40),
	.B(\dp_dut/dp_cluster_1/N34 ),
	.A(\dp_dut/dp_cluster_1/N29 ));
   FAX1 \dp_dut/dp_cluster_1/add_0_root_add_75_3/U1_4  (.YS(\dp_dut/N41 ),
	.YC(\dp_dut/N42 ),
	.C(\dp_dut/dp_cluster_1/add_0_root_add_75_3/carry[4] ),
	.B(n11),
	.A(\dp_dut/dp_cluster_1/N30 ));
   AND2X2 U1 (.Y(n1),
	.B(\dp_dut/n341 ),
	.A(\dp_dut/n284 ));
   OR2X2 U2 (.Y(n2),
	.B(\dp_dut/n234 ),
	.A(\dp_dut/n204 ));
   AND2X2 U3 (.Y(n3),
	.B(\dp_dut/dollar_1_num [2]),
	.A(n24));
   AND2X2 U4 (.Y(n4),
	.B(\dp_dut/dollar_1_num [4]),
	.A(n19));
   AND2X2 U5 (.Y(n5),
	.B(\dp_dut/inserted_money [7]),
	.A(n27));
   AND2X2 U6 (.Y(n6),
	.B(\dp_dut/dollar_05_num [3]),
	.A(n31));
   AND2X2 U7 (.Y(n7),
	.B(\dp_dut/dollar_025_num [3]),
	.A(n33));
   AND2X2 U8 (.Y(n8),
	.B(\dp_dut/inserted_money [13]),
	.A(n35));
   AND2X2 U9 (.Y(n9),
	.B(\dp_dut/dp_cluster_0/N145 ),
	.A(n59));
   NAND2X1 U10 (.Y(n10),
	.B(n81),
	.A(\dp_dut/N40 ));
   AND2X2 U11 (.Y(n11),
	.B(out_csel_c),
	.A(out_csel_d));
   AND2X2 U12 (.Y(n12),
	.B(n68),
	.A(\dp_dut/inserted_money [1]));
   AND2X2 U13 (.Y(n13),
	.B(\dp_dut/inserted_money [3]),
	.A(in_inserted_5));
   AND2X2 U14 (.Y(n14),
	.B(\dp_dut/inserted_money [4]),
	.A(n13));
   AND2X2 U15 (.Y(n15),
	.B(\dp_dut/inserted_money [5]),
	.A(n14));
   AND2X2 U16 (.Y(n16),
	.B(out_csel_a),
	.A(out_csel_b));
   AND2X2 U17 (.Y(n17),
	.B(\dp_dut/dollar_1_num [0]),
	.A(in_inserted_1));
   AND2X2 U18 (.Y(n18),
	.B(\dp_dut/dp_cluster_0/N94 ),
	.A(in_inserted_1));
   AND2X2 U19 (.Y(n19),
	.B(\dp_dut/dollar_1_num [3]),
	.A(n3));
   AND2X2 U20 (.Y(n20),
	.B(\dp_dut/dollar_1_num [5]),
	.A(n4));
   AND2X2 U21 (.Y(n21),
	.B(\dp_dut/inserted_money [8]),
	.A(n5));
   AND2X2 U22 (.Y(n22),
	.B(\dp_dut/inserted_money [9]),
	.A(n21));
   AND2X2 U23 (.Y(n23),
	.B(\dp_dut/inserted_money [10]),
	.A(n22));
   AND2X2 U24 (.Y(n24),
	.B(\dp_dut/dollar_1_num [1]),
	.A(n17));
   AND2X2 U25 (.Y(n25),
	.B(\dp_dut/dollar_05_num [0]),
	.A(n69));
   AND2X2 U26 (.Y(n26),
	.B(\dp_dut/dollar_025_num [0]),
	.A(n68));
   AND2X2 U27 (.Y(n27),
	.B(\dp_dut/inserted_money [6]),
	.A(n15));
   AND2X2 U28 (.Y(n28),
	.B(\dp_dut/dollar_025_num [1]),
	.A(n26));
   AND2X2 U29 (.Y(n29),
	.B(\dp_dut/inserted_money [11]),
	.A(n23));
   AND2X2 U30 (.Y(n30),
	.B(\dp_dut/dollar_05_num [1]),
	.A(n25));
   AND2X2 U31 (.Y(n31),
	.B(\dp_dut/dollar_05_num [2]),
	.A(n30));
   AND2X2 U32 (.Y(n32),
	.B(\dp_dut/dollar_05_num [4]),
	.A(n6));
   AND2X2 U33 (.Y(n33),
	.B(\dp_dut/dollar_025_num [2]),
	.A(n28));
   AND2X2 U34 (.Y(n34),
	.B(\dp_dut/dollar_025_num [4]),
	.A(n7));
   AND2X2 U35 (.Y(n35),
	.B(\dp_dut/inserted_money [12]),
	.A(n29));
   AND2X2 U36 (.Y(n36),
	.B(out_csel_a),
	.A(out_csel_c));
   AND2X2 U37 (.Y(n37),
	.B(\dp_dut/dollar_05_num [5]),
	.A(n32));
   AND2X2 U38 (.Y(n38),
	.B(\dp_dut/dollar_025_num [5]),
	.A(n34));
   AND2X2 U39 (.Y(n39),
	.B(\dp_dut/dp_cluster_0/N95 ),
	.A(n18));
   AND2X2 U40 (.Y(n40),
	.B(\dp_dut/dp_cluster_1/N28 ),
	.A(n36));
   AND2X2 U41 (.Y(n41),
	.B(\dp_dut/dp_cluster_0/N142 ),
	.A(\dp_dut/dp_cluster_0/add_0_root_add_121_5/carry[3] ));
   AND2X2 U42 (.Y(n42),
	.B(\dp_dut/dp_cluster_0/N97 ),
	.A(\dp_dut/dp_cluster_0/add_1_root_add_121_5/carry[6] ));
   AND2X2 U43 (.Y(n43),
	.B(\dp_dut/dollar_1_num [6]),
	.A(n20));
   AND2X2 U44 (.Y(n44),
	.B(\dp_dut/dp_cluster_0/N98 ),
	.A(n42));
   AND2X2 U45 (.Y(n45),
	.B(\dp_dut/dp_cluster_0/N99 ),
	.A(n44));
   AND2X2 U46 (.Y(n46),
	.B(\dp_dut/dp_cluster_0/N100 ),
	.A(n45));
   AND2X2 U47 (.Y(n47),
	.B(\dp_dut/dp_cluster_0/N101 ),
	.A(n46));
   AND2X2 U48 (.Y(n48),
	.B(\dp_dut/dp_cluster_0/N102 ),
	.A(n47));
   AND2X2 U49 (.Y(n49),
	.B(\dp_dut/dp_cluster_0/N103 ),
	.A(n48));
   AND2X2 U50 (.Y(n50),
	.B(\dp_dut/dp_cluster_0/N104 ),
	.A(n49));
   AND2X2 U51 (.Y(n51),
	.B(\dp_dut/dp_cluster_0/N143 ),
	.A(n41));
   AND2X2 U52 (.Y(n52),
	.B(\dp_dut/dp_cluster_0/N146 ),
	.A(n9));
   AND2X2 U53 (.Y(n53),
	.B(\dp_dut/dp_cluster_0/N147 ),
	.A(n52));
   AND2X2 U54 (.Y(n54),
	.B(\dp_dut/dp_cluster_0/N148 ),
	.A(n53));
   AND2X2 U55 (.Y(n55),
	.B(\dp_dut/dp_cluster_0/N149 ),
	.A(n54));
   AND2X2 U56 (.Y(n56),
	.B(\dp_dut/dp_cluster_0/N150 ),
	.A(n55));
   AND2X2 U57 (.Y(n57),
	.B(\dp_dut/dp_cluster_0/N151 ),
	.A(n56));
   AND2X2 U58 (.Y(n58),
	.B(\dp_dut/dp_cluster_0/N152 ),
	.A(n57));
   AND2X2 U59 (.Y(n59),
	.B(\dp_dut/dp_cluster_0/N144 ),
	.A(n51));
   AND2X2 U60 (.Y(n60),
	.B(\dp_dut/dollar_05_num [6]),
	.A(n37));
   AND2X2 U61 (.Y(n61),
	.B(\dp_dut/dollar_025_num [6]),
	.A(n38));
   AND2X2 U62 (.Y(n62),
	.B(\dp_dut/inserted_money [14]),
	.A(n8));
   AND2X2 U63 (.Y(n63),
	.B(\dp_dut/dp_cluster_0/N105 ),
	.A(n50));
   AND2X2 U64 (.Y(n64),
	.B(\dp_dut/dp_cluster_0/N153 ),
	.A(n58));
   INVX2 U65 (.Y(n83),
	.A(\dp_dut/n372 ));
   INVX2 U66 (.Y(n71),
	.A(n65));
   INVX2 U67 (.Y(n98),
	.A(\dp_dut/n288 ));
   OR2X1 U68 (.Y(n65),
	.B(n72),
	.A(n132));
   INVX2 U69 (.Y(n84),
	.A(n66));
   INVX2 U70 (.Y(n85),
	.A(n66));
   INVX2 U71 (.Y(n86),
	.A(n87));
   INVX2 U72 (.Y(n73),
	.A(n72));
   INVX2 U73 (.Y(n70),
	.A(n67));
   BUFX2 U74 (.Y(n97),
	.A(n90));
   BUFX2 U75 (.Y(n91),
	.A(n88));
   BUFX2 U76 (.Y(n92),
	.A(n88));
   BUFX2 U77 (.Y(n93),
	.A(n88));
   BUFX2 U78 (.Y(n94),
	.A(n89));
   BUFX2 U79 (.Y(n95),
	.A(n89));
   BUFX2 U80 (.Y(n96),
	.A(n89));
   OR2X1 U81 (.Y(n66),
	.B(n109),
	.A(\dp_dut/n344 ));
   INVX2 U82 (.Y(n87),
	.A(\dp_dut/n284 ));
   OR2X1 U83 (.Y(n67),
	.B(\dp_dut/n342 ),
	.A(\dp_dut/n344 ));
   INVX2 U84 (.Y(n74),
	.A(n2));
   INVX2 U85 (.Y(n72),
	.A(\dp_dut/n345 ));
   BUFX2 U86 (.Y(n69),
	.A(in_inserted_05));
   BUFX2 U87 (.Y(n68),
	.A(in_inserted_025));
   BUFX2 U88 (.Y(n88),
	.A(in_clka));
   BUFX2 U89 (.Y(n89),
	.A(in_clka));
   BUFX2 U90 (.Y(n90),
	.A(in_clka));
   OR2X1 U91 (.Y(\dp_dut/sub_76/carry [11]),
	.B(\dp_dut/sub_76/carry [10]),
	.A(\dp_dut/inserted_money [10]));
   XNOR2X1 U92 (.Y(\dp_dut/N54 ),
	.B(\dp_dut/inserted_money [10]),
	.A(\dp_dut/sub_76/carry [10]));
   OR2X1 U93 (.Y(\dp_dut/sub_76/carry [12]),
	.B(\dp_dut/sub_76/carry [11]),
	.A(\dp_dut/inserted_money [11]));
   XNOR2X1 U94 (.Y(\dp_dut/N55 ),
	.B(\dp_dut/inserted_money [11]),
	.A(\dp_dut/sub_76/carry [11]));
   OR2X1 U95 (.Y(\dp_dut/sub_76/carry [13]),
	.B(\dp_dut/sub_76/carry [12]),
	.A(\dp_dut/inserted_money [12]));
   XNOR2X1 U96 (.Y(\dp_dut/N56 ),
	.B(\dp_dut/inserted_money [12]),
	.A(\dp_dut/sub_76/carry [12]));
   OR2X1 U97 (.Y(\dp_dut/sub_76/carry [14]),
	.B(\dp_dut/sub_76/carry [13]),
	.A(\dp_dut/inserted_money [13]));
   XNOR2X1 U98 (.Y(\dp_dut/N57 ),
	.B(\dp_dut/inserted_money [13]),
	.A(\dp_dut/sub_76/carry [13]));
   OR2X1 U99 (.Y(\dp_dut/sub_76/carry [15]),
	.B(\dp_dut/sub_76/carry [14]),
	.A(\dp_dut/inserted_money [14]));
   XNOR2X1 U100 (.Y(\dp_dut/N58 ),
	.B(\dp_dut/inserted_money [14]),
	.A(\dp_dut/sub_76/carry [14]));
   XNOR2X1 U101 (.Y(\dp_dut/N59 ),
	.B(\dp_dut/sub_76/carry [15]),
	.A(\dp_dut/inserted_money [15]));
   OR2X1 U102 (.Y(\dp_dut/sub_76/carry [8]),
	.B(\dp_dut/sub_76/carry [7]),
	.A(\dp_dut/inserted_money [7]));
   XNOR2X1 U103 (.Y(\dp_dut/N51 ),
	.B(\dp_dut/inserted_money [7]),
	.A(\dp_dut/sub_76/carry [7]));
   OR2X1 U104 (.Y(\dp_dut/sub_76/carry [9]),
	.B(\dp_dut/sub_76/carry [8]),
	.A(\dp_dut/inserted_money [8]));
   XNOR2X1 U105 (.Y(\dp_dut/N52 ),
	.B(\dp_dut/inserted_money [8]),
	.A(\dp_dut/sub_76/carry [8]));
   OR2X1 U106 (.Y(\dp_dut/sub_76/carry [10]),
	.B(\dp_dut/sub_76/carry [9]),
	.A(\dp_dut/inserted_money [9]));
   XNOR2X1 U107 (.Y(\dp_dut/N53 ),
	.B(\dp_dut/inserted_money [9]),
	.A(\dp_dut/sub_76/carry [9]));
   OR2X1 U108 (.Y(\dp_dut/r474/carry [2]),
	.B(\dp_dut/r474/carry [1]),
	.A(\dp_dut/item_a_num [1]));
   XNOR2X1 U109 (.Y(\dp_dut/N215 ),
	.B(\dp_dut/item_a_num [1]),
	.A(\dp_dut/r474/carry [1]));
   OR2X1 U110 (.Y(\dp_dut/r474/carry [3]),
	.B(\dp_dut/r474/carry [2]),
	.A(\dp_dut/item_a_num [2]));
   XNOR2X1 U111 (.Y(\dp_dut/N216 ),
	.B(\dp_dut/item_a_num [2]),
	.A(\dp_dut/r474/carry [2]));
   OR2X1 U112 (.Y(\dp_dut/r474/carry [4]),
	.B(\dp_dut/r474/carry [3]),
	.A(\dp_dut/item_a_num [3]));
   XNOR2X1 U113 (.Y(\dp_dut/N217 ),
	.B(\dp_dut/item_a_num [3]),
	.A(\dp_dut/r474/carry [3]));
   OR2X1 U114 (.Y(\dp_dut/r474/carry [5]),
	.B(\dp_dut/r474/carry [4]),
	.A(\dp_dut/item_a_num [4]));
   XNOR2X1 U115 (.Y(\dp_dut/N218 ),
	.B(\dp_dut/item_a_num [4]),
	.A(\dp_dut/r474/carry [4]));
   OR2X1 U116 (.Y(\dp_dut/r474/carry [6]),
	.B(\dp_dut/r474/carry [5]),
	.A(\dp_dut/item_a_num [5]));
   XNOR2X1 U117 (.Y(\dp_dut/N219 ),
	.B(\dp_dut/item_a_num [5]),
	.A(\dp_dut/r474/carry [5]));
   OR2X1 U118 (.Y(\dp_dut/r474/carry [7]),
	.B(\dp_dut/r474/carry [6]),
	.A(\dp_dut/item_a_num [6]));
   XNOR2X1 U119 (.Y(\dp_dut/N220 ),
	.B(\dp_dut/item_a_num [6]),
	.A(\dp_dut/r474/carry [6]));
   XNOR2X1 U120 (.Y(\dp_dut/N221 ),
	.B(\dp_dut/r474/carry [7]),
	.A(\dp_dut/item_a_num [7]));
   OR2X1 U121 (.Y(\dp_dut/r474/carry [1]),
	.B(n188),
	.A(\dp_dut/item_a_num [0]));
   XNOR2X1 U122 (.Y(\dp_dut/N214 ),
	.B(\dp_dut/item_a_num [0]),
	.A(n188));
   OR2X1 U123 (.Y(\dp_dut/r475/carry [2]),
	.B(\dp_dut/r475/carry [1]),
	.A(\dp_dut/item_b_num [1]));
   XNOR2X1 U124 (.Y(\dp_dut/N223 ),
	.B(\dp_dut/item_b_num [1]),
	.A(\dp_dut/r475/carry [1]));
   OR2X1 U125 (.Y(\dp_dut/r475/carry [3]),
	.B(\dp_dut/r475/carry [2]),
	.A(\dp_dut/item_b_num [2]));
   XNOR2X1 U126 (.Y(\dp_dut/N224 ),
	.B(\dp_dut/item_b_num [2]),
	.A(\dp_dut/r475/carry [2]));
   OR2X1 U127 (.Y(\dp_dut/r475/carry [4]),
	.B(\dp_dut/r475/carry [3]),
	.A(\dp_dut/item_b_num [3]));
   XNOR2X1 U128 (.Y(\dp_dut/N225 ),
	.B(\dp_dut/item_b_num [3]),
	.A(\dp_dut/r475/carry [3]));
   OR2X1 U129 (.Y(\dp_dut/r475/carry [5]),
	.B(\dp_dut/r475/carry [4]),
	.A(\dp_dut/item_b_num [4]));
   XNOR2X1 U130 (.Y(\dp_dut/N226 ),
	.B(\dp_dut/item_b_num [4]),
	.A(\dp_dut/r475/carry [4]));
   OR2X1 U131 (.Y(\dp_dut/r475/carry [6]),
	.B(\dp_dut/r475/carry [5]),
	.A(\dp_dut/item_b_num [5]));
   XNOR2X1 U132 (.Y(\dp_dut/N227 ),
	.B(\dp_dut/item_b_num [5]),
	.A(\dp_dut/r475/carry [5]));
   OR2X1 U133 (.Y(\dp_dut/r475/carry [7]),
	.B(\dp_dut/r475/carry [6]),
	.A(\dp_dut/item_b_num [6]));
   XNOR2X1 U134 (.Y(\dp_dut/N228 ),
	.B(\dp_dut/item_b_num [6]),
	.A(\dp_dut/r475/carry [6]));
   XNOR2X1 U135 (.Y(\dp_dut/N229 ),
	.B(\dp_dut/r475/carry [7]),
	.A(\dp_dut/item_b_num [7]));
   OR2X1 U136 (.Y(\dp_dut/r475/carry [1]),
	.B(n217),
	.A(\dp_dut/item_b_num [0]));
   XNOR2X1 U137 (.Y(\dp_dut/N222 ),
	.B(\dp_dut/item_b_num [0]),
	.A(n217));
   OR2X1 U138 (.Y(\dp_dut/r476/carry [2]),
	.B(\dp_dut/r476/carry [1]),
	.A(\dp_dut/item_c_num [1]));
   XNOR2X1 U139 (.Y(\dp_dut/N231 ),
	.B(\dp_dut/item_c_num [1]),
	.A(\dp_dut/r476/carry [1]));
   OR2X1 U140 (.Y(\dp_dut/r476/carry [3]),
	.B(\dp_dut/r476/carry [2]),
	.A(\dp_dut/item_c_num [2]));
   XNOR2X1 U141 (.Y(\dp_dut/N232 ),
	.B(\dp_dut/item_c_num [2]),
	.A(\dp_dut/r476/carry [2]));
   OR2X1 U142 (.Y(\dp_dut/r476/carry [4]),
	.B(\dp_dut/r476/carry [3]),
	.A(\dp_dut/item_c_num [3]));
   XNOR2X1 U143 (.Y(\dp_dut/N233 ),
	.B(\dp_dut/item_c_num [3]),
	.A(\dp_dut/r476/carry [3]));
   OR2X1 U144 (.Y(\dp_dut/r476/carry [5]),
	.B(\dp_dut/r476/carry [4]),
	.A(\dp_dut/item_c_num [4]));
   XNOR2X1 U145 (.Y(\dp_dut/N234 ),
	.B(\dp_dut/item_c_num [4]),
	.A(\dp_dut/r476/carry [4]));
   OR2X1 U146 (.Y(\dp_dut/r476/carry [6]),
	.B(\dp_dut/r476/carry [5]),
	.A(\dp_dut/item_c_num [5]));
   XNOR2X1 U147 (.Y(\dp_dut/N235 ),
	.B(\dp_dut/item_c_num [5]),
	.A(\dp_dut/r476/carry [5]));
   OR2X1 U148 (.Y(\dp_dut/r476/carry [7]),
	.B(\dp_dut/r476/carry [6]),
	.A(\dp_dut/item_c_num [6]));
   XNOR2X1 U149 (.Y(\dp_dut/N236 ),
	.B(\dp_dut/item_c_num [6]),
	.A(\dp_dut/r476/carry [6]));
   XNOR2X1 U150 (.Y(\dp_dut/N237 ),
	.B(\dp_dut/r476/carry [7]),
	.A(\dp_dut/item_c_num [7]));
   OR2X1 U151 (.Y(\dp_dut/r476/carry [1]),
	.B(n179),
	.A(\dp_dut/item_c_num [0]));
   XNOR2X1 U152 (.Y(\dp_dut/N230 ),
	.B(\dp_dut/item_c_num [0]),
	.A(n179));
   OR2X1 U153 (.Y(\dp_dut/r477/carry [2]),
	.B(\dp_dut/r477/carry [1]),
	.A(\dp_dut/item_d_num [1]));
   XNOR2X1 U154 (.Y(\dp_dut/N239 ),
	.B(\dp_dut/item_d_num [1]),
	.A(\dp_dut/r477/carry [1]));
   OR2X1 U155 (.Y(\dp_dut/r477/carry [3]),
	.B(\dp_dut/r477/carry [2]),
	.A(\dp_dut/item_d_num [2]));
   XNOR2X1 U156 (.Y(\dp_dut/N240 ),
	.B(\dp_dut/item_d_num [2]),
	.A(\dp_dut/r477/carry [2]));
   OR2X1 U157 (.Y(\dp_dut/r477/carry [4]),
	.B(\dp_dut/r477/carry [3]),
	.A(\dp_dut/item_d_num [3]));
   XNOR2X1 U158 (.Y(\dp_dut/N241 ),
	.B(\dp_dut/item_d_num [3]),
	.A(\dp_dut/r477/carry [3]));
   OR2X1 U159 (.Y(\dp_dut/r477/carry [5]),
	.B(\dp_dut/r477/carry [4]),
	.A(\dp_dut/item_d_num [4]));
   XNOR2X1 U160 (.Y(\dp_dut/N242 ),
	.B(\dp_dut/item_d_num [4]),
	.A(\dp_dut/r477/carry [4]));
   OR2X1 U161 (.Y(\dp_dut/r477/carry [6]),
	.B(\dp_dut/r477/carry [5]),
	.A(\dp_dut/item_d_num [5]));
   XNOR2X1 U162 (.Y(\dp_dut/N243 ),
	.B(\dp_dut/item_d_num [5]),
	.A(\dp_dut/r477/carry [5]));
   OR2X1 U163 (.Y(\dp_dut/r477/carry [7]),
	.B(\dp_dut/r477/carry [6]),
	.A(\dp_dut/item_d_num [6]));
   XNOR2X1 U164 (.Y(\dp_dut/N244 ),
	.B(\dp_dut/item_d_num [6]),
	.A(\dp_dut/r477/carry [6]));
   XNOR2X1 U165 (.Y(\dp_dut/N245 ),
	.B(\dp_dut/r477/carry [7]),
	.A(\dp_dut/item_d_num [7]));
   OR2X1 U166 (.Y(\dp_dut/r477/carry [1]),
	.B(n170),
	.A(\dp_dut/item_d_num [0]));
   XNOR2X1 U167 (.Y(\dp_dut/N238 ),
	.B(\dp_dut/item_d_num [0]),
	.A(n170));
   OR2X1 U168 (.Y(\dp_dut/sub_137/carry [11]),
	.B(\dp_dut/sub_137/carry [10]),
	.A(\dp_dut/inserted_money [10]));
   XNOR2X1 U169 (.Y(\dp_dut/N208 ),
	.B(\dp_dut/inserted_money [10]),
	.A(\dp_dut/sub_137/carry [10]));
   OR2X1 U170 (.Y(\dp_dut/sub_137/carry [12]),
	.B(\dp_dut/sub_137/carry [11]),
	.A(\dp_dut/inserted_money [11]));
   XNOR2X1 U171 (.Y(\dp_dut/N209 ),
	.B(\dp_dut/inserted_money [11]),
	.A(\dp_dut/sub_137/carry [11]));
   OR2X1 U172 (.Y(\dp_dut/sub_137/carry [13]),
	.B(\dp_dut/sub_137/carry [12]),
	.A(\dp_dut/inserted_money [12]));
   XNOR2X1 U173 (.Y(\dp_dut/N210 ),
	.B(\dp_dut/inserted_money [12]),
	.A(\dp_dut/sub_137/carry [12]));
   OR2X1 U174 (.Y(\dp_dut/sub_137/carry [14]),
	.B(\dp_dut/sub_137/carry [13]),
	.A(\dp_dut/inserted_money [13]));
   XNOR2X1 U175 (.Y(\dp_dut/N211 ),
	.B(\dp_dut/inserted_money [13]),
	.A(\dp_dut/sub_137/carry [13]));
   OR2X1 U176 (.Y(\dp_dut/sub_137/carry [15]),
	.B(\dp_dut/sub_137/carry [14]),
	.A(\dp_dut/inserted_money [14]));
   XNOR2X1 U177 (.Y(\dp_dut/N212 ),
	.B(\dp_dut/inserted_money [14]),
	.A(\dp_dut/sub_137/carry [14]));
   XNOR2X1 U178 (.Y(\dp_dut/N213 ),
	.B(\dp_dut/sub_137/carry [15]),
	.A(\dp_dut/inserted_money [15]));
   OR2X1 U179 (.Y(\dp_dut/sub_137/carry [8]),
	.B(\dp_dut/sub_137/carry [7]),
	.A(\dp_dut/inserted_money [7]));
   XNOR2X1 U180 (.Y(\dp_dut/N205 ),
	.B(\dp_dut/inserted_money [7]),
	.A(\dp_dut/sub_137/carry [7]));
   OR2X1 U181 (.Y(\dp_dut/sub_137/carry [9]),
	.B(\dp_dut/sub_137/carry [8]),
	.A(\dp_dut/inserted_money [8]));
   XNOR2X1 U182 (.Y(\dp_dut/N206 ),
	.B(\dp_dut/inserted_money [8]),
	.A(\dp_dut/sub_137/carry [8]));
   OR2X1 U183 (.Y(\dp_dut/sub_137/carry [10]),
	.B(\dp_dut/sub_137/carry [9]),
	.A(\dp_dut/inserted_money [9]));
   XNOR2X1 U184 (.Y(\dp_dut/N207 ),
	.B(\dp_dut/inserted_money [9]),
	.A(\dp_dut/sub_137/carry [9]));
   OR2X1 U185 (.Y(\dp_dut/sub_171/carry [2]),
	.B(\dp_dut/sub_171/carry [1]),
	.A(\dp_dut/dollar_1_num [1]));
   XNOR2X1 U186 (.Y(\dp_dut/N294 ),
	.B(\dp_dut/dollar_1_num [1]),
	.A(\dp_dut/sub_171/carry [1]));
   OR2X1 U187 (.Y(\dp_dut/sub_171/carry [3]),
	.B(\dp_dut/sub_171/carry [2]),
	.A(\dp_dut/dollar_1_num [2]));
   XNOR2X1 U188 (.Y(\dp_dut/N295 ),
	.B(\dp_dut/dollar_1_num [2]),
	.A(\dp_dut/sub_171/carry [2]));
   OR2X1 U189 (.Y(\dp_dut/sub_171/carry [4]),
	.B(\dp_dut/sub_171/carry [3]),
	.A(\dp_dut/dollar_1_num [3]));
   XNOR2X1 U190 (.Y(\dp_dut/N296 ),
	.B(\dp_dut/dollar_1_num [3]),
	.A(\dp_dut/sub_171/carry [3]));
   OR2X1 U191 (.Y(\dp_dut/sub_171/carry [5]),
	.B(\dp_dut/sub_171/carry [4]),
	.A(\dp_dut/dollar_1_num [4]));
   XNOR2X1 U192 (.Y(\dp_dut/N297 ),
	.B(\dp_dut/dollar_1_num [4]),
	.A(\dp_dut/sub_171/carry [4]));
   OR2X1 U193 (.Y(\dp_dut/sub_171/carry [6]),
	.B(\dp_dut/sub_171/carry [5]),
	.A(\dp_dut/dollar_1_num [5]));
   XNOR2X1 U194 (.Y(\dp_dut/N298 ),
	.B(\dp_dut/dollar_1_num [5]),
	.A(\dp_dut/sub_171/carry [5]));
   OR2X1 U195 (.Y(\dp_dut/sub_171/carry [7]),
	.B(\dp_dut/sub_171/carry [6]),
	.A(\dp_dut/dollar_1_num [6]));
   XNOR2X1 U196 (.Y(\dp_dut/N299 ),
	.B(\dp_dut/dollar_1_num [6]),
	.A(\dp_dut/sub_171/carry [6]));
   XNOR2X1 U197 (.Y(\dp_dut/N300 ),
	.B(\dp_dut/sub_171/carry [7]),
	.A(\dp_dut/dollar_1_num [7]));
   OR2X1 U198 (.Y(\dp_dut/sub_171/carry [1]),
	.B(\dp_dut/n389 ),
	.A(\dp_dut/dollar_1_num [0]));
   XNOR2X1 U199 (.Y(\dp_dut/N293 ),
	.B(\dp_dut/dollar_1_num [0]),
	.A(\dp_dut/n389 ));
   OR2X1 U200 (.Y(\dp_dut/sub_172/carry [2]),
	.B(\dp_dut/sub_172/carry [1]),
	.A(\dp_dut/dollar_05_num [1]));
   XNOR2X1 U201 (.Y(\dp_dut/N312 ),
	.B(\dp_dut/dollar_05_num [1]),
	.A(\dp_dut/sub_172/carry [1]));
   OR2X1 U202 (.Y(\dp_dut/sub_172/carry [3]),
	.B(\dp_dut/sub_172/carry [2]),
	.A(\dp_dut/dollar_05_num [2]));
   XNOR2X1 U203 (.Y(\dp_dut/N313 ),
	.B(\dp_dut/dollar_05_num [2]),
	.A(\dp_dut/sub_172/carry [2]));
   OR2X1 U204 (.Y(\dp_dut/sub_172/carry [4]),
	.B(\dp_dut/sub_172/carry [3]),
	.A(\dp_dut/dollar_05_num [3]));
   XNOR2X1 U205 (.Y(\dp_dut/N314 ),
	.B(\dp_dut/dollar_05_num [3]),
	.A(\dp_dut/sub_172/carry [3]));
   OR2X1 U206 (.Y(\dp_dut/sub_172/carry [5]),
	.B(\dp_dut/sub_172/carry [4]),
	.A(\dp_dut/dollar_05_num [4]));
   XNOR2X1 U207 (.Y(\dp_dut/N315 ),
	.B(\dp_dut/dollar_05_num [4]),
	.A(\dp_dut/sub_172/carry [4]));
   OR2X1 U208 (.Y(\dp_dut/sub_172/carry [6]),
	.B(\dp_dut/sub_172/carry [5]),
	.A(\dp_dut/dollar_05_num [5]));
   XNOR2X1 U209 (.Y(\dp_dut/N316 ),
	.B(\dp_dut/dollar_05_num [5]),
	.A(\dp_dut/sub_172/carry [5]));
   OR2X1 U210 (.Y(\dp_dut/sub_172/carry [7]),
	.B(\dp_dut/sub_172/carry [6]),
	.A(\dp_dut/dollar_05_num [6]));
   XNOR2X1 U211 (.Y(\dp_dut/N317 ),
	.B(\dp_dut/dollar_05_num [6]),
	.A(\dp_dut/sub_172/carry [6]));
   XNOR2X1 U212 (.Y(\dp_dut/N318 ),
	.B(\dp_dut/sub_172/carry [7]),
	.A(\dp_dut/dollar_05_num [7]));
   OR2X1 U213 (.Y(\dp_dut/sub_172/carry [1]),
	.B(\dp_dut/n389 ),
	.A(\dp_dut/dollar_05_num [0]));
   XNOR2X1 U214 (.Y(\dp_dut/N311 ),
	.B(\dp_dut/dollar_05_num [0]),
	.A(\dp_dut/n389 ));
   OR2X1 U215 (.Y(\dp_dut/sub_173/carry [2]),
	.B(\dp_dut/sub_173/carry [1]),
	.A(\dp_dut/dollar_025_num [1]));
   XNOR2X1 U216 (.Y(\dp_dut/N323 ),
	.B(\dp_dut/dollar_025_num [1]),
	.A(\dp_dut/sub_173/carry [1]));
   OR2X1 U217 (.Y(\dp_dut/sub_173/carry [3]),
	.B(\dp_dut/sub_173/carry [2]),
	.A(\dp_dut/dollar_025_num [2]));
   XNOR2X1 U218 (.Y(\dp_dut/N324 ),
	.B(\dp_dut/dollar_025_num [2]),
	.A(\dp_dut/sub_173/carry [2]));
   OR2X1 U219 (.Y(\dp_dut/sub_173/carry [4]),
	.B(\dp_dut/sub_173/carry [3]),
	.A(\dp_dut/dollar_025_num [3]));
   XNOR2X1 U220 (.Y(\dp_dut/N325 ),
	.B(\dp_dut/dollar_025_num [3]),
	.A(\dp_dut/sub_173/carry [3]));
   OR2X1 U221 (.Y(\dp_dut/sub_173/carry [5]),
	.B(\dp_dut/sub_173/carry [4]),
	.A(\dp_dut/dollar_025_num [4]));
   XNOR2X1 U222 (.Y(\dp_dut/N326 ),
	.B(\dp_dut/dollar_025_num [4]),
	.A(\dp_dut/sub_173/carry [4]));
   OR2X1 U223 (.Y(\dp_dut/sub_173/carry [6]),
	.B(\dp_dut/sub_173/carry [5]),
	.A(\dp_dut/dollar_025_num [5]));
   XNOR2X1 U224 (.Y(\dp_dut/N327 ),
	.B(\dp_dut/dollar_025_num [5]),
	.A(\dp_dut/sub_173/carry [5]));
   OR2X1 U225 (.Y(\dp_dut/sub_173/carry [7]),
	.B(\dp_dut/sub_173/carry [6]),
	.A(\dp_dut/dollar_025_num [6]));
   XNOR2X1 U226 (.Y(\dp_dut/N328 ),
	.B(\dp_dut/dollar_025_num [6]),
	.A(\dp_dut/sub_173/carry [6]));
   XNOR2X1 U227 (.Y(\dp_dut/N329 ),
	.B(\dp_dut/sub_173/carry [7]),
	.A(\dp_dut/dollar_025_num [7]));
   OR2X1 U228 (.Y(\dp_dut/sub_173/carry [1]),
	.B(\dp_dut/n389 ),
	.A(\dp_dut/dollar_025_num [0]));
   XNOR2X1 U229 (.Y(\dp_dut/N322 ),
	.B(\dp_dut/dollar_025_num [0]),
	.A(\dp_dut/n389 ));
   OR2X1 U230 (.Y(\dp_dut/sub_185/carry [1]),
	.B(n200),
	.A(\dp_dut/dollar_1_num [0]));
   XNOR2X1 U231 (.Y(\dp_dut/N333 ),
	.B(\dp_dut/dollar_1_num [0]),
	.A(n200));
   OR2X1 U232 (.Y(\dp_dut/sub_186/carry [2]),
	.B(\dp_dut/sub_186/carry [1]),
	.A(\dp_dut/dollar_05_num [1]));
   XNOR2X1 U233 (.Y(\dp_dut/N342 ),
	.B(\dp_dut/dollar_05_num [1]),
	.A(\dp_dut/sub_186/carry [1]));
   OR2X1 U234 (.Y(\dp_dut/sub_186/carry [3]),
	.B(\dp_dut/sub_186/carry [2]),
	.A(\dp_dut/dollar_05_num [2]));
   XNOR2X1 U235 (.Y(\dp_dut/N343 ),
	.B(\dp_dut/dollar_05_num [2]),
	.A(\dp_dut/sub_186/carry [2]));
   OR2X1 U236 (.Y(\dp_dut/sub_186/carry [4]),
	.B(\dp_dut/sub_186/carry [3]),
	.A(\dp_dut/dollar_05_num [3]));
   XNOR2X1 U237 (.Y(\dp_dut/N344 ),
	.B(\dp_dut/dollar_05_num [3]),
	.A(\dp_dut/sub_186/carry [3]));
   OR2X1 U238 (.Y(\dp_dut/sub_186/carry [5]),
	.B(\dp_dut/sub_186/carry [4]),
	.A(\dp_dut/dollar_05_num [4]));
   XNOR2X1 U239 (.Y(\dp_dut/N345 ),
	.B(\dp_dut/dollar_05_num [4]),
	.A(\dp_dut/sub_186/carry [4]));
   OR2X1 U240 (.Y(\dp_dut/sub_186/carry [6]),
	.B(\dp_dut/sub_186/carry [5]),
	.A(\dp_dut/dollar_05_num [5]));
   XNOR2X1 U241 (.Y(\dp_dut/N346 ),
	.B(\dp_dut/dollar_05_num [5]),
	.A(\dp_dut/sub_186/carry [5]));
   OR2X1 U242 (.Y(\dp_dut/sub_186/carry [7]),
	.B(\dp_dut/sub_186/carry [6]),
	.A(\dp_dut/dollar_05_num [6]));
   XNOR2X1 U243 (.Y(\dp_dut/N347 ),
	.B(\dp_dut/dollar_05_num [6]),
	.A(\dp_dut/sub_186/carry [6]));
   XNOR2X1 U244 (.Y(\dp_dut/N348 ),
	.B(\dp_dut/sub_186/carry [7]),
	.A(\dp_dut/dollar_05_num [7]));
   OR2X1 U245 (.Y(\dp_dut/sub_186/carry [1]),
	.B(n201),
	.A(\dp_dut/dollar_05_num [0]));
   XNOR2X1 U246 (.Y(\dp_dut/N341 ),
	.B(\dp_dut/dollar_05_num [0]),
	.A(n201));
   OR2X1 U247 (.Y(\dp_dut/sub_187/carry [2]),
	.B(\dp_dut/sub_187/carry [1]),
	.A(\dp_dut/dollar_025_num [1]));
   XNOR2X1 U248 (.Y(\dp_dut/N350 ),
	.B(\dp_dut/dollar_025_num [1]),
	.A(\dp_dut/sub_187/carry [1]));
   OR2X1 U249 (.Y(\dp_dut/sub_187/carry [3]),
	.B(\dp_dut/sub_187/carry [2]),
	.A(\dp_dut/dollar_025_num [2]));
   XNOR2X1 U250 (.Y(\dp_dut/N351 ),
	.B(\dp_dut/dollar_025_num [2]),
	.A(\dp_dut/sub_187/carry [2]));
   OR2X1 U251 (.Y(\dp_dut/sub_187/carry [4]),
	.B(\dp_dut/sub_187/carry [3]),
	.A(\dp_dut/dollar_025_num [3]));
   XNOR2X1 U252 (.Y(\dp_dut/N352 ),
	.B(\dp_dut/dollar_025_num [3]),
	.A(\dp_dut/sub_187/carry [3]));
   OR2X1 U253 (.Y(\dp_dut/sub_187/carry [5]),
	.B(\dp_dut/sub_187/carry [4]),
	.A(\dp_dut/dollar_025_num [4]));
   XNOR2X1 U254 (.Y(\dp_dut/N353 ),
	.B(\dp_dut/dollar_025_num [4]),
	.A(\dp_dut/sub_187/carry [4]));
   OR2X1 U255 (.Y(\dp_dut/sub_187/carry [6]),
	.B(\dp_dut/sub_187/carry [5]),
	.A(\dp_dut/dollar_025_num [5]));
   XNOR2X1 U256 (.Y(\dp_dut/N354 ),
	.B(\dp_dut/dollar_025_num [5]),
	.A(\dp_dut/sub_187/carry [5]));
   OR2X1 U257 (.Y(\dp_dut/sub_187/carry [7]),
	.B(\dp_dut/sub_187/carry [6]),
	.A(\dp_dut/dollar_025_num [6]));
   XNOR2X1 U258 (.Y(\dp_dut/N355 ),
	.B(\dp_dut/dollar_025_num [6]),
	.A(\dp_dut/sub_187/carry [6]));
   XNOR2X1 U259 (.Y(\dp_dut/N356 ),
	.B(\dp_dut/sub_187/carry [7]),
	.A(\dp_dut/dollar_025_num [7]));
   OR2X1 U260 (.Y(\dp_dut/sub_187/carry [1]),
	.B(n202),
	.A(\dp_dut/dollar_025_num [0]));
   XNOR2X1 U261 (.Y(\dp_dut/N349 ),
	.B(\dp_dut/dollar_025_num [0]),
	.A(n202));
   OR2X1 U262 (.Y(\dp_dut/sub_76/carry [7]),
	.B(\dp_dut/sub_76/carry [6]),
	.A(\dp_dut/inserted_money [6]));
   XNOR2X1 U263 (.Y(\dp_dut/N50 ),
	.B(\dp_dut/inserted_money [6]),
	.A(\dp_dut/sub_76/carry [6]));
   OR2X1 U264 (.Y(\dp_dut/sub_137/carry [7]),
	.B(\dp_dut/sub_137/carry [6]),
	.A(\dp_dut/inserted_money [6]));
   XNOR2X1 U265 (.Y(\dp_dut/N204 ),
	.B(\dp_dut/inserted_money [6]),
	.A(\dp_dut/sub_137/carry [6]));
   OR2X1 U266 (.Y(\dp_dut/sub_76/carry [2]),
	.B(n126),
	.A(\dp_dut/inserted_money [1]));
   XNOR2X1 U267 (.Y(\dp_dut/N45 ),
	.B(\dp_dut/inserted_money [1]),
	.A(n126));
   OR2X1 U268 (.Y(\dp_dut/sub_137/carry [2]),
	.B(n126),
	.A(\dp_dut/inserted_money [1]));
   XNOR2X1 U269 (.Y(\dp_dut/N199 ),
	.B(\dp_dut/inserted_money [1]),
	.A(n126));
   XOR2X1 U270 (.Y(\dp_dut/N171 ),
	.B(\dp_dut/dollar_1_num [0]),
	.A(in_inserted_1));
   XOR2X1 U271 (.Y(\dp_dut/N172 ),
	.B(\dp_dut/dollar_1_num [1]),
	.A(n17));
   XOR2X1 U272 (.Y(\dp_dut/N173 ),
	.B(\dp_dut/dollar_1_num [2]),
	.A(n24));
   XOR2X1 U273 (.Y(\dp_dut/N174 ),
	.B(\dp_dut/dollar_1_num [3]),
	.A(n3));
   XOR2X1 U274 (.Y(\dp_dut/N175 ),
	.B(\dp_dut/dollar_1_num [4]),
	.A(n19));
   XOR2X1 U275 (.Y(\dp_dut/N176 ),
	.B(\dp_dut/dollar_1_num [5]),
	.A(n4));
   XOR2X1 U276 (.Y(\dp_dut/N177 ),
	.B(\dp_dut/dollar_1_num [6]),
	.A(n20));
   XOR2X1 U277 (.Y(\dp_dut/N178 ),
	.B(n43),
	.A(\dp_dut/dollar_1_num [7]));
   XOR2X1 U278 (.Y(\dp_dut/N179 ),
	.B(\dp_dut/dollar_05_num [0]),
	.A(n69));
   XOR2X1 U279 (.Y(\dp_dut/N180 ),
	.B(\dp_dut/dollar_05_num [1]),
	.A(n25));
   XOR2X1 U280 (.Y(\dp_dut/N181 ),
	.B(\dp_dut/dollar_05_num [2]),
	.A(n30));
   XOR2X1 U281 (.Y(\dp_dut/N182 ),
	.B(\dp_dut/dollar_05_num [3]),
	.A(n31));
   XOR2X1 U282 (.Y(\dp_dut/N183 ),
	.B(\dp_dut/dollar_05_num [4]),
	.A(n6));
   XOR2X1 U283 (.Y(\dp_dut/N184 ),
	.B(\dp_dut/dollar_05_num [5]),
	.A(n32));
   XOR2X1 U284 (.Y(\dp_dut/N185 ),
	.B(\dp_dut/dollar_05_num [6]),
	.A(n37));
   XOR2X1 U285 (.Y(\dp_dut/N186 ),
	.B(n60),
	.A(\dp_dut/dollar_05_num [7]));
   XOR2X1 U286 (.Y(\dp_dut/N187 ),
	.B(\dp_dut/dollar_025_num [0]),
	.A(n68));
   XOR2X1 U287 (.Y(\dp_dut/N188 ),
	.B(\dp_dut/dollar_025_num [1]),
	.A(n26));
   XOR2X1 U288 (.Y(\dp_dut/N189 ),
	.B(\dp_dut/dollar_025_num [2]),
	.A(n28));
   XOR2X1 U289 (.Y(\dp_dut/N190 ),
	.B(\dp_dut/dollar_025_num [3]),
	.A(n33));
   XOR2X1 U290 (.Y(\dp_dut/N191 ),
	.B(\dp_dut/dollar_025_num [4]),
	.A(n7));
   XOR2X1 U291 (.Y(\dp_dut/N192 ),
	.B(\dp_dut/dollar_025_num [5]),
	.A(n34));
   XOR2X1 U292 (.Y(\dp_dut/N193 ),
	.B(\dp_dut/dollar_025_num [6]),
	.A(n38));
   XOR2X1 U293 (.Y(\dp_dut/N194 ),
	.B(n61),
	.A(\dp_dut/dollar_025_num [7]));
   XOR2X1 U294 (.Y(\dp_dut/dp_cluster_0/N95 ),
	.B(\dp_dut/inserted_money [4]),
	.A(n13));
   XOR2X1 U295 (.Y(\dp_dut/dp_cluster_0/N96 ),
	.B(\dp_dut/inserted_money [5]),
	.A(n14));
   XOR2X1 U296 (.Y(\dp_dut/dp_cluster_0/N97 ),
	.B(\dp_dut/inserted_money [6]),
	.A(n15));
   XOR2X1 U297 (.Y(\dp_dut/dp_cluster_0/N98 ),
	.B(\dp_dut/inserted_money [7]),
	.A(n27));
   XOR2X1 U298 (.Y(\dp_dut/dp_cluster_0/N99 ),
	.B(\dp_dut/inserted_money [8]),
	.A(n5));
   XOR2X1 U299 (.Y(\dp_dut/dp_cluster_0/N100 ),
	.B(\dp_dut/inserted_money [9]),
	.A(n21));
   XOR2X1 U300 (.Y(\dp_dut/dp_cluster_0/N101 ),
	.B(\dp_dut/inserted_money [10]),
	.A(n22));
   XOR2X1 U301 (.Y(\dp_dut/dp_cluster_0/N102 ),
	.B(\dp_dut/inserted_money [11]),
	.A(n23));
   XOR2X1 U302 (.Y(\dp_dut/dp_cluster_0/N103 ),
	.B(\dp_dut/inserted_money [12]),
	.A(n29));
   XOR2X1 U303 (.Y(\dp_dut/dp_cluster_0/N104 ),
	.B(\dp_dut/inserted_money [13]),
	.A(n35));
   XOR2X1 U304 (.Y(\dp_dut/dp_cluster_0/N105 ),
	.B(\dp_dut/inserted_money [14]),
	.A(n8));
   XOR2X1 U305 (.Y(\dp_dut/dp_cluster_0/N106 ),
	.B(n62),
	.A(\dp_dut/inserted_money [15]));
   XOR2X1 U306 (.Y(\dp_dut/dp_cluster_0/N146 ),
	.B(\dp_dut/dp_cluster_0/N98 ),
	.A(n42));
   XOR2X1 U307 (.Y(\dp_dut/dp_cluster_0/N147 ),
	.B(\dp_dut/dp_cluster_0/N99 ),
	.A(n44));
   XOR2X1 U308 (.Y(\dp_dut/dp_cluster_0/N148 ),
	.B(\dp_dut/dp_cluster_0/N100 ),
	.A(n45));
   XOR2X1 U309 (.Y(\dp_dut/dp_cluster_0/N149 ),
	.B(\dp_dut/dp_cluster_0/N101 ),
	.A(n46));
   XOR2X1 U310 (.Y(\dp_dut/dp_cluster_0/N150 ),
	.B(\dp_dut/dp_cluster_0/N102 ),
	.A(n47));
   XOR2X1 U311 (.Y(\dp_dut/dp_cluster_0/N151 ),
	.B(\dp_dut/dp_cluster_0/N103 ),
	.A(n48));
   XOR2X1 U312 (.Y(\dp_dut/dp_cluster_0/N152 ),
	.B(\dp_dut/dp_cluster_0/N104 ),
	.A(n49));
   XOR2X1 U313 (.Y(\dp_dut/dp_cluster_0/N153 ),
	.B(\dp_dut/dp_cluster_0/N105 ),
	.A(n50));
   XOR2X1 U314 (.Y(\dp_dut/dp_cluster_0/N154 ),
	.B(n63),
	.A(\dp_dut/dp_cluster_0/N106 ));
   XOR2X1 U315 (.Y(\dp_dut/N156 ),
	.B(n68),
	.A(\dp_dut/inserted_money [1]));
   XOR2X1 U316 (.Y(\dp_dut/N159 ),
	.B(\dp_dut/dp_cluster_0/N143 ),
	.A(n41));
   XOR2X1 U317 (.Y(\dp_dut/N160 ),
	.B(\dp_dut/dp_cluster_0/N144 ),
	.A(n51));
   XOR2X1 U318 (.Y(\dp_dut/N161 ),
	.B(\dp_dut/dp_cluster_0/N145 ),
	.A(n59));
   XOR2X1 U319 (.Y(\dp_dut/N162 ),
	.B(\dp_dut/dp_cluster_0/N146 ),
	.A(n9));
   XOR2X1 U320 (.Y(\dp_dut/N163 ),
	.B(\dp_dut/dp_cluster_0/N147 ),
	.A(n52));
   XOR2X1 U321 (.Y(\dp_dut/N164 ),
	.B(\dp_dut/dp_cluster_0/N148 ),
	.A(n53));
   XOR2X1 U322 (.Y(\dp_dut/N165 ),
	.B(\dp_dut/dp_cluster_0/N149 ),
	.A(n54));
   XOR2X1 U323 (.Y(\dp_dut/N166 ),
	.B(\dp_dut/dp_cluster_0/N150 ),
	.A(n55));
   XOR2X1 U324 (.Y(\dp_dut/N167 ),
	.B(\dp_dut/dp_cluster_0/N151 ),
	.A(n56));
   XOR2X1 U325 (.Y(\dp_dut/N168 ),
	.B(\dp_dut/dp_cluster_0/N152 ),
	.A(n57));
   XOR2X1 U326 (.Y(\dp_dut/N169 ),
	.B(\dp_dut/dp_cluster_0/N153 ),
	.A(n58));
   XOR2X1 U327 (.Y(\dp_dut/N170 ),
	.B(n64),
	.A(\dp_dut/dp_cluster_0/N154 ));
   XOR2X1 U328 (.Y(\dp_dut/dp_cluster_1/N34 ),
	.B(out_csel_c),
	.A(out_csel_d));
   XOR2X1 U329 (.Y(\dp_dut/N38 ),
	.B(out_csel_a),
	.A(out_csel_c));
   XOR2X1 U330 (.Y(\dp_dut/dp_cluster_0/N94 ),
	.B(\dp_dut/inserted_money [3]),
	.A(in_inserted_5));
   XOR2X1 U331 (.Y(\dp_dut/dp_cluster_0/N142 ),
	.B(\dp_dut/dp_cluster_0/N94 ),
	.A(in_inserted_1));
   XOR2X1 U332 (.Y(\dp_dut/dp_cluster_1/N28 ),
	.B(out_csel_a),
	.A(out_csel_b));
   XOR2X1 U333 (.Y(\dp_dut/N39 ),
	.B(\dp_dut/dp_cluster_1/N28 ),
	.A(n36));
   XOR2X1 U334 (.Y(\dp_dut/N158 ),
	.B(\dp_dut/dp_cluster_0/N142 ),
	.A(\dp_dut/dp_cluster_0/add_0_root_add_121_5/carry[3] ));
   XOR2X1 U335 (.Y(\dp_dut/dp_cluster_0/N143 ),
	.B(\dp_dut/dp_cluster_0/N95 ),
	.A(n18));
   XOR2X1 U336 (.Y(\dp_dut/dp_cluster_0/N145 ),
	.B(\dp_dut/dp_cluster_0/N97 ),
	.A(\dp_dut/dp_cluster_0/add_1_root_add_121_5/carry[6] ));
   NAND2X1 U337 (.Y(n75),
	.B(n131),
	.A(cmd[1]));
   NAND2X1 U338 (.Y(n76),
	.B(n131),
	.A(cmd[1]));
   BUFX2 U339 (.Y(n77),
	.A(n75));
   BUFX2 U340 (.Y(n78),
	.A(n75));
   BUFX2 U341 (.Y(n79),
	.A(n76));
   BUFX2 U342 (.Y(n80),
	.A(n76));
   BUFX2 U343 (.Y(n81),
	.A(\dp_dut/n202 ));
   BUFX2 U344 (.Y(n82),
	.A(\dp_dut/n202 ));
   AND2X2 U345 (.Y(n262),
	.B(n260),
	.A(n261));
   INVX2 U346 (.Y(n99),
	.A(\dp_dut/n341 ));
   INVX2 U347 (.Y(n100),
	.A(in_restart));
   INVX2 U348 (.Y(n101),
	.A(\dp_dut/n248 ));
   INVX2 U349 (.Y(n102),
	.A(\dp_dut/n234 ));
   INVX2 U350 (.Y(n103),
	.A(in_sel_a));
   INVX2 U351 (.Y(n104),
	.A(in_sel_b));
   INVX2 U352 (.Y(n105),
	.A(in_sel_c));
   INVX2 U353 (.Y(n106),
	.A(in_sel_d));
   INVX2 U354 (.Y(n107),
	.A(\dp_dut/n373 ));
   INVX2 U355 (.Y(n108),
	.A(\dp_dut/n239 ));
   INVX2 U356 (.Y(n109),
	.A(\dp_dut/n342 ));
   INVX2 U357 (.Y(n110),
	.A(\dp_dut/n272 ));
   INVX2 U358 (.Y(out_sol_ok),
	.A(\dp_dut/n389 ));
   INVX2 U359 (.Y(n112),
	.A(\dp_dut/n210 ));
   INVX2 U360 (.Y(n113),
	.A(n229));
   INVX2 U361 (.Y(n114),
	.A(\dp_dut/n225 ));
   INVX2 U362 (.Y(n115),
	.A(n233));
   INVX2 U363 (.Y(n116),
	.A(\dp_dut/n222 ));
   INVX2 U364 (.Y(n117),
	.A(\dp_dut/n220 ));
   INVX2 U365 (.Y(n118),
	.A(n230));
   INVX2 U366 (.Y(n119),
	.A(\dp_dut/n218 ));
   INVX2 U367 (.Y(n120),
	.A(\dp_dut/n216 ));
   INVX2 U368 (.Y(n121),
	.A(n234));
   INVX2 U369 (.Y(n122),
	.A(\dp_dut/n214 ));
   INVX2 U370 (.Y(n123),
	.A(\dp_dut/n212 ));
   INVX2 U371 (.Y(n124),
	.A(\dp_dut/n208 ));
   INVX2 U372 (.Y(out_change[15]),
	.A(\dp_dut/n203 ));
   INVX2 U373 (.Y(n126),
	.A(\dp_dut/total_price [1]));
   INVX2 U374 (.Y(n127),
	.A(\dp_dut/total_price [2]));
   INVX2 U375 (.Y(n128),
	.A(n246));
   INVX2 U376 (.Y(n129),
	.A(\dp_dut/total_price [4]));
   INVX2 U377 (.Y(n130),
	.A(\dp_dut/total_price [5]));
   INVX2 U378 (.Y(n131),
	.A(cmd[0]));
   INVX2 U379 (.Y(n132),
	.A(\dp_dut/n388 ));
   INVX2 U380 (.Y(n133),
	.A(\main_FSM_dut/next_out_state[1] ));
   INVX2 U381 (.Y(n134),
	.A(out_state[0]));
   INVX2 U382 (.Y(n135),
	.A(out_change_05));
   INVX2 U383 (.Y(n136),
	.A(out_change_1[1]));
   INVX2 U384 (.Y(n137),
	.A(\dp_dut/dollar_05_num [6]));
   INVX2 U385 (.Y(n138),
	.A(\dp_dut/dollar_05_num [5]));
   INVX2 U386 (.Y(n139),
	.A(\dp_dut/dollar_05_num [4]));
   INVX2 U387 (.Y(n140),
	.A(\dp_dut/dollar_05_num [3]));
   INVX2 U388 (.Y(n141),
	.A(\dp_dut/dollar_05_num [2]));
   INVX2 U389 (.Y(n142),
	.A(\dp_dut/dollar_05_num [7]));
   INVX2 U390 (.Y(n143),
	.A(\dp_dut/dollar_05_num [0]));
   INVX2 U391 (.Y(n144),
	.A(\dp_dut/dollar_025_num [6]));
   INVX2 U392 (.Y(n145),
	.A(\dp_dut/dollar_025_num [5]));
   INVX2 U393 (.Y(n146),
	.A(\dp_dut/dollar_025_num [4]));
   INVX2 U394 (.Y(n147),
	.A(\dp_dut/dollar_025_num [3]));
   INVX2 U395 (.Y(n148),
	.A(\dp_dut/dollar_025_num [2]));
   INVX2 U396 (.Y(n149),
	.A(\dp_dut/dollar_025_num [1]));
   INVX2 U397 (.Y(n150),
	.A(\dp_dut/dollar_025_num [7]));
   INVX2 U398 (.Y(n151),
	.A(\dp_dut/dollar_025_num [0]));
   INVX2 U399 (.Y(n152),
	.A(\dp_dut/dollar_1_num [3]));
   INVX2 U400 (.Y(n153),
	.A(\dp_dut/dollar_1_num [5]));
   INVX2 U401 (.Y(n154),
	.A(out_change_1[0]));
   INVX2 U402 (.Y(n155),
	.A(out_change_1[2]));
   INVX2 U403 (.Y(n156),
	.A(out_change_1[3]));
   INVX2 U404 (.Y(n157),
	.A(out_change_1[4]));
   INVX2 U405 (.Y(n158),
	.A(out_change_1[5]));
   INVX2 U406 (.Y(n159),
	.A(out_change_1[6]));
   INVX2 U407 (.Y(n160),
	.A(out_change_1[7]));
   INVX2 U408 (.Y(n161),
	.A(out_change_025));
   INVX2 U409 (.Y(n162),
	.A(\dp_dut/item_d_num [7]));
   INVX2 U410 (.Y(n163),
	.A(\dp_dut/item_d_num [6]));
   INVX2 U411 (.Y(n164),
	.A(\dp_dut/item_d_num [5]));
   INVX2 U412 (.Y(n165),
	.A(\dp_dut/item_d_num [4]));
   INVX2 U413 (.Y(n166),
	.A(\dp_dut/item_d_num [3]));
   INVX2 U414 (.Y(n167),
	.A(\dp_dut/item_d_num [2]));
   INVX2 U415 (.Y(n168),
	.A(\dp_dut/item_d_num [1]));
   INVX2 U416 (.Y(n169),
	.A(\dp_dut/item_d_num [0]));
   INVX2 U417 (.Y(n170),
	.A(out_csel_d));
   INVX2 U418 (.Y(n171),
	.A(\dp_dut/item_c_num [7]));
   INVX2 U419 (.Y(n172),
	.A(\dp_dut/item_c_num [6]));
   INVX2 U420 (.Y(n173),
	.A(\dp_dut/item_c_num [5]));
   INVX2 U421 (.Y(n174),
	.A(\dp_dut/item_c_num [4]));
   INVX2 U422 (.Y(n175),
	.A(\dp_dut/item_c_num [3]));
   INVX2 U423 (.Y(n176),
	.A(\dp_dut/item_c_num [2]));
   INVX2 U424 (.Y(n177),
	.A(\dp_dut/item_c_num [1]));
   INVX2 U425 (.Y(n178),
	.A(\dp_dut/item_c_num [0]));
   INVX2 U426 (.Y(n179),
	.A(out_csel_c));
   INVX2 U427 (.Y(n180),
	.A(\dp_dut/item_a_num [7]));
   INVX2 U428 (.Y(n181),
	.A(\dp_dut/item_a_num [6]));
   INVX2 U429 (.Y(n182),
	.A(\dp_dut/item_a_num [5]));
   INVX2 U430 (.Y(n183),
	.A(\dp_dut/item_a_num [4]));
   INVX2 U431 (.Y(n184),
	.A(\dp_dut/item_a_num [3]));
   INVX2 U432 (.Y(n185),
	.A(\dp_dut/item_a_num [2]));
   INVX2 U433 (.Y(n186),
	.A(\dp_dut/item_a_num [1]));
   INVX2 U434 (.Y(n187),
	.A(\dp_dut/item_a_num [0]));
   INVX2 U435 (.Y(n188),
	.A(out_csel_a));
   INVX2 U436 (.Y(n189),
	.A(\dp_dut/inserted_money [13]));
   INVX2 U437 (.Y(n190),
	.A(\dp_dut/inserted_money [12]));
   INVX2 U438 (.Y(n191),
	.A(\dp_dut/inserted_money [11]));
   INVX2 U439 (.Y(n192),
	.A(\dp_dut/inserted_money [10]));
   INVX2 U440 (.Y(n193),
	.A(\dp_dut/inserted_money [9]));
   INVX2 U441 (.Y(n194),
	.A(n252));
   INVX2 U442 (.Y(n195),
	.A(\dp_dut/inserted_money [8]));
   INVX2 U443 (.Y(n196),
	.A(\dp_dut/inserted_money [7]));
   INVX2 U444 (.Y(n197),
	.A(\dp_dut/inserted_money [6]));
   INVX2 U445 (.Y(n198),
	.A(\dp_dut/inserted_money [5]));
   INVX2 U446 (.Y(n199),
	.A(\dp_dut/inserted_money [4]));
   INVX2 U447 (.Y(n200),
	.A(\dp_dut/inserted_money [3]));
   INVX2 U448 (.Y(n201),
	.A(\dp_dut/inserted_money [2]));
   INVX2 U449 (.Y(n202),
	.A(\dp_dut/inserted_money [1]));
   INVX2 U450 (.Y(n203),
	.A(\dp_dut/N155 ));
   INVX2 U451 (.Y(n204),
	.A(\dp_dut/item_b_num [6]));
   INVX2 U452 (.Y(n205),
	.A(\dp_dut/item_b_num [5]));
   INVX2 U453 (.Y(n206),
	.A(\dp_dut/item_b_num [4]));
   INVX2 U454 (.Y(n207),
	.A(\dp_dut/item_b_num [3]));
   INVX2 U455 (.Y(n208),
	.A(\dp_dut/item_b_num [2]));
   INVX2 U456 (.Y(n209),
	.A(\dp_dut/item_b_num [1]));
   INVX2 U457 (.Y(n210),
	.A(\dp_dut/item_b_num [0]));
   INVX2 U458 (.Y(n211),
	.A(\dp_dut/item_b_num [7]));
   INVX2 U459 (.Y(n212),
	.A(\dp_dut/dollar_1_num [0]));
   INVX2 U460 (.Y(n213),
	.A(\dp_dut/dollar_1_num [7]));
   INVX2 U461 (.Y(n214),
	.A(\dp_dut/dollar_1_num [1]));
   INVX2 U462 (.Y(n215),
	.A(\dp_dut/inserted_money [14]));
   INVX2 U463 (.Y(n216),
	.A(\dp_dut/inserted_money [15]));
   INVX2 U464 (.Y(n217),
	.A(out_csel_b));
   NAND2X1 U465 (.Y(n248),
	.B(n202),
	.A(\dp_dut/total_price [1]));
   NAND2X1 U466 (.Y(n254),
	.B(n198),
	.A(\dp_dut/total_price [5]));
   NAND2X1 U467 (.Y(n252),
	.B(n247),
	.A(n197));
   NOR2X1 U468 (.Y(n219),
	.B(\dp_dut/dollar_025_num [6]),
	.A(\dp_dut/dollar_025_num [7]));
   NOR2X1 U469 (.Y(n218),
	.B(\dp_dut/dollar_025_num [3]),
	.A(\dp_dut/dollar_025_num [4]));
   NAND3X1 U470 (.Y(n222),
	.C(n218),
	.B(n145),
	.A(n219));
   NOR2X1 U471 (.Y(n220),
	.B(\dp_dut/dollar_025_num [1]),
	.A(\dp_dut/dollar_025_num [2]));
   NAND3X1 U472 (.Y(n221),
	.C(n220),
	.B(n151),
	.A(n112));
   OR2X1 U473 (.Y(\dp_dut/N63 ),
	.B(n221),
	.A(n222));
   NOR2X1 U474 (.Y(n224),
	.B(\dp_dut/dollar_05_num [6]),
	.A(\dp_dut/dollar_05_num [7]));
   NOR2X1 U475 (.Y(n223),
	.B(\dp_dut/dollar_05_num [3]),
	.A(\dp_dut/dollar_05_num [4]));
   NAND3X1 U476 (.Y(n227),
	.C(n223),
	.B(n138),
	.A(n224));
   NOR2X1 U477 (.Y(n225),
	.B(\dp_dut/dollar_05_num [1]),
	.A(\dp_dut/dollar_05_num [2]));
   NAND3X1 U478 (.Y(n226),
	.C(n225),
	.B(n143),
	.A(n124));
   OR2X1 U479 (.Y(\dp_dut/N62 ),
	.B(n226),
	.A(n227));
   NAND2X1 U480 (.Y(n232),
	.B(n152),
	.A(n117));
   NAND3X1 U481 (.Y(n228),
	.C(\dp_dut/dollar_1_num [2]),
	.B(\dp_dut/n222 ),
	.A(n232));
   OAI21X1 U482 (.Y(n235),
	.C(n228),
	.B(n152),
	.A(n117));
   AOI22X1 U483 (.Y(n229),
	.D(n114),
	.C(n212),
	.B(\dp_dut/out_change_1_sol1[1] ),
	.A(n214));
   OAI21X1 U484 (.Y(n231),
	.C(n113),
	.B(n214),
	.A(\dp_dut/out_change_1_sol1[1] ));
   NAND2X1 U485 (.Y(n238),
	.B(n153),
	.A(n120));
   OAI21X1 U486 (.Y(n230),
	.C(n238),
	.B(\dp_dut/dollar_1_num [4]),
	.A(\dp_dut/n218 ));
   OAI21X1 U487 (.Y(n244),
	.C(n118),
	.B(n231),
	.A(n235));
   OAI21X1 U488 (.Y(n233),
	.C(n232),
	.B(\dp_dut/dollar_1_num [2]),
	.A(\dp_dut/n222 ));
   NAND2X1 U489 (.Y(n236),
	.B(n213),
	.A(n123));
   OAI21X1 U490 (.Y(n234),
	.C(n236),
	.B(\dp_dut/n214 ),
	.A(\dp_dut/dollar_1_num [6]));
   OAI21X1 U491 (.Y(n243),
	.C(n121),
	.B(n235),
	.A(n115));
   NAND3X1 U492 (.Y(n237),
	.C(\dp_dut/dollar_1_num [6]),
	.B(\dp_dut/n214 ),
	.A(n236));
   OAI21X1 U493 (.Y(n241),
	.C(n237),
	.B(n213),
	.A(n123));
   NAND3X1 U494 (.Y(n239),
	.C(\dp_dut/dollar_1_num [4]),
	.B(\dp_dut/n218 ),
	.A(n238));
   OAI21X1 U495 (.Y(n240),
	.C(n239),
	.B(n153),
	.A(n120));
   OAI22X1 U496 (.Y(n242),
	.D(n241),
	.C(n121),
	.B(n240),
	.A(n241));
   OAI21X1 U497 (.Y(\dp_dut/N61 ),
	.C(n242),
	.B(n243),
	.A(n244));
   NAND2X1 U498 (.Y(n249),
	.B(n10),
	.A(\dp_dut/inserted_money [3]));
   NAND3X1 U499 (.Y(n245),
	.C(\dp_dut/total_price [2]),
	.B(n201),
	.A(n249));
   OAI21X1 U500 (.Y(n246),
	.C(n245),
	.B(n10),
	.A(\dp_dut/inserted_money [3]));
   NOR2X1 U501 (.Y(n247),
	.B(\dp_dut/inserted_money [7]),
	.A(\dp_dut/inserted_money [8]));
   AOI21X1 U502 (.Y(n258),
	.C(n252),
	.B(n128),
	.A(n248));
   OAI21X1 U503 (.Y(n251),
	.C(n249),
	.B(n201),
	.A(\dp_dut/total_price [2]));
   OR2X1 U504 (.Y(n253),
	.B(\dp_dut/total_price [5]),
	.A(n198));
   OAI21X1 U505 (.Y(n250),
	.C(n253),
	.B(n199),
	.A(\dp_dut/total_price [4]));
   AOI21X1 U506 (.Y(n257),
	.C(n250),
	.B(n251),
	.A(n128));
   NAND2X1 U507 (.Y(n255),
	.B(n199),
	.A(n253));
   OAI21X1 U508 (.Y(n256),
	.C(n254),
	.B(n255),
	.A(n129));
   AOI22X1 U509 (.Y(n259),
	.D(n256),
	.C(n194),
	.B(n257),
	.A(n258));
   NOR2X1 U510 (.Y(n264),
	.B(n259),
	.A(\dp_dut/inserted_money [10]));
   NOR2X1 U511 (.Y(n263),
	.B(\dp_dut/inserted_money [11]),
	.A(\dp_dut/inserted_money [12]));
   NOR2X1 U512 (.Y(n261),
	.B(\dp_dut/inserted_money [13]),
	.A(\dp_dut/inserted_money [14]));
   NOR2X1 U513 (.Y(n260),
	.B(\dp_dut/inserted_money [15]),
	.A(\dp_dut/inserted_money [9]));
   NAND3X1 U514 (.Y(\dp_dut/N196 ),
	.C(n262),
	.B(n263),
	.A(n264));
endmodule

